import { withProfile, type ProfileName } from './fragrance-expansion';
import type {
  FragranceSeed,
  GenderStyle,
  Longevity,
  PriceRange,
  Projection,
  ScentFamily,
  Tier,
} from './fragrances';

type EntryOverrides = Partial<Pick<
  FragranceSeed,
  'genderStyle' | 'projection' | 'longevity'
>>;

type BrandEntry = [
  id: string,
  name: string,
  profile: ProfileName,
  scentFamilies: ScentFamily[],
  accords: string[],
  notes: string[],
  vibeTags: string[],
  shortDescription: string,
  overrides?: EntryOverrides,
];

type BrandDefaults = {
  brand: string;
  priceRange: PriceRange;
  priceDisplay: string;
  genderStyle: GenderStyle;
  projection: Projection;
  longevity: Longevity;
  tier: Tier;
};

function expandBrand(defaults: BrandDefaults, entries: BrandEntry[]): FragranceSeed[] {
  return entries.map(([
    id,
    name,
    profile,
    scentFamilies,
    accords,
    notes,
    vibeTags,
    shortDescription,
    overrides = {},
  ]) => withProfile({
    ...defaults,
    id,
    name,
    profile,
    scentFamilies,
    accords,
    notes,
    vibeTags,
    shortDescription,
    ...overrides,
  }));
}

const zoologist = expandBrand(
  {
    brand: 'Zoologist',
    priceRange: 'niche',
    priceDisplay: '$175-$210',
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
  },
  [
    [
      'zoologist-bee',
      'Bee',
      'sweet-gourmand',
      ['sweet', 'gourmand', 'floral'],
      ['honey', 'beeswax', 'vanilla', 'floral'],
      ['orange', 'royal jelly', 'honey', 'beeswax', 'vanilla'],
      ['honeyed', 'golden', 'dense', 'artistic', 'comforting'],
      'A lavish cloud of honey, wax, florals, and warm vanilla.',
    ],
    [
      'zoologist-squid',
      'Squid',
      'smoky-dark',
      ['aquatic', 'oriental', 'spicy'],
      ['marine', 'incense', 'inky', 'amber'],
      ['pink pepper', 'ink', 'incense', 'ambergris', 'benzoin'],
      ['deep-sea', 'inky', 'mysterious', 'salty', 'experimental'],
      'Dark oceanic ink, incense, and ambergris with cinematic depth.',
    ],
    [
      'zoologist-cow',
      'Cow',
      'green-woody',
      ['fresh', 'floral', 'clean'],
      ['green', 'lactonic', 'apple', 'floral'],
      ['sage', 'apple', 'milk', 'heliotrope', 'musk'],
      ['meadow', 'milky', 'gentle', 'green', 'comforting'],
      'Fresh meadow air, crisp apple, soft milk, and clean musk.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-harvest-mouse',
      'Harvest Mouse',
      'sweet-gourmand',
      ['sweet', 'woody', 'gourmand'],
      ['hay', 'vanilla', 'beer', 'woody'],
      ['bergamot', 'hay', 'beer', 'chamomile', 'vanilla'],
      ['cozy', 'countryside', 'warm', 'toasted', 'whimsical'],
      'Sunlit hay, chamomile, beer, and vanilla in a cozy field.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-rabbit',
      'Rabbit',
      'sweet-gourmand',
      ['gourmand', 'sweet', 'floral'],
      ['carrot cake', 'hay', 'vanilla', 'green'],
      ['cinnamon', 'apple', 'carrot', 'hay', 'vanilla'],
      ['playful', 'baked', 'soft', 'garden', 'comforting'],
      'A playful carrot-cake gourmand softened by hay and green leaves.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-penguin',
      'Penguin',
      'fresh-aquatic',
      ['fresh', 'aquatic', 'woody'],
      ['icy', 'marine', 'suede', 'musk'],
      ['antarctic air', 'ice', 'juniper', 'suede', 'musk'],
      ['frozen', 'mineral', 'clean', 'remote', 'modern'],
      'Icy air, juniper, suede, and musk with polar clarity.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-tyrannosaurus-rex',
      'Tyrannosaurus Rex',
      'smoky-dark',
      ['woody', 'spicy', 'oriental'],
      ['smoke', 'resinous', 'leather', 'floral'],
      ['black pepper', 'fir', 'incense', 'leather', 'cade'],
      ['extreme', 'volcanic', 'smoky', 'challenging', 'bold'],
      'An uncompromising eruption of smoke, resin, leather, and florals.',
    ],
    [
      'zoologist-moth',
      'Moth',
      'smoky-dark',
      ['spicy', 'floral', 'oriental'],
      ['powdery', 'smoky', 'honey', 'spicy'],
      ['clove', 'saffron', 'honey', 'heliotrope', 'smoke'],
      ['dusty', 'gothic', 'powdery', 'antique', 'mysterious'],
      'Dusty florals, honey, spice, and smoke in a gothic haze.',
    ],
    [
      'zoologist-seahorse',
      'Seahorse',
      'fresh-aquatic',
      ['aquatic', 'fresh', 'floral'],
      ['marine', 'aromatic', 'floral', 'salty'],
      ['cardamom', 'fennel', 'tuberose', 'seaweed', 'ambergris'],
      ['oceanic', 'transparent', 'unusual', 'bright', 'salty'],
      'A transparent marine floral with fennel, seaweed, and ambergris.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-snowy-owl',
      'Snowy Owl',
      'green-woody',
      ['fresh', 'clean', 'woody'],
      ['earthy', 'minty', 'powdery', 'musky'],
      ['snow accord', 'mint', 'coconut', 'orris', 'musk'],
      ['snowy', 'quiet', 'earthy', 'cool', 'textural'],
      'Cool snow, mint, earth, orris, and soft feather-like musk.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-camel',
      'Camel',
      'amber-spicy',
      ['oriental', 'spicy', 'woody'],
      ['dried fruit', 'amber', 'incense', 'animalic'],
      ['dates', 'dried fruit', 'incense', 'myrrh', 'oud'],
      ['desert', 'resinous', 'rich', 'spiced', 'nomadic'],
      'Dried fruit, incense, amber, and woods crossing a warm desert.',
    ],
    [
      'zoologist-panda',
      'Panda',
      'green-woody',
      ['fresh', 'woody', 'citrus'],
      ['green', 'apple', 'earthy', 'musky'],
      ['apple', 'magnolia', 'bamboo', 'tea', 'musk'],
      ['lush', 'bamboo', 'fruity', 'earthy', 'energetic'],
      'Juicy apple, bamboo, tea, flowers, and damp forest earth.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-hummingbird',
      'Hummingbird',
      'floral-bold',
      ['floral', 'sweet', 'gourmand'],
      ['floral', 'fruity', 'honey', 'powdery'],
      ['apple', 'cherry', 'honeysuckle', 'lilac', 'honey'],
      ['nectar', 'lush', 'romantic', 'colorful', 'opulent'],
      'A vivid nectar of fruit, lilac, honeysuckle, and honey.',
    ],
    [
      'zoologist-chameleon',
      'Chameleon',
      'citrus-beach',
      ['floral', 'sweet', 'aquatic'],
      ['tropical', 'floral', 'salty', 'creamy'],
      ['bergamot', 'mango', 'ylang-ylang', 'sea salt', 'vanilla'],
      ['tropical', 'colorful', 'beach', 'creamy', 'playful'],
      'Tropical fruit, creamy flowers, sea salt, and sun-warmed skin.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-sacred-scarab',
      'Sacred Scarab',
      'amber-spicy',
      ['oriental', 'floral', 'woody'],
      ['incense', 'wine', 'resinous', 'animalic'],
      ['aldehydes', 'wine', 'lotus', 'incense', 'myrrh'],
      ['ancient', 'ceremonial', 'resinous', 'opulent', 'artistic'],
      'Wine, lotus, incense, and resins with ancient ceremonial richness.',
    ],
    [
      'zoologist-tiger',
      'Tiger',
      'green-woody',
      ['woody', 'spicy', 'citrus'],
      ['vetiver', 'citrus', 'spicy', 'smoky'],
      ['kumquat', 'cardamom', 'carrot seed', 'vetiver', 'incense'],
      ['focused', 'dry', 'powerful', 'wild', 'elegant'],
      'Dry vetiver, bright citrus, spice, and incense with controlled power.',
    ],
    [
      'zoologist-king-cobra',
      'King Cobra',
      'smoky-dark',
      ['woody', 'spicy', 'oriental'],
      ['cannabis', 'incense', 'green', 'leather'],
      ['camphor', 'cannabis', 'fig leaf', 'incense', 'leather'],
      ['dangerous', 'herbal', 'smoky', 'dark', 'experimental'],
      'Camphorous greens, incense, leather, and venomous herbal smoke.',
    ],
    [
      'zoologist-portuguese-man-o-war',
      "Portuguese Man O' War",
      'fresh-aquatic',
      ['aquatic', 'fresh', 'spicy'],
      ['marine', 'mineral', 'aromatic', 'salty'],
      ['lemon', 'lavender', 'sea salt', 'mineral amber', 'musk'],
      ['electric', 'oceanic', 'mineral', 'bright', 'unusual'],
      'Electric citrus, aromatic herbs, salt, and mineral ocean air.',
    ],
  ],
);

const maisonMargiela = expandBrand(
  {
    brand: 'Maison Margiela',
    priceRange: 'designer',
    priceDisplay: '$85-$180',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
  },
  [
    [
      'replica-whispers-in-the-library',
      'REPLICA Whispers in the Library',
      'woody-elegant',
      ['woody', 'sweet', 'spicy'],
      ['woody', 'vanilla', 'powdery', 'balsamic'],
      ['pepper', 'cedar', 'vanilla', 'benzoin'],
      ['library', 'paper', 'quiet', 'dark-academia', 'cozy'],
      'Polished wood, old paper, pepper, and vanilla in a quiet library.',
    ],
    [
      'replica-when-the-rain-stops',
      'REPLICA When the Rain Stops',
      'fresh-aquatic',
      ['fresh', 'aquatic', 'woody'],
      ['rain', 'aquatic', 'green', 'musky'],
      ['rain accord', 'pink pepper', 'rose', 'pine needle', 'moss'],
      ['rainy', 'clean', 'green', 'reflective', 'everyday'],
      'Rain-washed air, wet greenery, rose, and clean moss.',
    ],
    [
      'replica-autumn-vibes',
      'REPLICA Autumn Vibes',
      'green-woody',
      ['woody', 'spicy', 'fresh'],
      ['woody', 'earthy', 'spicy', 'mossy'],
      ['cardamom', 'pink pepper', 'maple', 'cedar', 'moss'],
      ['autumn', 'forest', 'crisp', 'earthy', 'cozy'],
      'Crisp leaves, cardamom, cedar, and moss on an autumn walk.',
    ],
    [
      'replica-matcha-meditation',
      'REPLICA Matcha Meditation',
      'green-woody',
      ['fresh', 'sweet', 'floral'],
      ['tea', 'green', 'white chocolate', 'floral'],
      ['green tea', 'matcha', 'orange blossom', 'jasmine', 'white chocolate'],
      ['tea', 'calm', 'creamy', 'mindful', 'soft'],
      'Green matcha, jasmine, orange blossom, and creamy white chocolate.',
    ],
    [
      'replica-bubble-bath',
      'REPLICA Bubble Bath',
      'fresh-clean',
      ['clean', 'floral', 'fresh'],
      ['soapy', 'coconut', 'musky', 'floral'],
      ['soap bubbles', 'lavender', 'rose', 'coconut', 'white musk'],
      ['soapy', 'spa', 'clean', 'comforting', 'minimal'],
      'A warm bath of clean soap, lavender, coconut, and white musk.',
      { projection: 'subtle' },
    ],
    [
      'replica-sailing-day',
      'REPLICA Sailing Day',
      'fresh-aquatic',
      ['aquatic', 'fresh', 'woody'],
      ['marine', 'aromatic', 'salty', 'woody'],
      ['aquatic accord', 'coriander', 'iris', 'seaweed', 'ambergris'],
      ['sailing', 'ocean', 'breezy', 'clean', 'summer'],
      'A brisk marine breeze with coriander, seaweed, and ambergris.',
    ],
    [
      'replica-springtime-in-a-park',
      'REPLICA Springtime in a Park',
      'floral-soft',
      ['floral', 'sweet', 'fresh'],
      ['floral', 'pear', 'green', 'musky'],
      ['pear', 'lily of the valley', 'rose', 'jasmine', 'musk'],
      ['spring', 'park', 'airy', 'romantic', 'daytime'],
      'Airy pear, lily of the valley, rose, and soft spring musk.',
      { projection: 'subtle' },
    ],
    [
      'replica-under-the-lemon-trees',
      'REPLICA Under the Lemon Trees',
      'citrus-beach',
      ['citrus', 'fresh', 'woody'],
      ['citrus', 'green', 'aromatic', 'woody'],
      ['lime', 'petitgrain', 'green tea', 'coriander', 'cedar'],
      ['lemon-grove', 'sunny', 'fresh', 'mediterranean', 'casual'],
      'Sunlit citrus leaves, green tea, herbs, and light woods.',
    ],
    [
      'replica-flower-market',
      'REPLICA Flower Market',
      'floral-soft',
      ['floral', 'fresh', 'clean'],
      ['floral', 'green', 'watery', 'fresh'],
      ['green leaves', 'freesia', 'jasmine', 'tuberose', 'rose'],
      ['bouquet', 'fresh-cut', 'spring', 'bright', 'romantic'],
      'A colorful market bouquet of fresh-cut stems and dewy petals.',
    ],
    [
      'replica-at-the-barbers',
      "REPLICA At the Barber's",
      'fresh-clean',
      ['fresh', 'clean', 'woody'],
      ['aromatic', 'lavender', 'soapy', 'woody'],
      ['basil', 'lavender', 'rosemary', 'tonka bean', 'moss'],
      ['barbershop', 'shaved', 'classic', 'clean', 'tailored'],
      'A classic clean shave of lavender, herbs, tonka, and moss.',
      { genderStyle: 'masculine' },
    ],
    [
      'replica-afternoon-delight',
      'REPLICA Afternoon Delight',
      'sweet-gourmand',
      ['gourmand', 'sweet', 'woody'],
      ['vanilla', 'biscuit', 'creamy', 'woody'],
      ['bitter almond', 'madeleine accord', 'sandalwood', 'vanilla', 'musk'],
      ['bakery', 'soft', 'comforting', 'vanilla', 'cozy'],
      'A tender madeleine, almond, vanilla, and sandalwood gourmand.',
    ],
    [
      'replica-up-at-dawn',
      'REPLICA Up at Dawn',
      'floral-soft',
      ['floral', 'fresh', 'clean'],
      ['floral', 'airy', 'musky', 'green'],
      ['pink pepper', 'rose', 'orange blossom', 'ambrette', 'musk'],
      ['dawn', 'light', 'hopeful', 'fresh', 'soft'],
      'A luminous dawn of rose, orange blossom, ambrette, and musk.',
    ],
    [
      'replica-chasing-sunsets',
      'REPLICA Chasing Sunsets',
      'citrus-beach',
      ['citrus', 'floral', 'fresh'],
      ['citrus', 'solar', 'floral', 'musky'],
      ['grapefruit', 'orange blossom', 'ylang-ylang', 'musk', 'amber'],
      ['sunset', 'vacation', 'warm', 'radiant', 'beach'],
      'Radiant citrus, solar florals, amber, and skin-warm musk.',
    ],
    [
      'replica-never-ending-summer',
      'REPLICA Never-ending Summer',
      'citrus-beach',
      ['citrus', 'fresh', 'woody'],
      ['citrus', 'aromatic', 'sparkling', 'woody'],
      ['orange', 'spritz accord', 'vetiver', 'ginger', 'cedar'],
      ['summer', 'aperitivo', 'sparkling', 'carefree', 'bright'],
      'A sparkling orange spritz with ginger, vetiver, and bright woods.',
    ],
    [
      'replica-on-a-date',
      'REPLICA On a Date',
      'floral-bold',
      ['floral', 'sweet', 'woody'],
      ['rose', 'fruity', 'woody', 'earthy'],
      ['blackcurrant', 'rose', 'geranium', 'patchouli', 'moss'],
      ['vineyard', 'date-night', 'romantic', 'wine', 'warm'],
      'Blackcurrant, rose, patchouli, and vineyard earth at sunset.',
    ],
    [
      'replica-from-the-garden',
      'REPLICA From the Garden',
      'green-woody',
      ['fresh', 'citrus', 'woody'],
      ['tomato leaf', 'green', 'earthy', 'citrus'],
      ['tomato leaf', 'green mandarin', 'geranium', 'patchouli', 'moss'],
      ['garden', 'tomato-leaf', 'earthy', 'fresh', 'natural'],
      'Crushed tomato leaves, citrus, geranium, and garden soil.',
    ],
    [
      'replica-soul-of-the-forest',
      'REPLICA Soul of the Forest',
      'green-woody',
      ['woody', 'fresh', 'spicy'],
      ['woody', 'resinous', 'green', 'aromatic'],
      ['blackcurrant', 'fir balsam', 'labdanum', 'cedar', 'moss'],
      ['enchanted-forest', 'resinous', 'deep', 'green', 'mysterious'],
      'A deep forest of fir balsam, cedar, moss, and dark fruit.',
      { longevity: 'long' },
    ],
    [
      'replica-celestial-whispers',
      'REPLICA Celestial Whispers',
      'skin-musk',
      ['floral', 'clean', 'sweet'],
      ['musky', 'powdery', 'floral', 'amber'],
      ['aldehydes', 'iris', 'jasmine', 'musk', 'amber'],
      ['ethereal', 'luminous', 'soft', 'dreamy', 'intimate'],
      'Ethereal aldehydes, iris, jasmine, musk, and luminous amber.',
      { longevity: 'long' },
    ],
    [
      'replica-flying',
      'REPLICA Flying',
      'fresh-aquatic',
      ['fresh', 'aquatic', 'citrus'],
      ['airy', 'citrus', 'aromatic', 'musky'],
      ['bergamot', 'orange blossom', 'neroli', 'almond', 'musk'],
      ['weightless', 'sky', 'bright', 'clean', 'uplifting'],
      'Weightless citrus, neroli, almond, and clean airborne musk.',
      { longevity: 'long' },
    ],
    [
      'replica-dancing-on-the-moon',
      'REPLICA Dancing on the Moon',
      'floral-bold',
      ['floral', 'clean', 'woody'],
      ['white floral', 'mineral', 'powdery', 'woody'],
      ['aldehydes', 'jasmine', 'frangipani', 'iris', 'cashmeran'],
      ['lunar', 'mineral', 'futuristic', 'white-floral', 'artistic'],
      'Lunar white florals, mineral dust, iris, and soft woods.',
      { longevity: 'long' },
    ],
    [
      'replica-ideal-one',
      'REPLICA Ideal One',
      'skin-musk',
      ['clean', 'woody', 'sweet'],
      ['skin musk', 'woody', 'amber', 'soft spicy'],
      ['pink pepper', 'orange blossom', 'ambroxan', 'musk', 'woods'],
      ['connection', 'intimate', 'modern', 'skin', 'magnetic'],
      'A magnetic skin scent of soft spice, ambroxan, musk, and woods.',
      { longevity: 'long' },
    ],
  ],
);

const maisonFrancisKurkdjian = expandBrand(
  {
    brand: 'Maison Francis Kurkdjian',
    priceRange: 'niche',
    priceDisplay: '$245-$395',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
  },
  [
    [
      'mfk-baccarat-rouge-540-extrait',
      'Baccarat Rouge 540 Extrait',
      'amber-spicy',
      ['oriental', 'sweet', 'woody'],
      ['amber', 'almond', 'woody', 'warm spicy'],
      ['bitter almond', 'saffron', 'jasmine', 'cedar', 'ambergris'],
      ['luxurious', 'radiant', 'intense', 'signature', 'evening'],
      'A richer almond, saffron, amber, and cedar interpretation of the icon.',
      { projection: 'strong' },
    ],
    [
      'mfk-724',
      '724',
      'fresh-clean',
      ['clean', 'fresh', 'floral'],
      ['aldehydic', 'musky', 'white floral', 'citrus'],
      ['bergamot', 'aldehydes', 'jasmine', 'sweet pea', 'white musk'],
      ['city', 'laundered', 'modern', 'bright', 'polished'],
      'Bright city air, aldehydes, white flowers, and immaculate musk.',
    ],
    [
      'mfk-aqua-universalis',
      'Aqua Universalis',
      'fresh-clean',
      ['citrus', 'clean', 'floral'],
      ['citrus', 'musky', 'white floral', 'fresh'],
      ['bergamot', 'lemon', 'lily of the valley', 'mock orange', 'musk'],
      ['crisp', 'linen', 'effortless', 'bright', 'everyday'],
      'Effortless citrus, white flowers, and clean linen-like musk.',
      { projection: 'subtle', longevity: 'moderate' },
    ],
    [
      'mfk-aqua-vitae',
      'Aqua Vitae',
      'citrus-beach',
      ['citrus', 'fresh', 'woody'],
      ['citrus', 'solar', 'spicy', 'woody'],
      ['lemon', 'mandarin', 'hedione', 'guaiac wood', 'tonka bean'],
      ['sunlit', 'warm-skin', 'bright', 'easy', 'refined'],
      'Sun-warmed citrus, airy florals, soft woods, and tonka.',
      { projection: 'subtle', longevity: 'moderate' },
    ],
    [
      'mfk-aqua-celestia-cologne-forte',
      'Aqua Celestia Cologne forte',
      'fresh-aquatic',
      ['fresh', 'citrus', 'clean'],
      ['citrus', 'green', 'musky', 'fruity'],
      ['bergamot', 'blackcurrant', 'mimosa', 'jasmine', 'musk'],
      ['sky-blue', 'airy', 'cool', 'optimistic', 'summer'],
      'A cool blue blend of bergamot, blackcurrant, mimosa, and musk.',
      { longevity: 'moderate' },
    ],
    [
      'mfk-aqua-media-cologne-forte',
      'Aqua Media Cologne forte',
      'green-woody',
      ['fresh', 'citrus', 'clean'],
      ['green', 'citrus', 'aromatic', 'musky'],
      ['bergamot', 'verbena', 'fennel', 'hedione', 'musk'],
      ['vivid-green', 'energizing', 'herbal', 'modern', 'fresh'],
      'Vivid bergamot, verbena, fennel, airy florals, and musk.',
      { longevity: 'moderate' },
    ],
    [
      'mfk-petit-matin',
      'Petit Matin',
      'fresh-clean',
      ['citrus', 'fresh', 'clean'],
      ['citrus', 'aromatic', 'musky', 'floral'],
      ['lemon', 'litsea cubeba', 'lavender', 'orange blossom', 'musk'],
      ['morning', 'sparkling', 'clean', 'optimistic', 'easy'],
      'A sparkling Paris morning of lemon, lavender, blossoms, and musk.',
      { longevity: 'moderate' },
    ],
    [
      'mfk-grand-soir',
      'Grand Soir',
      'amber-spicy',
      ['oriental', 'sweet', 'spicy'],
      ['amber', 'vanilla', 'balsamic', 'warm spicy'],
      ['labdanum', 'benzoin', 'amber', 'vanilla', 'tonka bean'],
      ['evening', 'golden', 'formal', 'warm', 'opulent'],
      'A grand golden amber of labdanum, benzoin, vanilla, and tonka.',
      { projection: 'strong' },
    ],
    [
      'mfk-gentle-fluidity-silver',
      'Gentle Fluidity Silver',
      'fresh-clean',
      ['fresh', 'woody', 'spicy'],
      ['aromatic', 'juniper', 'musky', 'woody'],
      ['juniper berries', 'coriander', 'nutmeg', 'amber woods', 'musk'],
      ['gin-tonic', 'crisp', 'tailored', 'cool', 'versatile'],
      'Crisp juniper, spice, amber woods, and musk with tailored freshness.',
    ],
    [
      'mfk-oud',
      'OUD',
      'woody-elegant',
      ['woody', 'spicy', 'oriental'],
      ['oud', 'saffron', 'woody', 'aromatic'],
      ['saffron', 'elemi', 'cedar', 'patchouli', 'oud'],
      ['precise', 'dry', 'luxurious', 'structured', 'evening'],
      'A precise composition of saffron, cedar, patchouli, and refined oud.',
    ],
    [
      'mfk-oud-satin-mood',
      'Oud Satin Mood',
      'floral-bold',
      ['oriental', 'floral', 'sweet'],
      ['rose', 'oud', 'vanilla', 'powdery'],
      ['violet', 'rose', 'oud', 'benzoin', 'vanilla'],
      ['satin', 'opulent', 'romantic', 'powerful', 'evening'],
      'Plush rose, violet, oud, benzoin, and vanilla with satin richness.',
      { projection: 'strong' },
    ],
    [
      'mfk-oud-satin-mood-extrait',
      'Oud Satin Mood Extrait',
      'floral-bold',
      ['oriental', 'floral', 'sweet'],
      ['rose', 'oud', 'cinnamon', 'vanilla'],
      ['cinnamon', 'rose', 'oud', 'benzoin', 'vanilla'],
      ['intense', 'velvety', 'rose', 'luxurious', 'statement'],
      'An intensified velvet rose, cinnamon, oud, benzoin, and vanilla.',
      { projection: 'strong' },
    ],
    [
      'mfk-oud-silk-mood',
      'Oud Silk Mood',
      'woody-elegant',
      ['woody', 'floral', 'fresh'],
      ['rose', 'oud', 'aromatic', 'woody'],
      ['bergamot', 'blue chamomile', 'rose', 'papyrus', 'oud'],
      ['silky', 'airy', 'refined', 'rose', 'architectural'],
      'Airy rose, blue chamomile, papyrus, and oud with silk-like texture.',
    ],
    [
      'mfk-apom',
      'APOM',
      'floral-soft',
      ['floral', 'woody', 'sweet'],
      ['orange blossom', 'lavender', 'amber', 'vanilla'],
      ['lavender', 'orange blossom', 'ylang-ylang', 'amber', 'vanilla'],
      ['radiant', 'intimate', 'sunny', 'soft', 'signature'],
      'Radiant lavender and orange blossom warmed by amber and vanilla.',
    ],
    [
      'mfk-a-la-rose',
      'A la rose',
      'floral-soft',
      ['floral', 'fresh', 'citrus'],
      ['rose', 'citrus', 'floral', 'musky'],
      ['bergamot', 'orange', 'damask rose', 'grasse rose', 'musk'],
      ['rose-garden', 'luminous', 'romantic', 'fresh', 'elegant'],
      'A luminous bouquet of two roses, bright citrus, and clean musk.',
      { genderStyle: 'feminine' },
    ],
    [
      'mfk-lhomme-a-la-rose',
      "L'Homme A la rose",
      'green-woody',
      ['floral', 'fresh', 'woody'],
      ['rose', 'green', 'citrus', 'woody'],
      ['grapefruit', 'rose', 'sage', 'cistus', 'amber woods'],
      ['green-rose', 'modern', 'tailored', 'fresh', 'confident'],
      'A modern green rose with grapefruit, sage, and amber woods.',
      { genderStyle: 'masculine' },
    ],
    [
      'mfk-amyris-femme',
      'Amyris femme',
      'floral-soft',
      ['floral', 'citrus', 'sweet'],
      ['floral', 'citrus', 'powdery', 'woody'],
      ['lemon blossom', 'orange', 'iris', 'amyris', 'vetiver'],
      ['effortless', 'silky', 'bright', 'feminine', 'elegant'],
      'Silky iris, lemon blossom, amyris, and vetiver with easy elegance.',
      { genderStyle: 'feminine' },
    ],
    [
      'mfk-amyris-homme',
      'Amyris homme',
      'woody-elegant',
      ['woody', 'citrus', 'spicy'],
      ['woody', 'aromatic', 'citrus', 'amber'],
      ['mandarin', 'rosemary', 'amyris', 'iris', 'tonka bean'],
      ['polished', 'relaxed', 'modern', 'warm', 'versatile'],
      'Mandarin, rosemary, amyris, iris, and tonka in polished balance.',
      { genderStyle: 'masculine' },
    ],
  ],
);

export const brandExpansion: FragranceSeed[] = [
  ...zoologist,
  ...maisonMargiela,
  ...maisonFrancisKurkdjian,
];
