import { withProfile, type ProfileName } from './fragrance-expansion';
import type {
  FragranceSeed,
  GenderStyle,
  Longevity,
  PriceRange,
  Projection,
  ScentFamily,
  Tier,
} from './fragrances';

type EntryOverrides = Partial<Pick<
  FragranceSeed,
  'genderStyle' | 'projection' | 'longevity'
>>;

type BrandEntry = [
  id: string,
  name: string,
  profile: ProfileName,
  scentFamilies: ScentFamily[],
  accords: string[],
  notes: string[],
  vibeTags: string[],
  shortDescription: string,
  overrides?: EntryOverrides,
];

type BrandDefaults = {
  brand: string;
  priceRange: PriceRange;
  priceDisplay: string;
  genderStyle: GenderStyle;
  projection: Projection;
  longevity: Longevity;
  tier: Tier;
};

function expandBrand(defaults: BrandDefaults, entries: BrandEntry[]): FragranceSeed[] {
  return entries.map(([
    id,
    name,
    profile,
    scentFamilies,
    accords,
    notes,
    vibeTags,
    shortDescription,
    overrides = {},
  ]) => withProfile({
    ...defaults,
    id,
    name,
    profile,
    scentFamilies,
    accords,
    notes,
    vibeTags,
    shortDescription,
    ...overrides,
  }));
}

const zoologist = expandBrand(
  {
    brand: 'Zoologist',
    priceRange: 'niche',
    priceDisplay: '$175-$210',
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
  },
  [
    [
      'zoologist-bee',
      'Bee',
      'sweet-gourmand',
      ['sweet', 'gourmand', 'floral'],
      ['honey', 'beeswax', 'vanilla', 'floral'],
      ['orange', 'royal jelly', 'honey', 'beeswax', 'vanilla'],
      ['honeyed', 'golden', 'dense', 'artistic', 'comforting'],
      'A lavish cloud of honey, wax, florals, and warm vanilla.',
    ],
    [
      'zoologist-squid',
      'Squid',
      'smoky-dark',
      ['aquatic', 'oriental', 'spicy'],
      ['marine', 'incense', 'inky', 'amber'],
      ['pink pepper', 'ink', 'incense', 'ambergris', 'benzoin'],
      ['deep-sea', 'inky', 'mysterious', 'salty', 'experimental'],
      'Dark oceanic ink, incense, and ambergris with cinematic depth.',
    ],
    [
      'zoologist-cow',
      'Cow',
      'green-woody',
      ['fresh', 'floral', 'clean'],
      ['green', 'lactonic', 'apple', 'floral'],
      ['sage', 'apple', 'milk', 'heliotrope', 'musk'],
      ['meadow', 'milky', 'gentle', 'green', 'comforting'],
      'Fresh meadow air, crisp apple, soft milk, and clean musk.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-harvest-mouse',
      'Harvest Mouse',
      'sweet-gourmand',
      ['sweet', 'woody', 'gourmand'],
      ['hay', 'vanilla', 'beer', 'woody'],
      ['bergamot', 'hay', 'beer', 'chamomile', 'vanilla'],
      ['cozy', 'countryside', 'warm', 'toasted', 'whimsical'],
      'Sunlit hay, chamomile, beer, and vanilla in a cozy field.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-rabbit',
      'Rabbit',
      'sweet-gourmand',
      ['gourmand', 'sweet', 'floral'],
      ['carrot cake', 'hay', 'vanilla', 'green'],
      ['cinnamon', 'apple', 'carrot', 'hay', 'vanilla'],
      ['playful', 'baked', 'soft', 'garden', 'comforting'],
      'A playful carrot-cake gourmand softened by hay and green leaves.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-penguin',
      'Penguin',
      'fresh-aquatic',
      ['fresh', 'aquatic', 'woody'],
      ['icy', 'marine', 'suede', 'musk'],
      ['antarctic air', 'ice', 'juniper', 'suede', 'musk'],
      ['frozen', 'mineral', 'clean', 'remote', 'modern'],
      'Icy air, juniper, suede, and musk with polar clarity.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-tyrannosaurus-rex',
      'Tyrannosaurus Rex',
      'smoky-dark',
      ['woody', 'spicy', 'oriental'],
      ['smoke', 'resinous', 'leather', 'floral'],
      ['black pepper', 'fir', 'incense', 'leather', 'cade'],
      ['extreme', 'volcanic', 'smoky', 'challenging', 'bold'],
      'An uncompromising eruption of smoke, resin, leather, and florals.',
    ],
    [
      'zoologist-moth',
      'Moth',
      'smoky-dark',
      ['spicy', 'floral', 'oriental'],
      ['powdery', 'smoky', 'honey', 'spicy'],
      ['clove', 'saffron', 'honey', 'heliotrope', 'smoke'],
      ['dusty', 'gothic', 'powdery', 'antique', 'mysterious'],
      'Dusty florals, honey, spice, and smoke in a gothic haze.',
    ],
    [
      'zoologist-seahorse',
      'Seahorse',
      'fresh-aquatic',
      ['aquatic', 'fresh', 'floral'],
      ['marine', 'aromatic', 'floral', 'salty'],
      ['cardamom', 'fennel', 'tuberose', 'seaweed', 'ambergris'],
      ['oceanic', 'transparent', 'unusual', 'bright', 'salty'],
      'A transparent marine floral with fennel, seaweed, and ambergris.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-snowy-owl',
      'Snowy Owl',
      'green-woody',
      ['fresh', 'clean', 'woody'],
      ['earthy', 'minty', 'powdery', 'musky'],
      ['snow accord', 'mint', 'coconut', 'orris', 'musk'],
      ['snowy', 'quiet', 'earthy', 'cool', 'textural'],
      'Cool snow, mint, earth, orris, and soft feather-like musk.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-camel',
      'Camel',
      'amber-spicy',
      ['oriental', 'spicy', 'woody'],
      ['dried fruit', 'amber', 'incense', 'animalic'],
      ['dates', 'dried fruit', 'incense', 'myrrh', 'oud'],
      ['desert', 'resinous', 'rich', 'spiced', 'nomadic'],
      'Dried fruit, incense, amber, and woods crossing a warm desert.',
    ],
    [
      'zoologist-panda',
      'Panda',
      'green-woody',
      ['fresh', 'woody', 'citrus'],
      ['green', 'apple', 'earthy', 'musky'],
      ['apple', 'magnolia', 'bamboo', 'tea', 'musk'],
      ['lush', 'bamboo', 'fruity', 'earthy', 'energetic'],
      'Juicy apple, bamboo, tea, flowers, and damp forest earth.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-hummingbird',
      'Hummingbird',
      'floral-bold',
      ['floral', 'sweet', 'gourmand'],
      ['floral', 'fruity', 'honey', 'powdery'],
      ['apple', 'cherry', 'honeysuckle', 'lilac', 'honey'],
      ['nectar', 'lush', 'romantic', 'colorful', 'opulent'],
      'A vivid nectar of fruit, lilac, honeysuckle, and honey.',
    ],
    [
      'zoologist-chameleon',
      'Chameleon',
      'citrus-beach',
      ['floral', 'sweet', 'aquatic'],
      ['tropical', 'floral', 'salty', 'creamy'],
      ['bergamot', 'mango', 'ylang-ylang', 'sea salt', 'vanilla'],
      ['tropical', 'colorful', 'beach', 'creamy', 'playful'],
      'Tropical fruit, creamy flowers, sea salt, and sun-warmed skin.',
      { projection: 'moderate' },
    ],
    [
      'zoologist-sacred-scarab',
      'Sacred Scarab',
      'amber-spicy',
      ['oriental', 'floral', 'woody'],
      ['incense', 'wine', 'resinous', 'animalic'],
      ['aldehydes', 'wine', 'lotus', 'incense', 'myrrh'],
      ['ancient', 'ceremonial', 'resinous', 'opulent', 'artistic'],
      'Wine, lotus, incense, and resins with ancient ceremonial richness.',
    ],
    [
      'zoologist-tiger',
      'Tiger',
      'green-woody',
      ['woody', 'spicy', 'citrus'],
      ['vetiver', 'citrus', 'spicy', 'smoky'],
      ['kumquat', 'cardamom', 'carrot seed', 'vetiver', 'incense'],
      ['focused', 'dry', 'powerful', 'wild', 'elegant'],
      'Dry vetiver, bright citrus, spice, and incense with controlled power.',
    ],
    [
      'zoologist-king-cobra',
      'King Cobra',
      'smoky-dark',
      ['woody', 'spicy', 'oriental'],
      ['cannabis', 'incense', 'green', 'leather'],
      ['camphor', 'cannabis', 'fig leaf', 'incense', 'leather'],
      ['dangerous', 'herbal', 'smoky', 'dark', 'experimental'],
      'Camphorous greens, incense, leather, and venomous herbal smoke.',
    ],
    [
      'zoologist-portuguese-man-o-war',
      "Portuguese Man O' War",
      'fresh-aquatic',
      ['aquatic', 'fresh', 'spicy'],
      ['marine', 'mineral', 'aromatic', 'salty'],
      ['lemon', 'lavender', 'sea salt', 'mineral amber', 'musk'],
      ['electric', 'oceanic', 'mineral', 'bright', 'unusual'],
      'Electric citrus, aromatic herbs, salt, and mineral ocean air.',
    ],
  ],
);

const maisonMargiela = expandBrand(
  {
    brand: 'Maison Margiela',
    priceRange: 'designer',
    priceDisplay: '$85-$180',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
  },
  [
    [
      'replica-whispers-in-the-library',
      'REPLICA Whispers in the Library',
      'woody-elegant',
      ['woody', 'sweet', 'spicy'],
      ['woody', 'vanilla', 'powdery', 'balsamic'],
      ['pepper', 'cedar', 'vanilla', 'benzoin'],
      ['library', 'paper', 'quiet', 'dark-academia', 'cozy'],
      'Polished wood, old paper, pepper, and vanilla in a quiet library.',
    ],
    [
      'replica-when-the-rain-stops',
      'REPLICA When the Rain Stops',
      'fresh-aquatic',
      ['fresh', 'aquatic', 'woody'],
      ['rain', 'aquatic', 'green', 'musky'],
      ['rain accord', 'pink pepper', 'rose', 'pine needle', 'moss'],
      ['rainy', 'clean', 'green', 'reflective', 'everyday'],
      'Rain-washed air, wet greenery, rose, and clean moss.',
    ],
    [
      'replica-autumn-vibes',
      'REPLICA Autumn Vibes',
      'green-woody',
      ['woody', 'spicy', 'fresh'],
      ['woody', 'earthy', 'spicy', 'mossy'],
      ['cardamom', 'pink pepper', 'maple', 'cedar', 'moss'],
      ['autumn', 'forest', 'crisp', 'earthy', 'cozy'],
      'Crisp leaves, cardamom, cedar, and moss on an autumn walk.',
    ],
    [
      'replica-matcha-meditation',
      'REPLICA Matcha Meditation',
      'green-woody',
      ['fresh', 'sweet', 'floral'],
      ['tea', 'green', 'white chocolate', 'floral'],
      ['green tea', 'matcha', 'orange blossom', 'jasmine', 'white chocolate'],
      ['tea', 'calm', 'creamy', 'mindful', 'soft'],
      'Green matcha, jasmine, orange blossom, and creamy white chocolate.',
    ],
    [
      'replica-bubble-bath',
      'REPLICA Bubble Bath',
      'fresh-clean',
      ['clean', 'floral', 'fresh'],
      ['soapy', 'coconut', 'musky', 'floral'],
      ['soap bubbles', 'lavender', 'rose', 'coconut', 'white musk'],
      ['soapy', 'spa', 'clean', 'comforting', 'minimal'],
      'A warm bath of clean soap, lavender, coconut, and white musk.',
      { projection: 'subtle' },
    ],
    [
      'replica-sailing-day',
      'REPLICA Sailing Day',
      'fresh-aquatic',
      ['aquatic', 'fresh', 'woody'],
      ['marine', 'aromatic', 'salty', 'woody'],
      ['aquatic accord', 'coriander', 'iris', 'seaweed', 'ambergris'],
      ['sailing', 'ocean', 'breezy', 'clean', 'summer'],
      'A brisk marine breeze with coriander, seaweed, and ambergris.',
    ],
    [
      'replica-springtime-in-a-park',
      'REPLICA Springtime in a Park',
      'floral-soft',
      ['floral', 'sweet', 'fresh'],
      ['floral', 'pear', 'green', 'musky'],
      ['pear', 'lily of the valley', 'rose', 'jasmine', 'musk'],
      ['spring', 'park', 'airy', 'romantic', 'daytime'],
      'Airy pear, lily of the valley, rose, and soft spring musk.',
      { projection: 'subtle' },
    ],
    [
      'replica-under-the-lemon-trees',
      'REPLICA Under the Lemon Trees',
      'citrus-beach',
      ['citrus', 'fresh', 'woody'],
      ['citrus', 'green', 'aromatic', 'woody'],
      ['lime', 'petitgrain', 'green tea', 'coriander', 'cedar'],
      ['lemon-grove', 'sunny', 'fresh', 'mediterranean', 'casual'],
      'Sunlit citrus leaves, green tea, herbs, and light woods.',
    ],
    [
      'replica-flower-market',
      'REPLICA Flower Market',
      'floral-soft',
      ['floral', 'fresh', 'clean'],
      ['floral', 'green', 'watery', 'fresh'],
      ['green leaves', 'freesia', 'jasmine', 'tuberose', 'rose'],
      ['bouquet', 'fresh-cut', 'spring', 'bright', 'romantic'],
      'A colorful market bouquet of fresh-cut stems and dewy petals.',
    ],
    [
      'replica-at-the-barbers',
      "REPLICA At the Barber's",
      'fresh-clean',
      ['fresh', 'clean', 'woody'],
      ['aromatic', 'lavender', 'soapy', 'woody'],
      ['basil', 'lavender', 'rosemary', 'tonka bean', 'moss'],
      ['barbershop', 'shaved', 'classic', 'clean', 'tailored'],
      'A classic clean shave of lavender, herbs, tonka, and moss.',
      { genderStyle: 'masculine' },
    ],
    [
      'replica-afternoon-delight',
      'REPLICA Afternoon Delight',
      'sweet-gourmand',
      ['gourmand', 'sweet', 'woody'],
      ['vanilla', 'biscuit', 'creamy', 'woody'],
      ['bitter almond', 'madeleine accord', 'sandalwood', 'vanilla', 'musk'],
      ['bakery', 'soft', 'comforting', 'vanilla', 'cozy'],
      'A tender madeleine, almond, vanilla, and sandalwood gourmand.',
    ],
    [
      'replica-up-at-dawn',
      'REPLICA Up at Dawn',
      'floral-soft',
      ['floral', 'fresh', 'clean'],
      ['floral', 'airy', 'musky', 'green'],
      ['pink pepper', 'rose', 'orange blossom', 'ambrette', 'musk'],
      ['dawn', 'light', 'hopeful', 'fresh', 'soft'],
      'A luminous dawn of rose, orange blossom, ambrette, and musk.',
    ],
    [
      'replica-chasing-sunsets',
      'REPLICA Chasing Sunsets',
      'citrus-beach',
      ['citrus', 'floral', 'fresh'],
      ['citrus', 'solar', 'floral', 'musky'],
      ['grapefruit', 'orange blossom', 'ylang-ylang', 'musk', 'amber'],
      ['sunset', 'vacation', 'warm', 'radiant', 'beach'],
      'Radiant citrus, solar florals, amber, and skin-warm musk.',
    ],
    [
      'replica-never-ending-summer',
      'REPLICA Never-ending Summer',
      'citrus-beach',
      ['citrus', 'fresh', 'woody'],
      ['citrus', 'aromatic', 'sparkling', 'woody'],
      ['orange', 'spritz accord', 'vetiver', 'ginger', 'cedar'],
      ['summer', 'aperitivo', 'sparkling', 'carefree', 'bright'],
      'A sparkling orange spritz with ginger, vetiver, and bright woods.',
    ],
    [
      'replica-on-a-date',
      'REPLICA On a Date',
      'floral-bold',
      ['floral', 'sweet', 'woody'],
      ['rose', 'fruity', 'woody', 'earthy'],
      ['blackcurrant', 'rose', 'geranium', 'patchouli', 'moss'],
      ['vineyard', 'date-night', 'romantic', 'wine', 'warm'],
      'Blackcurrant, rose, patchouli, and vineyard earth at sunset.',
    ],
    [
      'replica-from-the-garden',
      'REPLICA From the Garden',
      'green-woody',
      ['fresh', 'citrus', 'woody'],
      ['tomato leaf', 'green', 'earthy', 'citrus'],
      ['tomato leaf', 'green mandarin', 'geranium', 'patchouli', 'moss'],
      ['garden', 'tomato-leaf', 'earthy', 'fresh', 'natural'],
      'Crushed tomato leaves, citrus, geranium, and garden soil.',
    ],
    [
      'replica-soul-of-the-forest',
      'REPLICA Soul of the Forest',
      'green-woody',
      ['woody', 'fresh', 'spicy'],
      ['woody', 'resinous', 'green', 'aromatic'],
      ['blackcurrant', 'fir balsam', 'labdanum', 'cedar', 'moss'],
      ['enchanted-forest', 'resinous', 'deep', 'green', 'mysterious'],
      'A deep forest of fir balsam, cedar, moss, and dark fruit.',
      { longevity: 'long' },
    ],
    [
      'replica-celestial-whispers',
      'REPLICA Celestial Whispers',
      'skin-musk',
      ['floral', 'clean', 'sweet'],
      ['musky', 'powdery', 'floral', 'amber'],
      ['aldehydes', 'iris', 'jasmine', 'musk', 'amber'],
      ['ethereal', 'luminous', 'soft', 'dreamy', 'intimate'],
      'Ethereal aldehydes, iris, jasmine, musk, and luminous amber.',
      { longevity: 'long' },
    ],
    [
      'replica-flying',
      'REPLICA Flying',
      'fresh-aquatic',
      ['fresh', 'aquatic', 'citrus'],
      ['airy', 'citrus', 'aromatic', 'musky'],
      ['bergamot', 'orange blossom', 'neroli', 'almond', 'musk'],
      ['weightless', 'sky', 'bright', 'clean', 'uplifting'],
      'Weightless citrus, neroli, almond, and clean airborne musk.',
      { longevity: 'long' },
    ],
    [
      'replica-dancing-on-the-moon',
      'REPLICA Dancing on the Moon',
      'floral-bold',
      ['floral', 'clean', 'woody'],
      ['white floral', 'mineral', 'powdery', 'woody'],
      ['aldehydes', 'jasmine', 'frangipani', 'iris', 'cashmeran'],
      ['lunar', 'mineral', 'futuristic', 'white-floral', 'artistic'],
      'Lunar white florals, mineral dust, iris, and soft woods.',
      { longevity: 'long' },
    ],
    [
      'replica-ideal-one',
      'REPLICA Ideal One',
      'skin-musk',
      ['clean', 'woody', 'sweet'],
      ['skin musk', 'woody', 'amber', 'soft spicy'],
      ['pink pepper', 'orange blossom', 'ambroxan', 'musk', 'woods'],
      ['connection', 'intimate', 'modern', 'skin', 'magnetic'],
      'A magnetic skin scent of soft spice, ambroxan, musk, and woods.',
      { longevity: 'long' },
    ],
  ],
);

const maisonFrancisKurkdjian = expandBrand(
  {
    brand: 'Maison Francis Kurkdjian',
    priceRange: 'niche',
    priceDisplay: '$245-$395',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
  },
  [
    [
      'mfk-baccarat-rouge-540-extrait',
      'Baccarat Rouge 540 Extrait',
      'amber-spicy',
      ['oriental', 'sweet', 'woody'],
      ['amber', 'almond', 'woody', 'warm spicy'],
      ['bitter almond', 'saffron', 'jasmine', 'cedar', 'ambergris'],
      ['luxurious', 'radiant', 'intense', 'signature', 'evening'],
      'A richer almond, saffron, amber, and cedar interpretation of the icon.',
      { projection: 'strong' },
    ],
    [
      'mfk-724',
      '724',
      'fresh-clean',
      ['clean', 'fresh', 'floral'],
      ['aldehydic', 'musky', 'white floral', 'citrus'],
      ['bergamot', 'aldehydes', 'jasmine', 'sweet pea', 'white musk'],
      ['city', 'laundered', 'modern', 'bright', 'polished'],
      'Bright city air, aldehydes, white flowers, and immaculate musk.',
    ],
    [
      'mfk-aqua-universalis',
      'Aqua Universalis',
      'fresh-clean',
      ['citrus', 'clean', 'floral'],
      ['citrus', 'musky', 'white floral', 'fresh'],
      ['bergamot', 'lemon', 'lily of the valley', 'mock orange', 'musk'],
      ['crisp', 'linen', 'effortless', 'bright', 'everyday'],
      'Effortless citrus, white flowers, and clean linen-like musk.',
      { projection: 'subtle', longevity: 'moderate' },
    ],
    [
      'mfk-aqua-vitae',
      'Aqua Vitae',
      'citrus-beach',
      ['citrus', 'fresh', 'woody'],
      ['citrus', 'solar', 'spicy', 'woody'],
      ['lemon', 'mandarin', 'hedione', 'guaiac wood', 'tonka bean'],
      ['sunlit', 'warm-skin', 'bright', 'easy', 'refined'],
      'Sun-warmed citrus, airy florals, soft woods, and tonka.',
      { projection: 'subtle', longevity: 'moderate' },
    ],
    [
      'mfk-aqua-celestia-cologne-forte',
      'Aqua Celestia Cologne forte',
      'fresh-aquatic',
      ['fresh', 'citrus', 'clean'],
      ['citrus', 'green', 'musky', 'fruity'],
      ['bergamot', 'blackcurrant', 'mimosa', 'jasmine', 'musk'],
      ['sky-blue', 'airy', 'cool', 'optimistic', 'summer'],
      'A cool blue blend of bergamot, blackcurrant, mimosa, and musk.',
      { longevity: 'moderate' },
    ],
    [
      'mfk-aqua-media-cologne-forte',
      'Aqua Media Cologne forte',
      'green-woody',
      ['fresh', 'citrus', 'clean'],
      ['green', 'citrus', 'aromatic', 'musky'],
      ['bergamot', 'verbena', 'fennel', 'hedione', 'musk'],
      ['vivid-green', 'energizing', 'herbal', 'modern', 'fresh'],
      'Vivid bergamot, verbena, fennel, airy florals, and musk.',
      { longevity: 'moderate' },
    ],
    [
      'mfk-petit-matin',
      'Petit Matin',
      'fresh-clean',
      ['citrus', 'fresh', 'clean'],
      ['citrus', 'aromatic', 'musky', 'floral'],
      ['lemon', 'litsea cubeba', 'lavender', 'orange blossom', 'musk'],
      ['morning', 'sparkling', 'clean', 'optimistic', 'easy'],
      'A sparkling Paris morning of lemon, lavender, blossoms, and musk.',
      { longevity: 'moderate' },
    ],
    [
      'mfk-grand-soir',
      'Grand Soir',
      'amber-spicy',
      ['oriental', 'sweet', 'spicy'],
      ['amber', 'vanilla', 'balsamic', 'warm spicy'],
      ['labdanum', 'benzoin', 'amber', 'vanilla', 'tonka bean'],
      ['evening', 'golden', 'formal', 'warm', 'opulent'],
      'A grand golden amber of labdanum, benzoin, vanilla, and tonka.',
      { projection: 'strong' },
    ],
    [
      'mfk-gentle-fluidity-silver',
      'Gentle Fluidity Silver',
      'fresh-clean',
      ['fresh', 'woody', 'spicy'],
      ['aromatic', 'juniper', 'musky', 'woody'],
      ['juniper berries', 'coriander', 'nutmeg', 'amber woods', 'musk'],
      ['gin-tonic', 'crisp', 'tailored', 'cool', 'versatile'],
      'Crisp juniper, spice, amber woods, and musk with tailored freshness.',
    ],
    [
      'mfk-oud',
      'OUD',
      'woody-elegant',
      ['woody', 'spicy', 'oriental'],
      ['oud', 'saffron', 'woody', 'aromatic'],
      ['saffron', 'elemi', 'cedar', 'patchouli', 'oud'],
      ['precise', 'dry', 'luxurious', 'structured', 'evening'],
      'A precise composition of saffron, cedar, patchouli, and refined oud.',
    ],
    [
      'mfk-oud-satin-mood',
      'Oud Satin Mood',
      'floral-bold',
      ['oriental', 'floral', 'sweet'],
      ['rose', 'oud', 'vanilla', 'powdery'],
      ['violet', 'rose', 'oud', 'benzoin', 'vanilla'],
      ['satin', 'opulent', 'romantic', 'powerful', 'evening'],
      'Plush rose, violet, oud, benzoin, and vanilla with satin richness.',
      { projection: 'strong' },
    ],
    [
      'mfk-oud-satin-mood-extrait',
      'Oud Satin Mood Extrait',
      'floral-bold',
      ['oriental', 'floral', 'sweet'],
      ['rose', 'oud', 'cinnamon', 'vanilla'],
      ['cinnamon', 'rose', 'oud', 'benzoin', 'vanilla'],
      ['intense', 'velvety', 'rose', 'luxurious', 'statement'],
      'An intensified velvet rose, cinnamon, oud, benzoin, and vanilla.',
      { projection: 'strong' },
    ],
    [
      'mfk-oud-silk-mood',
      'Oud Silk Mood',
      'woody-elegant',
      ['woody', 'floral', 'fresh'],
      ['rose', 'oud', 'aromatic', 'woody'],
      ['bergamot', 'blue chamomile', 'rose', 'papyrus', 'oud'],
      ['silky', 'airy', 'refined', 'rose', 'architectural'],
      'Airy rose, blue chamomile, papyrus, and oud with silk-like texture.',
    ],
    [
      'mfk-apom',
      'APOM',
      'floral-soft',
      ['floral', 'woody', 'sweet'],
      ['orange blossom', 'lavender', 'amber', 'vanilla'],
      ['lavender', 'orange blossom', 'ylang-ylang', 'amber', 'vanilla'],
      ['radiant', 'intimate', 'sunny', 'soft', 'signature'],
      'Radiant lavender and orange blossom warmed by amber and vanilla.',
    ],
    [
      'mfk-a-la-rose',
      'A la rose',
      'floral-soft',
      ['floral', 'fresh', 'citrus'],
      ['rose', 'citrus', 'floral', 'musky'],
      ['bergamot', 'orange', 'damask rose', 'grasse rose', 'musk'],
      ['rose-garden', 'luminous', 'romantic', 'fresh', 'elegant'],
      'A luminous bouquet of two roses, bright citrus, and clean musk.',
      { genderStyle: 'feminine' },
    ],
    [
      'mfk-lhomme-a-la-rose',
      "L'Homme A la rose",
      'green-woody',
      ['floral', 'fresh', 'woody'],
      ['rose', 'green', 'citrus', 'woody'],
      ['grapefruit', 'rose', 'sage', 'cistus', 'amber woods'],
      ['green-rose', 'modern', 'tailored', 'fresh', 'confident'],
      'A modern green rose with grapefruit, sage, and amber woods.',
      { genderStyle: 'masculine' },
    ],
    [
      'mfk-amyris-femme',
      'Amyris femme',
      'floral-soft',
      ['floral', 'citrus', 'sweet'],
      ['floral', 'citrus', 'powdery', 'woody'],
      ['lemon blossom', 'orange', 'iris', 'amyris', 'vetiver'],
      ['effortless', 'silky', 'bright', 'feminine', 'elegant'],
      'Silky iris, lemon blossom, amyris, and vetiver with easy elegance.',
      { genderStyle: 'feminine' },
    ],
    [
      'mfk-amyris-homme',
      'Amyris homme',
      'woody-elegant',
      ['woody', 'citrus', 'spicy'],
      ['woody', 'aromatic', 'citrus', 'amber'],
      ['mandarin', 'rosemary', 'amyris', 'iris', 'tonka bean'],
      ['polished', 'relaxed', 'modern', 'warm', 'versatile'],
      'Mandarin, rosemary, amyris, iris, and tonka in polished balance.',
      { genderStyle: 'masculine' },
    ],
  ],
);

const tomFordPrivateBlend = expandBrand(
  {
    brand: 'Tom Ford',
    priceRange: 'niche',
    priceDisplay: '$280-$450',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
  },
  [
    [
      'tf-tuscan-leather',
      'Tuscan Leather',
      'smoky-dark',
      ['woody', 'spicy', 'oriental'],
      ['leather', 'suede', 'raspberry', 'smoky'],
      ['raspberry', 'saffron', 'leather', 'jasmine', 'amber'],
      ['leathery', 'raw', 'suede', 'confident', 'statement'],
      'A bold raspberry-tinged suede and leather with smoky depth.',
      { projection: 'strong' },
    ],
    [
      'tf-soleil-blanc',
      'Soleil Blanc',
      'citrus-beach',
      ['floral', 'oriental', 'sweet'],
      ['solar', 'coconut', 'floral', 'amber'],
      ['bergamot', 'cardamom', 'tuberose', 'ylang-ylang', 'coconut'],
      ['tropical', 'suntan', 'beach', 'radiant', 'vacation'],
      'A sun-drenched tropical floral with coconut, tuberose, and amber.',
    ],
    [
      'tf-costa-azzurra',
      'Costa Azzurra',
      'fresh-aquatic',
      ['woody', 'aquatic', 'fresh'],
      ['driftwood', 'marine', 'herbal', 'woody'],
      ['seaweed', 'juniper', 'vetiver', 'oakmoss', 'driftwood'],
      ['mediterranean', 'coastal', 'green', 'salty', 'escape'],
      'Mediterranean driftwood, sea air, and aromatic coastal greens.',
    ],
    [
      'tf-fucking-fabulous',
      'Fabulous',
      'amber-spicy',
      ['woody', 'oriental', 'spicy'],
      ['leather', 'almond', 'amber', 'vanilla'],
      ['lavender', 'bitter almond', 'leather', 'tonka bean', 'vanilla'],
      ['leathery', 'bold', 'almond', 'statement', 'luxurious'],
      'Creamy almond, leather, and warm woods in an unapologetic blend.',
      { projection: 'strong' },
    ],
    [
      'tf-bitter-peach',
      'Bitter Peach',
      'sweet-gourmand',
      ['sweet', 'gourmand', 'oriental'],
      ['peach', 'liqueur', 'vanilla', 'amber'],
      ['peach', 'blood orange', 'rum', 'cardamom', 'vanilla'],
      ['juicy', 'boozy', 'decadent', 'warm', 'addictive'],
      'A decadent boozy peach with rum, cardamom, and creamy vanilla.',
      { projection: 'strong' },
    ],
    [
      'tf-rose-prick',
      'Rose Prick',
      'floral-bold',
      ['floral', 'woody', 'spicy'],
      ['rose', 'thorny', 'spicy', 'earthy'],
      ['rose', 'turmeric', 'sichuan pepper', 'patchouli', 'tonka bean'],
      ['rose-garden', 'spicy', 'thorny', 'lush', 'unisex'],
      'A thorny, spiced rose garden with pepper, patchouli, and tonka.',
    ],
    [
      'tf-tobacco-oud',
      'Tobacco Oud',
      'smoky-dark',
      ['woody', 'spicy', 'oriental'],
      ['tobacco', 'oud', 'spicy', 'smoky'],
      ['tobacco', 'oud', 'cinnamon', 'incense', 'sandalwood'],
      ['smoky', 'oriental', 'dense', 'wintry', 'opulent'],
      'Smoky tobacco and oud wrapped in spice and warm incense.',
      { projection: 'strong' },
    ],
    [
      'tf-cafe-rose',
      'Café Rose',
      'floral-bold',
      ['floral', 'gourmand', 'oriental'],
      ['rose', 'coffee', 'spicy', 'amber'],
      ['coffee', 'rose', 'black pepper', 'patchouli', 'amber'],
      ['rose-coffee', 'rich', 'sultry', 'warm', 'opulent'],
      'A rich rose steeped in coffee, pepper, and golden amber.',
    ],
    [
      'tf-beau-de-jour',
      'Beau de Jour',
      'green-woody',
      ['fresh', 'woody', 'spicy'],
      ['aromatic', 'lavender', 'herbal', 'woody'],
      ['lavender', 'rosemary', 'geranium', 'oakmoss', 'amber'],
      ['barbershop', 'aromatic', 'clean', 'classic', 'tailored'],
      'A polished aromatic fougère of lavender, herbs, and mossy woods.',
      { genderStyle: 'masculine' },
    ],
    [
      'tf-vanille-fatale',
      'Vanille Fatale',
      'amber-spicy',
      ['sweet', 'oriental', 'woody'],
      ['vanilla', 'smoky', 'spicy', 'amber'],
      ['vanilla', 'incense', 'black pepper', 'sandalwood', 'amber'],
      ['smoky-vanilla', 'dark', 'warm', 'opulent', 'evening'],
      'A smoky, spiced vanilla with incense and warm sandalwood.',
      { projection: 'strong' },
    ],
    [
      'tf-jasmin-rouge',
      'Jasmin Rouge',
      'floral-bold',
      ['floral', 'spicy', 'oriental'],
      ['jasmine', 'spicy', 'amber', 'woody'],
      ['bergamot', 'jasmine', 'clary sage', 'cinnamon', 'amber'],
      ['spiced-jasmine', 'sultry', 'bold', 'warm', 'evening'],
      'A spiced, sultry jasmine with cinnamon, sage, and amber.',
      { genderStyle: 'feminine', projection: 'strong' },
    ],
  ],
);

const tomFordSignature = expandBrand(
  {
    brand: 'Tom Ford',
    priceRange: 'designer',
    priceDisplay: '$130-$175',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
  },
  [
    [
      'tf-noir-extreme',
      'Noir Extreme',
      'amber-spicy',
      ['oriental', 'sweet', 'spicy'],
      ['amber', 'spicy', 'gourmand', 'woody'],
      ['cardamom', 'nutmeg', 'kulfi', 'amber', 'sandalwood'],
      ['warm', 'spiced', 'creamy', 'crowd-pleaser', 'evening'],
      'Warm spiced amber with creamy kulfi, nutmeg, and woods.',
      { genderStyle: 'masculine' },
    ],
    [
      'tf-ombre-leather',
      'Ombré Leather',
      'smoky-dark',
      ['woody', 'spicy', 'floral'],
      ['leather', 'suede', 'floral', 'amber'],
      ['cardamom', 'leather', 'jasmine', 'patchouli', 'amber'],
      ['leather', 'rugged', 'suede', 'bold', 'unisex'],
      'Supple suede and leather softened by florals and warm amber.',
      { projection: 'strong' },
    ],
    [
      'tf-grey-vetiver',
      'Grey Vetiver',
      'woody-elegant',
      ['woody', 'citrus', 'spicy'],
      ['vetiver', 'citrus', 'spicy', 'woody'],
      ['grapefruit', 'sage', 'vetiver', 'orris', 'amber woods'],
      ['tailored', 'crisp', 'professional', 'clean', 'refined'],
      'A crisp, tailored vetiver with citrus, sage, and dry woods.',
      { genderStyle: 'masculine' },
    ],
    [
      'tf-noir',
      'Noir',
      'amber-spicy',
      ['oriental', 'spicy', 'woody'],
      ['amber', 'spicy', 'vanilla', 'woody'],
      ['bergamot', 'pink pepper', 'iris', 'vanilla', 'amber'],
      ['evening', 'warm', 'refined', 'sensual', 'classic'],
      'A refined oriental of pepper, iris, vanilla, and warm amber.',
      { genderStyle: 'masculine' },
    ],
    [
      'tf-velvet-orchid',
      'Velvet Orchid',
      'floral-bold',
      ['floral', 'sweet', 'oriental'],
      ['floral', 'honey', 'spicy', 'amber'],
      ['bergamot', 'honey', 'orchid', 'jasmine', 'vanilla'],
      ['plush', 'honeyed', 'sultry', 'opulent', 'evening'],
      'A plush, honeyed orchid floral with spice and warm vanilla.',
      { genderStyle: 'feminine', projection: 'strong' },
    ],
  ],
);

const initioParfums = expandBrand(
  {
    brand: 'Initio Parfums Privés',
    priceRange: 'niche',
    priceDisplay: '$250-$320',
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
  },
  [
    [
      'initio-oud-for-greatness',
      'Oud for Greatness',
      'smoky-dark',
      ['woody', 'spicy', 'oriental'],
      ['oud', 'saffron', 'smoky', 'woody'],
      ['saffron', 'nutmeg', 'oud', 'patchouli', 'musk'],
      ['powerhouse', 'smoky', 'oud', 'bold', 'signature'],
      'A towering saffron-and-oud powerhouse with smoky depth.',
    ],
    [
      'initio-rehab',
      'Rehab',
      'skin-musk',
      ['sweet', 'oriental', 'woody'],
      ['vanilla', 'musk', 'amber', 'spicy'],
      ['ginger', 'sambac jasmine', 'vanilla', 'benzoin', 'musk'],
      ['addictive', 'skin', 'warm', 'intimate', 'magnetic'],
      'An addictive skin scent of ginger, jasmine, vanilla, and musk.',
      { projection: 'moderate' },
    ],
    [
      'initio-atomic-rose',
      'Atomic Rose',
      'floral-bold',
      ['floral', 'sweet', 'woody'],
      ['rose', 'fruity', 'musky', 'woody'],
      ['raspberry', 'rose', 'cashmeran', 'musk', 'woods'],
      ['rosy', 'fruity', 'radiant', 'modern', 'flirty'],
      'A radiant fruity rose with raspberry, cashmere woods, and musk.',
    ],
    [
      'initio-psychedelic-love',
      'Psychedelic Love',
      'floral-bold',
      ['floral', 'sweet', 'woody'],
      ['rose', 'fruity', 'patchouli', 'vanilla'],
      ['raspberry', 'rose', 'vetiver', 'patchouli', 'vanilla'],
      ['hypnotic', 'fruity', 'warm', 'sensual', 'date'],
      'A hypnotic rose-raspberry warmed by patchouli and vanilla.',
    ],
    [
      'initio-paragon',
      'Paragon',
      'green-woody',
      ['woody', 'spicy', 'fresh'],
      ['woody', 'herbal', 'spicy', 'musky'],
      ['cardamom', 'nutmeg', 'bourbon vetiver', 'vanilla', 'musk'],
      ['refined', 'spicy', 'green', 'modern', 'versatile'],
      'Spiced vetiver and woods with a refined, contemporary edge.',
    ],
    [
      'initio-blessed-baraka',
      'Blessed Baraka',
      'sweet-gourmand',
      ['sweet', 'gourmand', 'oriental'],
      ['almond', 'vanilla', 'caramel', 'spicy'],
      ['almond', 'cinnamon', 'caramel', 'vanilla', 'tonka bean'],
      ['gourmand', 'sweet', 'cozy', 'warm', 'addictive'],
      'A cozy gourmand of almond, caramel, cinnamon, and vanilla.',
      { projection: 'moderate' },
    ],
    [
      'initio-magnetic-blend-1',
      'Magnetic Blend 1',
      'amber-spicy',
      ['oriental', 'spicy', 'woody'],
      ['amber', 'spicy', 'tobacco', 'woody'],
      ['cinnamon', 'tobacco', 'amber', 'sandalwood', 'musk'],
      ['warm', 'spiced', 'magnetic', 'evening', 'bold'],
      'A warm spiced amber with tobacco, cinnamon, and sandalwood.',
    ],
    [
      'initio-magnetic-blend-7',
      'Magnetic Blend 7',
      'skin-musk',
      ['sweet', 'oriental', 'woody'],
      ['amber', 'vanilla', 'musk', 'woody'],
      ['amber', 'sandalwood', 'tonka bean', 'vanilla', 'musk'],
      ['cozy', 'skin', 'warm', 'soft', 'intimate'],
      'A soft amber-vanilla musk that wraps the skin in warmth.',
      { projection: 'moderate' },
    ],
    [
      'initio-divine-attraction',
      'Divine Attraction',
      'amber-spicy',
      ['woody', 'spicy', 'oriental'],
      ['leather', 'spicy', 'amber', 'smoky'],
      ['cinnamon', 'leather', 'saffron', 'incense', 'amber'],
      ['leathery', 'spiced', 'bold', 'evening', 'magnetic'],
      'A spiced leather and incense blend with smoldering amber.',
    ],
  ],
);

const louisVuitton = expandBrand(
  {
    brand: 'Louis Vuitton',
    priceRange: 'niche',
    priceDisplay: '$280-$400',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
  },
  [
    [
      'lv-ombre-nomade',
      'Ombre Nomade',
      'smoky-dark',
      ['woody', 'oriental', 'spicy'],
      ['oud', 'incense', 'raspberry', 'amber'],
      ['oud', 'raspberry', 'incense', 'benzoin', 'amber'],
      ['oud', 'smoky', 'dense', 'desert', 'statement'],
      'A smoky oud-and-incense epic with a raspberry-amber glow.',
      { projection: 'strong' },
    ],
    [
      'lv-attrape-reves',
      'Attrape-Rêves',
      'floral-bold',
      ['floral', 'sweet', 'oriental'],
      ['peach', 'floral', 'cocoa', 'amber'],
      ['peach', 'ginger', 'peony', 'cocoa', 'sandalwood'],
      ['dreamy', 'fruity', 'sultry', 'radiant', 'feminine'],
      'A dreamy peach-and-peony floral with cocoa and warm woods.',
      { genderStyle: 'feminine' },
    ],
    [
      'lv-imagination',
      'Imagination',
      'citrus-beach',
      ['citrus', 'woody', 'fresh'],
      ['citrus', 'tea', 'aromatic', 'woody'],
      ['bergamot', 'black tea', 'ginger', 'ambrox', 'woods'],
      ['bright', 'tea', 'sparkling', 'modern', 'versatile'],
      'Sparkling citrus and black tea over clean, modern woods.',
      { genderStyle: 'masculine' },
    ],
    [
      'lv-afternoon-swim',
      'Afternoon Swim',
      'citrus-beach',
      ['citrus', 'fresh', 'aquatic'],
      ['citrus', 'solar', 'aquatic', 'sweet'],
      ['orange', 'mandarin', 'bergamot', 'ginger', 'aquatic'],
      ['summer', 'bright', 'solar', 'energetic', 'vacation'],
      'A bright solar splash of orange, mandarin, and aquatic freshness.',
    ],
    [
      'lv-apogee',
      'Apogée',
      'floral-soft',
      ['floral', 'fresh', 'clean'],
      ['floral', 'green', 'woody', 'dewy'],
      ['lily of the valley', 'magnolia', 'sap', 'jasmine', 'sandalwood'],
      ['green-floral', 'dewy', 'fresh', 'elegant', 'spring'],
      'A dewy green floral of lily of the valley, magnolia, and sap.',
      { genderStyle: 'feminine' },
    ],
    [
      'lv-contre-moi',
      'Contre Moi',
      'sweet-gourmand',
      ['sweet', 'floral', 'gourmand'],
      ['vanilla', 'floral', 'creamy', 'sweet'],
      ['vanilla', 'magnolia', 'cocoa', 'tonka bean', 'musk'],
      ['creamy', 'vanilla', 'soft', 'romantic', 'cozy'],
      'A creamy vanilla and magnolia with cocoa and soft tonka.',
      { genderStyle: 'feminine' },
    ],
    [
      'lv-matiere-noire',
      'Matière Noire',
      'smoky-dark',
      ['woody', 'oriental', 'floral'],
      ['oud', 'blackberry', 'woody', 'smoky'],
      ['blackberry', 'narcissus', 'oud', 'agarwood', 'patchouli'],
      ['dark', 'mysterious', 'woody', 'opulent', 'evening'],
      'A dark, mysterious oud-and-blackberry weave of deep woods.',
    ],
    [
      'lv-symphony',
      'Symphony',
      'woody-elegant',
      ['woody', 'citrus', 'fresh'],
      ['citrus', 'tea', 'woody', 'amber'],
      ['bergamot', 'jasmine tea', 'ambrox', 'cedar', 'amber'],
      ['refined', 'luminous', 'tea', 'elegant', 'versatile'],
      'A luminous citrus-tea woody with refined amber clarity.',
    ],
    [
      'lv-spell-on-you',
      'Spell on You',
      'floral-bold',
      ['floral', 'sweet', 'woody'],
      ['floral', 'iris', 'fruity', 'musky'],
      ['orange blossom', 'iris', 'grenadine', 'jasmine', 'musk'],
      ['flirty', 'radiant', 'romantic', 'feminine', 'date'],
      'A flirty floral of orange blossom, iris, and sweet grenadine.',
      { genderStyle: 'feminine' },
    ],
    [
      'lv-california-dream',
      'California Dream',
      'citrus-beach',
      ['citrus', 'sweet', 'woody'],
      ['mandarin', 'amber', 'solar', 'woody'],
      ['bitter orange', 'mandarin', 'ambrette', 'amberwood', 'benzoin'],
      ['golden', 'sunny', 'smooth', 'radiant', 'easy'],
      'A golden-hour mandarin and amber with smooth, sunny warmth.',
    ],
    [
      'lv-pacific-chill',
      'Pacific Chill',
      'fresh-aquatic',
      ['citrus', 'fresh', 'aquatic'],
      ['citrus', 'minty', 'green', 'watery'],
      ['lime', 'mint', 'blackcurrant', 'aloe', 'basil'],
      ['cooling', 'crisp', 'watery', 'refreshing', 'summer'],
      'A cooling rush of lime, mint, blackcurrant, and crisp aloe.',
    ],
    [
      'lv-meteore',
      'Météore',
      'fresh-clean',
      ['citrus', 'fresh', 'woody'],
      ['citrus', 'aromatic', 'spicy', 'woody'],
      ['bergamot', 'mandarin', 'neroli', 'juniper', 'sandalwood'],
      ['radiant', 'crisp', 'bright', 'modern', 'versatile'],
      'A radiant citrus-aromatic with neroli, juniper, and soft woods.',
      { genderStyle: 'masculine' },
    ],
  ],
);

const goldfieldBanks = expandBrand(
  {
    brand: 'Goldfield & Banks',
    priceRange: 'niche',
    priceDisplay: '$200-$300',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
  },
  [
    [
      'gfb-pacific-rock-moss',
      'Pacific Rock Moss',
      'fresh-aquatic',
      ['fresh', 'aquatic', 'citrus'],
      ['marine', 'citrus', 'mossy', 'mineral'],
      ['lemon', 'sage', 'seaweed', 'coastal moss', 'vetiver'],
      ['coastal', 'salty', 'mineral', 'fresh', 'summer'],
      'Salty coastal air, citrus, and sea moss along a rocky shore.',
    ],
    [
      'gfb-blue-cypress',
      'Blue Cypress',
      'green-woody',
      ['woody', 'fresh', 'spicy'],
      ['woody', 'smoky', 'aromatic', 'earthy'],
      ['cypress', 'pepper', 'blue cypress oil', 'sandalwood', 'musk'],
      ['australian', 'woody', 'smoky', 'earthy', 'outdoors'],
      'Smoky Australian blue cypress with pepper and dry sandalwood.',
    ],
    [
      'gfb-bohemian-lime',
      'Bohemian Lime',
      'citrus-beach',
      ['citrus', 'fresh', 'woody'],
      ['lime', 'green', 'aromatic', 'woody'],
      ['lime', 'basil', 'vetiver', 'cedar', 'musk'],
      ['zesty', 'vibrant', 'green', 'summery', 'easy'],
      'A vibrant lime and basil over clean cedar and vetiver.',
    ],
    [
      'gfb-purple-suede',
      'Purple Suede',
      'floral-bold',
      ['floral', 'woody', 'sweet'],
      ['suede', 'floral', 'fruity', 'woody'],
      ['raspberry', 'violet', 'jasmine', 'suede', 'sandalwood'],
      ['plush', 'suede', 'fruity-floral', 'soft', 'elegant'],
      'Plush suede with raspberry, violet, and creamy sandalwood.',
    ],
    [
      'gfb-sunset-hour',
      'Sunset Hour',
      'citrus-beach',
      ['citrus', 'sweet', 'woody'],
      ['citrus', 'solar', 'tropical', 'woody'],
      ['bergamot', 'fig', 'coconut', 'ylang-ylang', 'sandalwood'],
      ['golden', 'tropical', 'sunset', 'warm', 'vacation'],
      'A golden tropical glow of fig, coconut, and sun-warmed woods.',
    ],
    [
      'gfb-velvet-splendour',
      'Velvet Splendour',
      'floral-bold',
      ['floral', 'oriental', 'sweet'],
      ['tuberose', 'floral', 'amber', 'spicy'],
      ['tuberose', 'frangipani', 'saffron', 'amber', 'vanilla'],
      ['opulent', 'white-floral', 'lush', 'evening', 'radiant'],
      'An opulent tuberose and frangipani wrapped in saffron amber.',
      { projection: 'strong' },
    ],
    [
      'gfb-southern-bloom',
      'Southern Bloom',
      'floral-soft',
      ['floral', 'fresh', 'clean'],
      ['floral', 'green', 'dewy', 'woody'],
      ['boronia', 'wattle', 'jasmine', 'green leaves', 'sandalwood'],
      ['native', 'dewy', 'green-floral', 'bright', 'spring'],
      'Australian native blooms, dewy greens, and soft sandalwood.',
      { genderStyle: 'feminine' },
    ],
    [
      'gfb-desert-rosewood',
      'Desert Rosewood',
      'amber-spicy',
      ['woody', 'oriental', 'spicy'],
      ['rosewood', 'amber', 'spicy', 'balsamic'],
      ['saffron', 'rosewood', 'amber', 'labdanum', 'vanilla'],
      ['warm', 'desert', 'resinous', 'spiced', 'evening'],
      'Warm desert rosewood with saffron, amber, and balsamic vanilla.',
    ],
    [
      'gfb-white-sandalwood',
      'White Sandalwood',
      'woody-elegant',
      ['woody', 'clean', 'sweet'],
      ['sandalwood', 'creamy', 'milky', 'soft'],
      ['bergamot', 'iris', 'sandalwood', 'tonka bean', 'musk'],
      ['creamy', 'smooth', 'minimal', 'refined', 'versatile'],
      'Creamy white sandalwood, iris, and soft tonka with quiet polish.',
      { projection: 'subtle' },
    ],
    [
      'gfb-ingenious-ginger',
      'Ingenious Ginger',
      'green-woody',
      ['spicy', 'fresh', 'woody'],
      ['ginger', 'spicy', 'citrus', 'woody'],
      ['ginger', 'pink pepper', 'nutmeg', 'cedar', 'musk'],
      ['zingy', 'spicy', 'warm', 'energetic', 'versatile'],
      'A zingy ginger and pepper spice over warm cedar and musk.',
    ],
    [
      'gfb-night-storm',
      'Night Storm',
      'smoky-dark',
      ['woody', 'spicy', 'oriental'],
      ['leather', 'smoky', 'spicy', 'woody'],
      ['black pepper', 'leather', 'oud', 'incense', 'vetiver'],
      ['stormy', 'smoky', 'leather', 'bold', 'evening'],
      'A stormy blend of pepper, leather, oud, and dark incense.',
      { projection: 'strong' },
    ],
  ],
);

const maisonMargielaExtra = expandBrand(
  {
    brand: 'Maison Margiela',
    priceRange: 'designer',
    priceDisplay: '$85-$180',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
  },
  [
    [
      'replica-tea-escape',
      'REPLICA Tea Escape',
      'green-woody',
      ['fresh', 'woody', 'sweet'],
      ['tea', 'woody', 'honey', 'aromatic'],
      ['bergamot', 'mate absolute', 'tea', 'immortelle', 'cedar'],
      ['tea-house', 'cozy', 'aromatic', 'calm', 'everyday'],
      'A warm cup of black tea, honeyed herbs, and soft cedar.',
    ],
    [
      'replica-lipstick-on',
      'REPLICA Lipstick On',
      'floral-bold',
      ['floral', 'sweet', 'oriental'],
      ['violet', 'powdery', 'iris', 'amber'],
      ['violet', 'iris', 'rose', 'vanilla', 'amber'],
      ['retro', 'powdery', 'glamorous', 'vintage', 'feminine'],
      'A vintage-glam violet-iris powder with creamy vanilla amber.',
      { genderStyle: 'feminine' },
    ],
    [
      'replica-music-festival',
      'REPLICA Music Festival',
      'fruity-playful',
      ['fresh', 'sweet', 'citrus'],
      ['green', 'fizzy', 'fruity', 'aromatic'],
      ['lemon', 'mint', 'tobacco leaf', 'beer accord', 'musk'],
      ['festival', 'green', 'youthful', 'carefree', 'crowd'],
      'Green herbal haze, citrus fizz, and a carefree festival buzz.',
    ],
  ],
);

const parfumsDeMarly = expandBrand(
  {
    brand: 'Parfums de Marly',
    priceRange: 'niche',
    priceDisplay: '$210-$355',
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
  },
  [
    [
      'pdm-pegasus',
      'Pegasus',
      'sweet-gourmand',
      ['sweet', 'gourmand', 'woody'],
      ['almond', 'vanilla', 'heliotrope', 'woody'],
      ['bergamot', 'bitter almond', 'heliotrope', 'vanilla', 'sandalwood'],
      ['almond', 'creamy', 'signature', 'crowd-pleaser', 'versatile'],
      'Creamy almond and heliotrope over vanilla and soft sandalwood.',
      { genderStyle: 'masculine' },
    ],
    [
      'pdm-carlisle',
      'Carlisle',
      'amber-spicy',
      ['oriental', 'spicy', 'woody'],
      ['apple', 'spicy', 'amber', 'woody'],
      ['apple', 'nutmeg', 'rose', 'patchouli', 'vanilla'],
      ['opulent', 'spiced', 'rich', 'statement', 'evening'],
      'A rich spiced fruit-and-amber blend with rose and vanilla.',
    ],
    [
      'pdm-percival',
      'Percival',
      'fresh-clean',
      ['fresh', 'aquatic', 'woody'],
      ['aromatic', 'marine', 'green', 'woody'],
      ['bergamot', 'lavender', 'violet leaf', 'cedar', 'musk'],
      ['fresh', 'aromatic', 'clean', 'daytime', 'versatile'],
      'A fresh aromatic of bergamot, lavender, violet leaf, and cedar.',
      { genderStyle: 'masculine' },
    ],
    [
      'pdm-sedley',
      'Sedley',
      'fresh-aquatic',
      ['fresh', 'aquatic', 'citrus'],
      ['aromatic', 'marine', 'minty', 'woody'],
      ['watermint', 'bergamot', 'lavender', 'geranium', 'musk'],
      ['breezy', 'clean', 'aquatic', 'versatile', 'daytime'],
      'A breezy aquatic with watermint, lavender, and clean musk.',
    ],
    [
      'pdm-galloway',
      'Galloway',
      'fresh-clean',
      ['fresh', 'citrus', 'woody'],
      ['citrus', 'aromatic', 'woody', 'musky'],
      ['bergamot', 'jasmine', 'sandalwood', 'vetiver', 'musk'],
      ['refined', 'clean', 'versatile', 'elegant', 'daytime'],
      'A refined citrus-woody with jasmine, sandalwood, and musk.',
    ],
    [
      'pdm-kalan',
      'Kalan',
      'amber-spicy',
      ['spicy', 'woody', 'oriental'],
      ['citrus', 'spicy', 'amber', 'leather'],
      ['lime', 'cinnamon', 'vetiver', 'tonka bean', 'amber'],
      ['spicy', 'warm', 'distinctive', 'evening', 'bold'],
      'A spicy citrus opening over vetiver, tonka, and warm amber.',
      { genderStyle: 'masculine' },
    ],
    [
      'pdm-haltane',
      'Haltane',
      'amber-spicy',
      ['woody', 'spicy', 'oriental'],
      ['saffron', 'woody', 'amber', 'spicy'],
      ['saffron', 'rum', 'cedar', 'patchouli', 'amber'],
      ['opulent', 'boozy', 'spiced', 'statement', 'evening'],
      'Saffron and rum over cedar, patchouli, and opulent amber.',
      { genderStyle: 'masculine' },
    ],
    [
      'pdm-delina-exclusif',
      'Delina Exclusif',
      'floral-bold',
      ['floral', 'sweet', 'woody'],
      ['rose', 'lychee', 'powdery', 'vanilla'],
      ['lychee', 'rose', 'vanilla', 'incense', 'musk'],
      ['romantic', 'rosy', 'radiant', 'feminine', 'statement'],
      'An intensified lychee-rose with vanilla, incense, and musk.',
      { genderStyle: 'feminine' },
    ],
    [
      'pdm-oajan',
      'Oajan',
      'amber-spicy',
      ['oriental', 'sweet', 'woody'],
      ['oud', 'amber', 'tobacco', 'vanilla'],
      ['rum', 'tobacco', 'oud', 'amber', 'vanilla'],
      ['warm', 'boozy', 'oud', 'opulent', 'evening'],
      'Boozy tobacco and oud melting into amber and vanilla.',
    ],
    [
      'pdm-meliora',
      'Meliora',
      'floral-soft',
      ['floral', 'sweet', 'clean'],
      ['floral', 'powdery', 'musky', 'fruity'],
      ['pear', 'peony', 'jasmine', 'sandalwood', 'musk'],
      ['elegant', 'soft', 'radiant', 'feminine', 'versatile'],
      'Pear and peony in a soft, radiant floral-musk.',
      { genderStyle: 'feminine' },
    ],
  ],
);

const yvesSaintLaurent = expandBrand(
  {
    brand: 'Yves Saint Laurent',
    priceRange: 'designer',
    priceDisplay: '$110-$185',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
  },
  [
    [
      'ysl-myslf',
      'MYSLF',
      'floral-soft',
      ['floral', 'woody', 'fresh'],
      ['orange blossom', 'ambergris', 'woody', 'floral'],
      ['bergamot', 'orange blossom', 'ambergris', 'patchouli', 'woods'],
      ['modern', 'clean', 'versatile', 'elegant', 'signature'],
      'Modern orange blossom and ambergris over clean, refined woods.',
      { genderStyle: 'masculine' },
    ],
    [
      'ysl-la-nuit-de-lhomme',
      'La Nuit de L\'Homme',
      'woody-elegant',
      ['woody', 'spicy', 'fresh'],
      ['cardamom', 'aromatic', 'woody', 'amber'],
      ['cardamom', 'bergamot', 'lavender', 'cedar', 'vetiver'],
      ['seductive', 'smooth', 'date-night', 'elegant', 'versatile'],
      'Smooth cardamom and cedar with a seductive, refined aura.',
      { genderStyle: 'masculine' },
    ],
    [
      'ysl-lhomme',
      'L\'Homme',
      'fresh-clean',
      ['fresh', 'woody', 'spicy'],
      ['citrus', 'aromatic', 'woody', 'spicy'],
      ['ginger', 'bergamot', 'violet leaf', 'cedar', 'tonka bean'],
      ['clean', 'elegant', 'versatile', 'daytime', 'classic'],
      'Bright ginger and violet leaf over clean cedar and tonka.',
      { genderStyle: 'masculine' },
    ],
    [
      'ysl-y-le-parfum',
      'Y Le Parfum',
      'amber-spicy',
      ['fresh', 'woody', 'spicy'],
      ['aromatic', 'apple', 'sage', 'amber'],
      ['apple', 'ginger', 'sage', 'cedar', 'tonka bean'],
      ['bold', 'fresh-spicy', 'modern', 'versatile', 'confident'],
      'A bolder, warmer Y — apple, sage, cedar, and tonka.',
      { genderStyle: 'masculine' },
    ],
    [
      'ysl-mon-paris',
      'Mon Paris',
      'floral-bold',
      ['floral', 'sweet', 'woody'],
      ['fruity', 'floral', 'patchouli', 'sweet'],
      ['strawberry', 'raspberry', 'peony', 'patchouli', 'white musk'],
      ['romantic', 'fruity', 'flirty', 'feminine', 'date'],
      'A flirty fruity-floral chypre of berries, peony, and patchouli.',
      { genderStyle: 'feminine' },
    ],
    [
      'ysl-libre-intense',
      'Libre Intense',
      'amber-spicy',
      ['floral', 'sweet', 'oriental'],
      ['lavender', 'vanilla', 'amber', 'floral'],
      ['lavender', 'orange blossom', 'vanilla', 'tonka bean', 'amber'],
      ['warm', 'sensual', 'evening', 'feminine', 'statement'],
      'A warmer Libre with lavender, orange blossom, and amber vanilla.',
      { genderStyle: 'feminine', projection: 'strong' },
    ],
    [
      'ysl-black-opium-le-parfum',
      'Black Opium Le Parfum',
      'sweet-gourmand',
      ['sweet', 'gourmand', 'floral'],
      ['coffee', 'vanilla', 'floral', 'sweet'],
      ['coffee', 'black tea', 'jasmine', 'vanilla', 'patchouli'],
      ['addictive', 'coffee', 'warm', 'night', 'feminine'],
      'A deeper coffee-and-vanilla Black Opium with jasmine warmth.',
      { genderStyle: 'feminine' },
    ],
    [
      'ysl-opium',
      'Opium',
      'amber-spicy',
      ['oriental', 'spicy', 'sweet'],
      ['spicy', 'amber', 'resinous', 'balsamic'],
      ['mandarin', 'clove', 'myrrh', 'patchouli', 'vanilla'],
      ['iconic', 'spicy', 'opulent', 'evening', 'bold'],
      'The iconic spicy oriental — clove, myrrh, patchouli, and vanilla.',
      { genderStyle: 'feminine', projection: 'strong' },
    ],
    [
      'ysl-cinema',
      'Cinéma',
      'floral-soft',
      ['floral', 'sweet', 'gourmand'],
      ['floral', 'almond', 'vanilla', 'powdery'],
      ['almond blossom', 'amaryllis', 'jasmine', 'vanilla', 'amber'],
      ['soft', 'glamorous', 'sweet', 'feminine', 'romantic'],
      'Soft almond blossom and jasmine over sweet vanilla amber.',
      { genderStyle: 'feminine' },
    ],
    [
      'ysl-y-edt',
      'Y Eau de Toilette',
      'fresh-aquatic',
      ['fresh', 'aquatic', 'woody'],
      ['aromatic', 'citrus', 'marine', 'woody'],
      ['bergamot', 'ginger', 'sage', 'geranium', 'ambergris'],
      ['fresh', 'crisp', 'daytime', 'clean', 'versatile'],
      'A crisp aquatic-aromatic with bergamot, sage, and ambergris.',
      { genderStyle: 'masculine', projection: 'moderate', longevity: 'moderate' },
    ],
  ],
);

const diorDesigner = expandBrand(
  {
    brand: 'Dior',
    priceRange: 'designer',
    priceDisplay: '$100-$185',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
  },
  [
    [
      'dior-jadore-edp',
      'J\'adore',
      'floral-bold',
      ['floral', 'fresh', 'sweet'],
      ['floral', 'fruity', 'musky', 'sweet'],
      ['ylang-ylang', 'damask rose', 'jasmine', 'magnolia', 'musk'],
      ['glamorous', 'radiant', 'feminine', 'elegant', 'signature'],
      'A radiant white-floral bouquet of ylang, rose, and jasmine.',
      { genderStyle: 'feminine' },
    ],
    [
      'dior-homme-original',
      'Dior Homme',
      'woody-elegant',
      ['woody', 'floral', 'spicy'],
      ['iris', 'powdery', 'woody', 'leather'],
      ['bergamot', 'iris', 'cocoa', 'leather', 'vetiver'],
      ['refined', 'powdery', 'tailored', 'elegant', 'signature'],
      'Powdery iris and cocoa with refined leather and woods.',
      { genderStyle: 'masculine' },
    ],
    [
      'dior-fahrenheit',
      'Fahrenheit',
      'green-woody',
      ['woody', 'floral', 'spicy'],
      ['violet', 'petrol', 'leather', 'woody'],
      ['violet leaf', 'nutmeg', 'leather', 'cedar', 'balsam'],
      ['distinctive', 'retro', 'rugged', 'statement', 'classic'],
      'The cult violet-leather-and-gasoline accord over warm woods.',
      { genderStyle: 'masculine', projection: 'strong' },
    ],
    [
      'dior-sauvage-elixir',
      'Sauvage Elixir',
      'amber-spicy',
      ['spicy', 'woody', 'oriental'],
      ['spicy', 'licorice', 'amber', 'woody'],
      ['cinnamon', 'nutmeg', 'grapefruit', 'lavender', 'licorice'],
      ['potent', 'spiced', 'dense', 'evening', 'statement'],
      'A potent spiced elixir of cinnamon, licorice, lavender, and woods.',
      { projection: 'strong' },
    ],
    [
      'dior-homme-cologne',
      'Dior Homme Cologne',
      'fresh-clean',
      ['citrus', 'fresh', 'clean'],
      ['citrus', 'floral', 'musky', 'clean'],
      ['bergamot', 'grapefruit', 'orange blossom', 'white musk', 'cedar'],
      ['clean', 'crisp', 'minimal', 'daytime', 'versatile'],
      'A clean citrus cologne with orange blossom and white musk.',
      { genderStyle: 'masculine', projection: 'subtle', longevity: 'moderate' },
    ],
    [
      'dior-miss-dior-blooming-bouquet',
      'Miss Dior Blooming Bouquet',
      'floral-soft',
      ['floral', 'fresh', 'sweet'],
      ['floral', 'peony', 'powdery', 'fruity'],
      ['peony', 'rose', 'apricot', 'white musk', 'sandalwood'],
      ['soft', 'romantic', 'airy', 'feminine', 'daytime'],
      'A soft peony-and-rose bouquet with fruity, powdery warmth.',
      { genderStyle: 'feminine' },
    ],
    [
      'dior-poison-girl',
      'Poison Girl',
      'sweet-gourmand',
      ['sweet', 'floral', 'gourmand'],
      ['almond', 'vanilla', 'rose', 'sweet'],
      ['orange', 'bitter almond', 'rose', 'tonka bean', 'vanilla'],
      ['addictive', 'sweet', 'flirty', 'feminine', 'night'],
      'An addictive almond-and-vanilla gourmand with a rosy heart.',
      { genderStyle: 'feminine' },
    ],
    [
      'dior-hypnotic-poison',
      'Hypnotic Poison',
      'sweet-gourmand',
      ['sweet', 'oriental', 'gourmand'],
      ['almond', 'vanilla', 'spicy', 'woody'],
      ['bitter almond', 'caraway', 'jasmine', 'vanilla', 'sandalwood'],
      ['hypnotic', 'almond', 'sultry', 'evening', 'iconic'],
      'A hypnotic bitter-almond and vanilla with spicy, woody depth.',
      { genderStyle: 'feminine', projection: 'strong' },
    ],
    [
      'dior-joy',
      'JOY by Dior',
      'floral-soft',
      ['floral', 'woody', 'fresh'],
      ['floral', 'citrus', 'musky', 'woody'],
      ['bergamot', 'grasse rose', 'jasmine', 'sandalwood', 'musk'],
      ['radiant', 'elegant', 'clean', 'feminine', 'versatile'],
      'A radiant rose-jasmine over creamy sandalwood and musk.',
      { genderStyle: 'feminine' },
    ],
    [
      'dior-eau-sauvage',
      'Eau Sauvage',
      'fresh-clean',
      ['citrus', 'fresh', 'woody'],
      ['citrus', 'aromatic', 'floral', 'woody'],
      ['lemon', 'basil', 'jasmine', 'oakmoss', 'vetiver'],
      ['classic', 'crisp', 'elegant', 'daytime', 'timeless'],
      'A timeless citrus-chypre with basil, jasmine, and oakmoss.',
      { genderStyle: 'masculine' },
    ],
  ],
);

const xerjoff = expandBrand(
  {
    brand: 'Xerjoff',
    priceRange: 'niche',
    priceDisplay: '$240-$500',
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
  },
  [
    [
      'xerjoff-alexandria-ii',
      'Alexandria II',
      'amber-spicy',
      ['oriental', 'sweet', 'woody'],
      ['amber', 'honey', 'oud', 'spicy'],
      ['bergamot', 'honey', 'rose', 'oud', 'vanilla'],
      ['opulent', 'royal', 'rich', 'statement', 'evening'],
      'A regal blend of honey, rose, oud, and golden vanilla amber.',
    ],
    [
      'xerjoff-accento',
      'Accento',
      'floral-bold',
      ['floral', 'fresh', 'woody'],
      ['pineapple', 'floral', 'green', 'woody'],
      ['pineapple', 'jasmine', 'orange blossom', 'rose', 'oakmoss'],
      ['radiant', 'fruity-floral', 'vibrant', 'elegant', 'versatile'],
      'A vibrant pineapple-and-jasmine floral over green oakmoss.',
      { genderStyle: 'feminine' },
    ],
    [
      'xerjoff-more-than-words',
      'More Than Words',
      'amber-spicy',
      ['sweet', 'oriental', 'woody'],
      ['vanilla', 'tobacco', 'amber', 'spicy'],
      ['cardamom', 'orange blossom', 'tobacco', 'vanilla', 'sandalwood'],
      ['warm', 'creamy', 'opulent', 'evening', 'signature'],
      'Creamy vanilla, tobacco, and orange blossom over warm woods.',
    ],
    [
      'xerjoff-40-knots',
      '40 Knots',
      'fresh-aquatic',
      ['aquatic', 'fresh', 'woody'],
      ['marine', 'citrus', 'aromatic', 'woody'],
      ['sea notes', 'bergamot', 'rosemary', 'vetiver', 'ambergris'],
      ['nautical', 'breezy', 'salty', 'luxurious', 'summer'],
      'A luxurious nautical breeze of sea air, citrus, and vetiver.',
      { projection: 'moderate' },
    ],
    [
      'xerjoff-italica',
      'Italica',
      'amber-spicy',
      ['sweet', 'oriental', 'woody'],
      ['vanilla', 'tonka', 'amber', 'tobacco'],
      ['benzoin', 'tonka bean', 'vanilla', 'tobacco', 'sandalwood'],
      ['cozy', 'creamy', 'warm', 'opulent', 'evening'],
      'A cozy vanilla-tonka and tobacco wrapped in soft amber.',
    ],
    [
      'xerjoff-laylati',
      'Laylati',
      'amber-spicy',
      ['oriental', 'sweet', 'floral'],
      ['honey', 'amber', 'floral', 'balsamic'],
      ['honey', 'jasmine', 'rose', 'amber', 'vanilla'],
      ['golden', 'honeyed', 'opulent', 'radiant', 'evening'],
      'A golden honey-and-floral amber with luminous warmth.',
      { genderStyle: 'feminine' },
    ],
    [
      'xerjoff-richwood',
      'Richwood',
      'woody-elegant',
      ['woody', 'citrus', 'spicy'],
      ['vetiver', 'citrus', 'woody', 'aromatic'],
      ['bergamot', 'sage', 'vetiver', 'cedar', 'musk'],
      ['refined', 'tailored', 'elegant', 'versatile', 'clean'],
      'A refined vetiver-and-citrus woody with tailored polish.',
    ],
    [
      'xerjoff-torino22',
      'Torino22',
      'sweet-gourmand',
      ['sweet', 'gourmand', 'floral'],
      ['marshmallow', 'floral', 'musky', 'sweet'],
      ['orange blossom', 'marshmallow', 'white flowers', 'musk', 'vanilla'],
      ['fluffy', 'sweet', 'airy', 'playful', 'radiant'],
      'A fluffy marshmallow-and-white-flower cloud with airy musk.',
    ],
    [
      'xerjoff-ouverture',
      'Ouverture',
      'amber-spicy',
      ['oriental', 'sweet', 'woody'],
      ['amber', 'honey', 'tobacco', 'balsamic'],
      ['davana', 'honey', 'tobacco', 'amber', 'sandalwood'],
      ['rich', 'boozy', 'opulent', 'warm', 'evening'],
      'A rich, boozy amber with honey, tobacco, and sandalwood.',
    ],
    [
      'xerjoff-renaissance',
      'Renaissance',
      'floral-soft',
      ['floral', 'fresh', 'woody'],
      ['floral', 'green', 'citrus', 'musky'],
      ['bergamot', 'peony', 'jasmine', 'cedar', 'musk'],
      ['elegant', 'fresh-floral', 'radiant', 'feminine', 'versatile'],
      'An elegant fresh-floral of peony, jasmine, cedar, and musk.',
      { genderStyle: 'feminine', projection: 'moderate' },
    ],
  ],
);

const chanel = expandBrand(
  {
    brand: 'Chanel',
    priceRange: 'designer',
    priceDisplay: '$110-$210',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
  },
  [
    [
      'chanel-coco-noir',
      'Coco Noir',
      'amber-spicy',
      ['oriental', 'floral', 'woody'],
      ['amber', 'floral', 'patchouli', 'woody'],
      ['grapefruit', 'rose', 'jasmine', 'patchouli', 'sandalwood'],
      ['elegant', 'mysterious', 'evening', 'opulent', 'feminine'],
      'A mysterious oriental of rose, jasmine, patchouli, and amber.',
      { genderStyle: 'feminine' },
    ],
    [
      'chanel-coco-mademoiselle-intense',
      'Coco Mademoiselle Intense',
      'amber-spicy',
      ['oriental', 'floral', 'woody'],
      ['patchouli', 'amber', 'floral', 'vanilla'],
      ['orange', 'rose', 'jasmine', 'patchouli', 'vanilla'],
      ['bold', 'warm', 'feminine', 'evening', 'statement'],
      'A warmer, deeper Coco Mademoiselle with amber and vanilla.',
      { genderStyle: 'feminine', projection: 'strong' },
    ],
    [
      'chanel-chance-eau-fraiche',
      'Chance Eau Fraîche',
      'citrus-beach',
      ['citrus', 'floral', 'fresh'],
      ['citrus', 'floral', 'green', 'musky'],
      ['lemon', 'jasmine', 'teak wood', 'amber', 'musk'],
      ['fresh', 'vibrant', 'daytime', 'clean', 'feminine'],
      'A vibrant citrus-floral with jasmine, teak, and clean musk.',
      { genderStyle: 'feminine' },
    ],
    [
      'chanel-no-5-leau',
      'N°5 L\'Eau',
      'floral-soft',
      ['floral', 'fresh', 'clean'],
      ['aldehydic', 'citrus', 'floral', 'musky'],
      ['lemon', 'aldehydes', 'rose', 'jasmine', 'cedar'],
      ['modern', 'airy', 'clean', 'elegant', 'feminine'],
      'A modern, airy N°5 — bright aldehydes, rose, jasmine, and cedar.',
      { genderStyle: 'feminine' },
    ],
    [
      'chanel-gabrielle',
      'Gabrielle',
      'floral-bold',
      ['floral', 'fresh', 'woody'],
      ['white floral', 'citrus', 'musky', 'woody'],
      ['grasse jasmine', 'ylang-ylang', 'orange blossom', 'tuberose', 'sandalwood'],
      ['luminous', 'white-floral', 'radiant', 'feminine', 'elegant'],
      'A luminous bouquet of four white flowers over soft woods.',
      { genderStyle: 'feminine' },
    ],
    [
      'chanel-allure-homme-sport',
      'Allure Homme Sport',
      'fresh-clean',
      ['fresh', 'citrus', 'woody'],
      ['citrus', 'aromatic', 'woody', 'amber'],
      ['orange', 'sea notes', 'pepper', 'cedar', 'tonka bean'],
      ['sporty', 'fresh', 'clean', 'versatile', 'daytime'],
      'A sporty fresh-woody with citrus, pepper, cedar, and tonka.',
      { genderStyle: 'masculine' },
    ],
    [
      'chanel-allure-homme',
      'Allure Homme',
      'woody-elegant',
      ['woody', 'citrus', 'spicy'],
      ['citrus', 'aromatic', 'woody', 'vanilla'],
      ['mandarin', 'pepper', 'tonka bean', 'cedar', 'vanilla'],
      ['refined', 'smooth', 'versatile', 'elegant', 'classic'],
      'A smooth, refined woody with mandarin, tonka, and cedar.',
      { genderStyle: 'masculine' },
    ],
    [
      'chanel-egoiste',
      'Égoïste',
      'woody-elegant',
      ['woody', 'spicy', 'floral'],
      ['sandalwood', 'spicy', 'rose', 'amber'],
      ['coriander', 'rose', 'sandalwood', 'cinnamon', 'amber'],
      ['retro', 'warm', 'distinctive', 'bold', 'classic'],
      'A bold retro sandalwood with rose, spice, and warm amber.',
      { genderStyle: 'masculine', projection: 'strong' },
    ],
    [
      'chanel-antaeus',
      'Antaeus',
      'amber-spicy',
      ['woody', 'spicy', 'oriental'],
      ['leather', 'aromatic', 'spicy', 'animalic'],
      ['lime', 'myrtle', 'leather', 'patchouli', 'labdanum'],
      ['vintage', 'leathery', 'rugged', 'bold', 'evening'],
      'A vintage leather-and-spice powerhouse with mossy depth.',
      { genderStyle: 'masculine', projection: 'strong' },
    ],
    [
      'chanel-no-19',
      'N°19',
      'green-woody',
      ['floral', 'woody', 'fresh'],
      ['green', 'iris', 'floral', 'woody'],
      ['galbanum', 'iris', 'rose', 'vetiver', 'oakmoss'],
      ['crisp', 'green', 'elegant', 'sophisticated', 'classic'],
      'A crisp green floral of galbanum, iris, vetiver, and oakmoss.',
      { genderStyle: 'feminine' },
    ],
  ],
);

const diptyque = expandBrand(
  {
    brand: 'Diptyque',
    priceRange: 'niche',
    priceDisplay: '$140-$210',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'niche',
  },
  [
    [
      'diptyque-do-son',
      'Do Son',
      'floral-bold',
      ['floral', 'fresh', 'clean'],
      ['tuberose', 'floral', 'marine', 'green'],
      ['tuberose', 'orange blossom', 'pink pepper', 'rose', 'musk'],
      ['airy', 'tuberose', 'elegant', 'romantic', 'feminine'],
      'An airy tuberose with orange blossom, pepper, and marine softness.',
      { genderStyle: 'feminine' },
    ],
    [
      'diptyque-tam-dao',
      'Tam Dao',
      'woody-elegant',
      ['woody', 'clean', 'spicy'],
      ['sandalwood', 'creamy', 'woody', 'milky'],
      ['sandalwood', 'cedar', 'cypress', 'rose', 'musk'],
      ['creamy', 'serene', 'minimal', 'meditative', 'versatile'],
      'Creamy sandalwood and cedar with a serene, milky calm.',
    ],
    [
      'diptyque-eau-rose',
      'Eau Rose',
      'floral-soft',
      ['floral', 'fresh', 'clean'],
      ['rose', 'fruity', 'green', 'musky'],
      ['litchi', 'rose', 'peony', 'honey', 'musk'],
      ['fresh-rose', 'soft', 'romantic', 'daytime', 'feminine'],
      'A fresh, dewy rose with litchi, peony, and soft musk.',
      { genderStyle: 'feminine' },
    ],
    [
      'diptyque-eau-des-sens',
      'Eau des Sens',
      'citrus-beach',
      ['citrus', 'fresh', 'woody'],
      ['orange', 'aromatic', 'green', 'woody'],
      ['bitter orange', 'angelica', 'juniper', 'patchouli', 'musk'],
      ['radiant', 'citrus', 'aromatic', 'versatile', 'daytime'],
      'Radiant bitter orange and angelica over patchouli and musk.',
    ],
    [
      'diptyque-ilio',
      'Ilio',
      'citrus-beach',
      ['floral', 'citrus', 'fresh'],
      ['iris', 'solar', 'citrus', 'marine'],
      ['mandarin', 'iris', 'jasmine', 'ambrette', 'sea notes'],
      ['solar', 'luminous', 'airy', 'summer', 'elegant'],
      'A solar iris-and-mandarin glow with airy marine warmth.',
    ],
    [
      'diptyque-eau-capitale',
      'Eau Capitale',
      'floral-bold',
      ['floral', 'spicy', 'woody'],
      ['rose', 'spicy', 'woody', 'musky'],
      ['bergamot', 'pink pepper', 'rose', 'patchouli', 'musk'],
      ['chic', 'rosy', 'spicy', 'elegant', 'versatile'],
      'A chic spiced rose with pink pepper, patchouli, and musk.',
    ],
    [
      'diptyque-34',
      'Eau de Parfum 34',
      'green-woody',
      ['woody', 'spicy', 'floral'],
      ['aromatic', 'woody', 'spicy', 'floral'],
      ['basil', 'pink pepper', 'tuberose', 'sandalwood', 'musk'],
      ['eclectic', 'aromatic', 'signature', 'versatile', 'elegant'],
      'An eclectic house blend of basil, pepper, tuberose, and woods.',
    ],
    [
      'diptyque-volutes',
      'Volutes',
      'amber-spicy',
      ['oriental', 'spicy', 'sweet'],
      ['tobacco', 'honey', 'spicy', 'powdery'],
      ['tobacco', 'honey', 'iris', 'hay', 'myrrh'],
      ['warm', 'smoky-sweet', 'vintage', 'cozy', 'evening'],
      'Honeyed tobacco and iris with a warm, powdery smoke.',
    ],
    [
      'diptyque-oyedo',
      'Oyédo',
      'citrus-beach',
      ['citrus', 'fresh', 'sweet'],
      ['citrus', 'candied', 'green', 'fresh'],
      ['yuzu', 'lime', 'mandarin', 'thyme', 'musk'],
      ['zesty', 'juicy', 'playful', 'summery', 'energetic'],
      'A zesty candied-yuzu and lime with a green, juicy lift.',
    ],
    [
      'diptyque-vetyverio',
      'Vetyverio',
      'green-woody',
      ['woody', 'floral', 'fresh'],
      ['vetiver', 'green', 'floral', 'earthy'],
      ['vetiver', 'grapefruit', 'rose', 'clove', 'myrrh'],
      ['earthy', 'green', 'sophisticated', 'versatile', 'elegant'],
      'A sophisticated vetiver with grapefruit, rose, and earthy depth.',
    ],
  ],
);

export const brandExpansion: FragranceSeed[] = [
  ...zoologist,
  ...maisonMargiela,
  ...maisonMargielaExtra,
  ...maisonFrancisKurkdjian,
  ...tomFordPrivateBlend,
  ...tomFordSignature,
  ...initioParfums,
  ...louisVuitton,
  ...goldfieldBanks,
  ...parfumsDeMarly,
  ...yvesSaintLaurent,
  ...diorDesigner,
  ...xerjoff,
  ...chanel,
  ...diptyque,
];
