import { withProfile, type ProfileName } from './fragrance-expansion';
import type {
  FragranceSeed,
  GenderStyle,
  Longevity,
  PriceRange,
  Projection,
  ScentFamily,
  Tier,
} from './fragrances';

type CompletionOverrides = Partial<Pick<
  FragranceSeed,
  'genderStyle' | 'projection' | 'longevity' | 'priceRange' | 'priceDisplay' | 'tier'
>>;

type CompletionEntry = [
  brand: string,
  id: string,
  name: string,
  profile: ProfileName,
  scentFamilies: ScentFamily[],
  accords: string[],
  notes: string[],
  vibeTags: string[],
  shortDescription: string,
  overrides?: CompletionOverrides,
];

type BrandDefaults = {
  priceRange: PriceRange;
  priceDisplay: string;
  genderStyle: GenderStyle;
  projection: Projection;
  longevity: Longevity;
  tier: Tier;
  productUrl: string;
};

const brandDefaults: Record<string, BrandDefaults> = {
  Zoologist: {
    priceRange: 'niche',
    priceDisplay: '$175-$210',
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    productUrl: 'https://www.zoologistperfumes.com/collections/zoologist-perfumes',
  },
  'Maison Margiela': {
    priceRange: 'designer',
    priceDisplay: '$85-$180',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    productUrl: 'https://www.maisonmargiela-fragrances.us/fragrances/replica/',
  },
  'Maison Francis Kurkdjian': {
    priceRange: 'niche',
    priceDisplay: '$245-$395',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
    productUrl: 'https://www.franciskurkdjian.com/us-en/fragrances/',
  },
  'Tom Ford': {
    priceRange: 'niche',
    priceDisplay: '$160-$450',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
    productUrl: 'https://www.tomfordbeauty.com/product/fragrance',
  },
  'Initio Parfums Privés': {
    priceRange: 'niche',
    priceDisplay: '$320-$410',
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    productUrl: 'https://www.initio-parfums.com/',
  },
  'Louis Vuitton': {
    priceRange: 'niche',
    priceDisplay: '$320-$475',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
    productUrl: 'https://us.louisvuitton.com/eng-us/fragrances/_/N-t1xadyga',
  },
  'Goldfield & Banks': {
    priceRange: 'niche',
    priceDisplay: '$155-$235',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'niche',
    productUrl: 'https://us.goldfieldandbanks.com/collections/perfume',
  },
  'Parfums de Marly': {
    priceRange: 'niche',
    priceDisplay: '$250-$390',
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    productUrl: 'https://us.parfums-de-marly.com/collections/fragrances',
  },
  'Yves Saint Laurent': {
    priceRange: 'designer',
    priceDisplay: '$95-$295',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    productUrl: 'https://www.yslbeautyus.com/fragrance/',
  },
  Dior: {
    priceRange: 'designer',
    priceDisplay: '$100-$330',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    productUrl: 'https://www.dior.com/en_us/beauty/fragrance',
  },
  Xerjoff: {
    priceRange: 'niche',
    priceDisplay: '$190-$450',
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    productUrl: 'https://xerjoff.com/collections/perfume',
  },
  Chanel: {
    priceRange: 'designer',
    priceDisplay: '$110-$300',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    productUrl: 'https://www.chanel.com/us/fragrance/',
  },
  Diptyque: {
    priceRange: 'niche',
    priceDisplay: '$140-$230',
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'niche',
    productUrl: 'https://www.diptyqueparis.com/en_us/c/fragrances.html',
  },
};

function entry([
  brand,
  id,
  name,
  profile,
  scentFamilies,
  accords,
  notes,
  vibeTags,
  shortDescription,
  overrides = {},
]: CompletionEntry): FragranceSeed {
  const defaults = brandDefaults[brand];
  if (!defaults) throw new Error(`Missing completion defaults for ${brand}`);

  return withProfile({
    ...defaults,
    ...overrides,
    brand,
    id,
    name,
    profile,
    scentFamilies,
    accords,
    notes,
    vibeTags,
    shortDescription,
    sourceUrl: defaults.productUrl,
  });
}

const entries: CompletionEntry[] = [
  ['Zoologist', 'zoologist-bat', 'Bat', 'fruity-playful', ['sweet', 'gourmand', 'woody'], ['fruit', 'earthy', 'mineral', 'musky'], ['banana', 'fig', 'tropical fruit', 'mineral notes', 'musk'], ['cave', 'fruity', 'earthy', 'unusual', 'nocturnal'], 'Tropical fruit, cool mineral cave air, and earthy musk with nocturnal strangeness.'],
  ['Zoologist', 'zoologist-beaver', 'Beaver', 'green-woody', ['woody', 'fresh', 'clean'], ['woody', 'aquatic', 'leather', 'green'], ['linden blossom', 'iris', 'castoreum accord', 'woods', 'musk'], ['riverbank', 'woody', 'animalic', 'clean', 'natural'], 'A damp riverbank of woods, soft florals, clean musk, and animalic warmth.'],
  ['Zoologist', 'zoologist-civet', 'Civet', 'amber-spicy', ['oriental', 'floral', 'spicy'], ['animalic', 'amber', 'floral', 'spicy'], ['bergamot', 'black pepper', 'civet accord', 'ylang-ylang', 'vanilla'], ['vintage', 'glamorous', 'animalic', 'warm', 'opulent'], 'A vintage-style amber floral with spice, plush warmth, and animalic glamour.'],
  ['Zoologist', 'zoologist-dodo', 'Dodo', 'green-woody', ['fresh', 'woody', 'clean'], ['green', 'aromatic', 'tropical', 'earthy'], ['bergamot', 'rosemary', 'lime', 'lavender', 'oakmoss'], ['wild', 'green', 'herbal', 'quirky', 'lush'], 'A vivid herbal-green composition with citrus lift and mossy tropical depth.'],
  ['Zoologist', 'zoologist-dragonfly', 'Dragonfly', 'fresh-aquatic', ['aquatic', 'floral', 'fresh'], ['aquatic', 'floral', 'green', 'rainy'], ['rainwater accord', 'lotus', 'iris', 'rice', 'musk'], ['pond', 'rain', 'delicate', 'watery', 'serene'], 'A delicate pond after rain: watery florals, rice powder, iris, and soft musk.'],
  ['Zoologist', 'zoologist-elephant', 'Elephant', 'green-woody', ['fresh', 'woody', 'clean'], ['green leaves', 'tea', 'coconut', 'woody'], ['green leaves', 'darjeeling tea', 'coconut milk', 'sandalwood', 'musk'], ['jungle', 'green', 'creamy', 'gentle', 'earthy'], 'Lush jungle leaves, tea, coconut milk, and sandalwood with gentle green warmth.'],
  ['Zoologist', 'zoologist-hyrax', 'Hyrax', 'smoky-dark', ['oriental', 'woody', 'spicy'], ['animalic', 'amber', 'leather', 'earthy'], ['saffron', 'rose', 'hyraceum accord', 'oud', 'amber'], ['animalic', 'intense', 'earthy', 'bold', 'challenging'], 'A powerful animalic amber-oud with saffron, rose, and earthy leather facets.', { projection: 'strong' }],
  ['Zoologist', 'zoologist-koala', 'Koala', 'fresh-clean', ['fresh', 'clean', 'woody'], ['eucalyptus', 'tea', 'musky', 'green'], ['eucalyptus', 'menthol honey gumdrops', 'black tea', 'mimosa', 'musk'], ['eucalyptus', 'clean', 'calming', 'green', 'soft'], 'A calming eucalyptus-tea scent softened by mimosa, musk, and airy woods.', { projection: 'moderate' }],
  ['Zoologist', 'zoologist-macaque-yuzu', 'Macaque Yuzu', 'citrus-beach', ['citrus', 'fresh', 'woody'], ['yuzu', 'green', 'woody', 'incense'], ['yuzu', 'juniper berries', 'hinoki wood', 'incense', 'musk'], ['japanese-forest', 'bright', 'yuzu', 'zen', 'green'], 'Bright yuzu, juniper, hinoki, and incense with a meditative forest mood.'],
  ['Zoologist', 'zoologist-musk-deer', 'Musk Deer', 'skin-musk', ['clean', 'woody', 'floral'], ['musk', 'sandalwood', 'powdery', 'floral'], ['cardamom', 'rose', 'sandalwood', 'ambrette', 'musk'], ['soft', 'powdery', 'intimate', 'elegant', 'skin'], 'A soft musk and sandalwood aura with rose, ambrette, and powdery warmth.', { projection: 'moderate' }],
  ['Zoologist', 'zoologist-nightingale', 'Nightingale', 'floral-bold', ['floral', 'sweet', 'woody'], ['plum', 'rose', 'chypre', 'mossy'], ['bergamot', 'plum blossom', 'rose', 'patchouli', 'moss'], ['romantic', 'chypre', 'plum', 'elegant', 'vintage'], 'A romantic fruity-floral chypre with plum blossom, rose, patchouli, and moss.'],
  ['Zoologist', 'zoologist-rhinoceros', 'Rhinoceros', 'smoky-dark', ['woody', 'spicy', 'oriental'], ['rum', 'leather', 'tobacco', 'smoky'], ['rum', 'whisky', 'tobacco', 'leather', 'oud'], ['boozy', 'leathery', 'powerful', 'rugged', 'night'], 'Boozy leather, tobacco, smoke, and oud with rugged heavyweight presence.', { projection: 'strong' }],
  ['Zoologist', 'zoologist-sloth', 'Sloth', 'green-woody', ['fresh', 'woody', 'floral'], ['green', 'earthy', 'chamomile', 'mossy'], ['chamomile', 'acai berry', 'violet leaf', 'jasmine', 'oakmoss'], ['slow', 'mossy', 'green', 'humid', 'natural'], 'A slow humid forest of chamomile, moss, violet leaf, and earthy green facets.'],
  ['Zoologist', 'zoologist-chipmunk', 'Chipmunk', 'woody-elegant', ['woody', 'sweet', 'spicy'], ['hazelnut', 'woody', 'earthy', 'warm spicy'], ['quince', 'pink pepper', 'hazelnut', 'oak', 'vetiver'], ['nutty', 'cozy', 'forest-floor', 'warm', 'playful'], 'A cozy nutty woodland scent with hazelnut, oak, quince, and vetiver.'],
  ['Zoologist', 'zoologist-cockatiel', 'Cockatiel', 'sweet-gourmand', ['sweet', 'floral', 'gourmand'], ['powdery', 'champagne', 'vanilla', 'fruity'], ['champagne', 'raspberry', 'rhubarb', 'mimosa', 'vanilla'], ['sparkling', 'powdery', 'cheerful', 'fruity', 'soft'], 'Sparkling fruit, mimosa powder, and vanilla with bright playful charm.'],
  ['Zoologist', 'zoologist-mongoose', 'Mongoose', 'green-woody', ['citrus', 'woody', 'spicy'], ['citrus', 'green', 'animalic', 'woody'], ['bergamot', 'mandarin', 'basil', 'vetiver', 'musk'], ['sharp', 'green', 'agile', 'citrus', 'earthy'], 'Sharp citrus and green herbs over vetiver and musky animalic warmth.'],
  ['Zoologist', 'zoologist-northern-cardinal', 'Northern Cardinal', 'fresh-clean', ['fresh', 'woody', 'clean'], ['snowy', 'green', 'rose', 'musky'], ['bergamot', 'snow accord', 'rose', 'fir balsam', 'musk'], ['winter', 'red-berry', 'snowy', 'clean', 'forest'], 'Snow-bright air, rose, fir balsam, and soft musk with winter clarity.'],
  ['Zoologist', 'zoologist-orca', 'Orca', 'fresh-aquatic', ['aquatic', 'fresh', 'woody'], ['marine', 'salty', 'ambergris', 'woody'], ['sea salt', 'tuberose', 'ambergris', 'woods', 'musk'], ['oceanic', 'deep', 'salty', 'smooth', 'powerful'], 'A deep marine floral with sea salt, ambergris, woods, and smooth oceanic power.'],

  ['Maison Francis Kurkdjian', 'mfk-baccarat-rouge-540-edp', 'Baccarat Rouge 540 Eau de Parfum', 'amber-spicy', ['oriental', 'sweet', 'woody'], ['amber', 'saffron', 'woody', 'airy'], ['saffron', 'jasmine', 'amberwood', 'ambergris', 'cedar'], ['radiant', 'signature', 'sweet-amber', 'luxury', 'transparent'], 'The airy amber-saffron icon: sweet, woody, radiant, and instantly recognizable.', { projection: 'strong' }],
  ['Maison Francis Kurkdjian', 'mfk-aqua-universalis-forte', 'Aqua Universalis forte', 'fresh-clean', ['citrus', 'clean', 'floral'], ['citrus', 'white floral', 'musky', 'fresh'], ['bergamot', 'lemon', 'white flowers', 'jasmine', 'musk'], ['linen', 'bright', 'polished', 'white-floral', 'clean'], 'A brighter, more floral take on clean citrus and white-musky linen.'],
  ['Maison Francis Kurkdjian', 'mfk-aqua-vitae-forte', 'Aqua Vitae forte', 'citrus-beach', ['citrus', 'floral', 'woody'], ['citrus', 'solar', 'floral', 'warm spicy'], ['bergamot', 'mandarin', 'ylang-ylang', 'sandalwood', 'vetiver'], ['sunlit', 'warm-skin', 'radiant', 'elegant', 'summer'], 'A more sensual solar citrus with warm florals, sandalwood, and vetiver.'],
  ['Maison Francis Kurkdjian', 'mfk-aqua-celestia-forte', 'Aqua Celestia forte', 'fresh-aquatic', ['fresh', 'citrus', 'clean'], ['lime', 'mint', 'musky', 'fresh'], ['lime', 'mint', 'blackcurrant', 'mimosa', 'musk'], ['blue-sky', 'cool', 'fresh', 'optimistic', 'clean'], 'Cool lime, mint, blackcurrant, mimosa, and musk with bright blue-sky lift.'],
  ['Maison Francis Kurkdjian', 'mfk-masculin-pluriel', 'Masculin Pluriel', 'woody-elegant', ['woody', 'fresh', 'spicy'], ['lavender', 'leather', 'woody', 'aromatic'], ['lavender', 'cedar', 'patchouli', 'vetiver', 'leather'], ['tailored', 'barbershop', 'classic', 'elegant', 'masculine'], 'A tailored aromatic fougere with lavender, woods, vetiver, and smooth leather.', { genderStyle: 'masculine' }],
  ['Maison Francis Kurkdjian', 'mfk-feminin-pluriel', 'Feminin Pluriel', 'floral-soft', ['floral', 'clean', 'woody'], ['floral', 'powdery', 'violet', 'woody'], ['violet', 'iris', 'rose', 'jasmine', 'patchouli'], ['bouquet', 'polished', 'soft', 'elegant', 'feminine'], 'A polished floral bouquet of violet, iris, rose, jasmine, and soft woods.', { genderStyle: 'feminine' }],
  ['Maison Francis Kurkdjian', 'mfk-oud-silk-mood-extrait', 'Oud Silk Mood Extrait', 'woody-elegant', ['woody', 'floral', 'oriental'], ['oud', 'rose', 'papyrus', 'spicy'], ['bergamot', 'rose', 'blue chamomile', 'papyrus', 'oud'], ['silky', 'rose-oud', 'refined', 'evening', 'luxury'], 'A denser rose-oud silk with papyrus, chamomile, and elegant lift.', { projection: 'strong' }],
  ['Maison Francis Kurkdjian', 'mfk-oud-velvet-mood', 'Oud Velvet Mood', 'smoky-dark', ['woody', 'oriental', 'spicy'], ['oud', 'smoky', 'amber', 'cinnamon'], ['cinnamon', 'saffron', 'oud', 'copahu balm', 'labdanum'], ['velvet', 'smoky', 'oud', 'formal', 'opulent'], 'A dark velvet oud with saffron, cinnamon, balsams, and resinous depth.', { projection: 'strong' }],
  ['Maison Francis Kurkdjian', 'mfk-oud-cashmere-mood', 'Oud Cashmere Mood', 'smoky-dark', ['woody', 'oriental', 'spicy'], ['oud', 'suede', 'smoky', 'amber'], ['labdanum', 'benzoin', 'vanilla', 'oud', 'cashmeran'], ['cashmere', 'dry', 'oud', 'textural', 'night'], 'Dry, textural oud wrapped in cashmeran, balsams, vanilla, and warm smoke.'],
  ['Maison Francis Kurkdjian', 'mfk-amyris-femme-extrait', 'Amyris femme Extrait', 'floral-bold', ['floral', 'sweet', 'woody'], ['floral', 'iris', 'amyris', 'warm'], ['pear', 'iris', 'jasmine', 'amyris', 'amber'], ['silky', 'luminous', 'dressy', 'feminine', 'warm'], 'A richer amyris floral with pear, iris, jasmine, and warm amber.', { genderStyle: 'feminine', projection: 'strong' }],
  ['Maison Francis Kurkdjian', 'mfk-amyris-homme-extrait', 'Amyris homme Extrait', 'woody-elegant', ['woody', 'spicy', 'oriental'], ['amyris', 'iris', 'cinnamon', 'amber'], ['mandarin', 'cinnamon', 'iris', 'amyris', 'vanilla'], ['polished', 'warm', 'masculine', 'dressy', 'smooth'], 'A deeper masculine amyris with cinnamon, iris, vanilla, and polished woods.', { genderStyle: 'masculine', projection: 'strong' }],
  ['Maison Francis Kurkdjian', 'mfk-kurky', 'Kurky', 'fruity-playful', ['sweet', 'clean', 'fresh'], ['fruity', 'musky', 'candy', 'fresh'], ['fruity notes', 'white musk', 'sweet notes', 'clean woods'], ['playful', 'candy', 'bright', 'youthful', 'soft'], 'A playful fruity musk with candy-like brightness and clean softness.', { projection: 'moderate' }],

  ['Tom Ford', 'tf-electric-cherry', 'Electric Cherry', 'fruity-playful', ['sweet', 'floral', 'clean'], ['cherry', 'ginger', 'jasmine', 'musk'], ['morello cherry', 'ginger', 'jasmine sambac', 'ambrettolide', 'pink pepper'], ['sparkling', 'cherry', 'playful', 'modern', 'bright'], 'Sparkling cherry, ginger, jasmine, and musk with a bright electric snap.'],
  ['Tom Ford', 'tf-cherry-smoke', 'Cherry Smoke', 'smoky-dark', ['sweet', 'woody', 'spicy'], ['cherry', 'smoky', 'leather', 'woody'], ['dark cherry', 'saffron', 'leather', 'olive wood', 'smoke'], ['dark-cherry', 'smoky', 'leather', 'night', 'bold'], 'Dark cherry, saffron, leather, and smoke with a sultry evening edge.', { projection: 'strong' }],
  ['Tom Ford', 'tf-soleil-neige', 'Soleil Neige', 'floral-soft', ['floral', 'fresh', 'clean'], ['white floral', 'powdery', 'citrus', 'musky'], ['bergamot', 'carrot seed', 'white flowers', 'benzoin', 'vanilla'], ['snow', 'solar', 'powdery', 'elegant', 'soft'], 'A snowy solar floral with bergamot, white blossoms, powder, and soft vanilla.'],
  ['Tom Ford', 'tf-soleil-brulant', 'Soleil Brulant', 'amber-spicy', ['oriental', 'spicy', 'floral'], ['amber', 'honey', 'spicy', 'floral'], ['mandarin', 'pink pepper', 'orange blossom', 'honey', 'amber'], ['hot-sun', 'golden', 'opulent', 'honeyed', 'luxury'], 'Hot golden amber, honey, citrus, and orange blossom with luxurious heat.', { projection: 'strong' }],
  ['Tom Ford', 'tf-mandarino-di-amalfi', 'Mandarino di Amalfi', 'citrus-beach', ['citrus', 'fresh', 'clean'], ['citrus', 'aromatic', 'green', 'fresh'], ['mandarin', 'lemon', 'grapefruit', 'basil', 'mint'], ['amalfi', 'sparkling', 'summer', 'citrus', 'vacation'], 'A sparkling Amalfi citrus breeze with herbs, mint, and clean summer brightness.'],
  ['Tom Ford', 'tf-fougere-dargent', "Fougere d'Argent", 'woody-elegant', ['fresh', 'spicy', 'woody'], ['lavender', 'ginger', 'coumarin', 'woody'], ['lavender', 'ginger', 'mandarin', 'labdanum', 'coumarin'], ['tailored', 'fougere', 'silver', 'smooth', 'modern'], 'A sleek modern fougere of lavender, ginger, citrus, labdanum, and coumarin.', { genderStyle: 'masculine' }],
  ['Tom Ford', 'tf-ebene-fume', 'Ebene Fume', 'smoky-dark', ['woody', 'spicy', 'oriental'], ['smoky', 'palo santo', 'leather', 'amber'], ['palo santo', 'black pepper', 'ebony wood', 'leather', 'resins'], ['incense', 'smoky', 'meditative', 'dark-wood', 'statement'], 'Meditative smoke, palo santo, ebony wood, leather, and dark resins.', { projection: 'strong' }],
  ['Tom Ford', 'tf-santal-blush', 'Santal Blush', 'woody-elegant', ['woody', 'spicy', 'floral'], ['sandalwood', 'spicy', 'creamy', 'floral'], ['cinnamon', 'caraway', 'ylang-ylang', 'sandalwood', 'benzoin'], ['creamy', 'sandalwood', 'soft-spice', 'elegant', 'warm'], 'Creamy sandalwood, soft spice, ylang-ylang, and balsamic warmth.'],
  ['Tom Ford', 'tf-white-suede', 'White Suede', 'skin-musk', ['clean', 'woody', 'floral'], ['suede', 'musk', 'rose', 'amber'], ['thyme', 'saffron', 'rose', 'suede', 'musk'], ['soft-suede', 'clean', 'intimate', 'quiet-luxury', 'smooth'], 'Soft suede, rose, musk, and saffron with polished skin-close elegance.'],
  ['Tom Ford', 'tf-noir-de-noir', 'Noir de Noir', 'floral-bold', ['floral', 'oriental', 'sweet'], ['rose', 'truffle', 'patchouli', 'chocolate'], ['saffron', 'black rose', 'truffle', 'patchouli', 'vanilla'], ['dark-rose', 'gothic', 'rich', 'romantic', 'night'], 'A dark rose with truffle, patchouli, saffron, and sensual gourmand depth.', { projection: 'strong' }],
  ['Tom Ford', 'tf-myrrhe-mystere', 'Myrrhe Mystere', 'amber-spicy', ['oriental', 'spicy', 'woody'], ['myrrh', 'vanilla', 'resinous', 'amber'], ['myrrh', 'vanilla', 'sandalwood', 'amber', 'resins'], ['resinous', 'mysterious', 'warm', 'sacred', 'luxury'], 'Myrrh, vanilla, sandalwood, and amber in a resinous ceremonial cloud.'],
  ['Tom Ford', 'tf-vanilla-sex', 'Vanilla Sex', 'sweet-gourmand', ['sweet', 'gourmand', 'oriental'], ['vanilla', 'almond', 'creamy', 'amber'], ['bitter almond', 'vanilla tincture', 'tonka bean', 'sandalwood', 'amber'], ['vanilla', 'creamy', 'provocative', 'addictive', 'warm'], 'A creamy almond-vanilla gourmand with tonka, sandalwood, and amber warmth.'],

  ['Initio Parfums Privés', 'initio-absolute-aphrodisiac', 'Absolute Aphrodisiac', 'sweet-gourmand', ['sweet', 'oriental', 'woody'], ['vanilla', 'amber', 'animalic', 'musky'], ['vanilla', 'amber', 'castoreum accord', 'white flowers', 'musk'], ['vanilla', 'seductive', 'animalic', 'warm', 'date-night'], 'A seductive vanilla-amber with animalic warmth and plush white florals.', { projection: 'strong' }],
  ['Initio Parfums Privés', 'initio-addictive-vibration', 'Addictive Vibration', 'floral-bold', ['floral', 'sweet', 'oriental'], ['honey', 'apple', 'orange blossom', 'musky'], ['apple blossom', 'orange blossom', 'honey', 'vanilla', 'musk'], ['honeyed', 'floral', 'addictive', 'feminine', 'radiant'], 'Honeyed blossoms, apple, vanilla, and musk with addictive sweetness.'],
  ['Initio Parfums Privés', 'initio-high-frequency', 'High Frequency', 'floral-bold', ['floral', 'sweet', 'clean'], ['almond', 'hedione', 'magnolia', 'musky'], ['magnolia', 'hedione', 'almond', 'musk'], ['radiant', 'almond', 'floral', 'modern', 'smooth'], 'Radiant magnolia, hedione, almond, and musk with smooth modern glow.'],
  ['Initio Parfums Privés', 'initio-mystic-experience', 'Mystic Experience', 'amber-spicy', ['oriental', 'woody', 'spicy'], ['coffee', 'musk', 'amber', 'woody'], ['coffee', 'musk', 'amber', 'sandalwood', 'spices'], ['mystic', 'coffee', 'warm', 'sensual', 'dense'], 'A warm coffee, musk, amber, and sandalwood blend with ritual-like depth.'],
  ['Initio Parfums Privés', 'initio-narcotic-delight', 'Narcotic Delight', 'sweet-gourmand', ['sweet', 'gourmand', 'oriental'], ['cherry', 'cognac', 'vanilla', 'tobacco'], ['cherry', 'cognac', 'pink pepper', 'tobacco', 'vanilla'], ['boozy-cherry', 'addictive', 'night-out', 'sweet', 'bold'], 'Boozy cherry, cognac, tobacco, and vanilla with night-out sweetness.', { projection: 'strong' }],
  ['Initio Parfums Privés', 'initio-oud-for-happiness', 'Oud for Happiness', 'green-woody', ['woody', 'fresh', 'spicy'], ['oud', 'ginger', 'licorice', 'green'], ['bergamot', 'ginger', 'licorice', 'oud', 'vanilla'], ['uplifting', 'oud', 'ginger', 'bright', 'unique'], 'A brighter oud lifted by ginger, bergamot, licorice, and creamy vanilla.'],

  ['Louis Vuitton', 'lv-limmensite', "L'Immensite", 'fresh-clean', ['fresh', 'citrus', 'spicy'], ['ginger', 'grapefruit', 'amber', 'fresh spicy'], ['grapefruit', 'ginger', 'ambroxan', 'sage', 'labdanum'], ['blue', 'fresh', 'versatile', 'polished', 'open-air'], 'A polished blue-fresh scent of grapefruit, ginger, sage, and ambroxan.', { genderStyle: 'masculine' }],
  ['Louis Vuitton', 'lv-nouveau-monde', 'Nouveau Monde', 'smoky-dark', ['woody', 'oriental', 'spicy'], ['oud', 'cacao', 'leather', 'amber'], ['cacao', 'oud', 'saffron', 'incense', 'leather'], ['cacao-oud', 'dark', 'luxury', 'travel', 'night'], 'Dark cacao, oud, saffron, incense, and leather with luxe travel energy.', { projection: 'strong' }],
  ['Louis Vuitton', 'lv-sur-la-route', 'Sur la Route', 'citrus-beach', ['citrus', 'fresh', 'woody'], ['citrus', 'leather', 'green', 'woody'], ['citron', 'bergamot', 'pink pepper', 'grass', 'leather'], ['road-trip', 'bright', 'green', 'casual', 'energetic'], 'A bright citrus road-trip scent with green grass, pepper, and soft leather.'],
  ['Louis Vuitton', 'lv-city-of-stars', 'City of Stars', 'citrus-beach', ['citrus', 'floral', 'fresh'], ['lime', 'tiare', 'musky', 'citrus'], ['blood orange', 'lime', 'lemon', 'tiare flower', 'musk'], ['los-angeles', 'night-drive', 'bright', 'solar', 'fun'], 'A neon citrus floral with lime, tiare, musk, and Los Angeles-night sparkle.'],
  ['Louis Vuitton', 'lv-on-the-beach', 'On the Beach', 'citrus-beach', ['citrus', 'fresh', 'woody'], ['yuzu', 'neroli', 'aromatic', 'sandy'], ['yuzu', 'neroli', 'thyme', 'rosemary', 'cypress'], ['beach', 'yuzu', 'sunny', 'salty', 'minimal'], 'Yuzu, neroli, herbs, and cypress with clean sunlit beach energy.'],
  ['Louis Vuitton', 'lv-heures-dabsence', "Heures d'Absence", 'floral-soft', ['floral', 'clean', 'fresh'], ['white floral', 'powdery', 'musky', 'fresh'], ['mimosa', 'jasmine', 'may rose', 'sandalwood', 'musk'], ['airy', 'soft-floral', 'elegant', 'daytime', 'luminous'], 'Airy mimosa, jasmine, rose, sandalwood, and musk with soft luminosity.', { genderStyle: 'feminine' }],
  ['Louis Vuitton', 'lv-rose-des-vents', 'Rose des Vents', 'floral-soft', ['floral', 'fresh', 'clean'], ['rose', 'iris', 'green', 'musky'], ['centifolia rose', 'iris', 'cedar', 'pepper', 'musk'], ['rose', 'polished', 'fresh', 'feminine', 'luxury'], 'A polished rose with iris, cedar, pepper, and clean musky freshness.', { genderStyle: 'feminine' }],
  ['Louis Vuitton', 'lv-les-sables-roses', 'Les Sables Roses', 'floral-bold', ['floral', 'oriental', 'woody'], ['rose', 'oud', 'amber', 'spicy'], ['rose', 'oud', 'ambergris', 'pepper', 'saffron'], ['rose-oud', 'desert', 'opulent', 'warm', 'formal'], 'A warm desert rose-oud with ambergris, saffron, and polished power.', { projection: 'strong' }],
  ['Louis Vuitton', 'lv-pur-oud', 'Pur Oud', 'smoky-dark', ['woody', 'oriental', 'spicy'], ['oud', 'smoky', 'leather', 'amber'], ['oud', 'saffron', 'leather', 'incense', 'amber'], ['oud', 'minimal', 'intense', 'luxury', 'night'], 'A direct, luxurious oud statement with leather, saffron, incense, and amber.', { projection: 'strong' }],
  ['Louis Vuitton', 'lv-stellar-times', 'Stellar Times', 'amber-spicy', ['oriental', 'sweet', 'floral'], ['amber', 'orange blossom', 'balsamic', 'warm'], ['orange blossom', 'amber', 'benzoin', 'peru balsam', 'vanilla'], ['celestial', 'golden', 'warm', 'limited', 'opulent'], 'A golden amber-orange blossom composition with balsamic celestial warmth.'],

  ['Parfums de Marly', 'pdm-herod', 'Herod', 'amber-spicy', ['sweet', 'spicy', 'woody'], ['tobacco', 'vanilla', 'cinnamon', 'woody'], ['cinnamon', 'tobacco leaf', 'incense', 'vanilla', 'cedar'], ['tobacco', 'date-night', 'warm', 'smooth', 'masculine'], 'Smooth tobacco, cinnamon, vanilla, incense, and cedar with rich evening warmth.', { genderStyle: 'masculine', projection: 'strong' }],
  ['Parfums de Marly', 'pdm-althair', 'Althair', 'sweet-gourmand', ['sweet', 'gourmand', 'oriental'], ['vanilla', 'orange blossom', 'cinnamon', 'amber'], ['orange blossom', 'cinnamon', 'bourbon vanilla', 'amber', 'musk'], ['vanilla', 'gourmand', 'smooth', 'winter', 'addictive'], 'A smooth bourbon-vanilla gourmand with orange blossom, cinnamon, amber, and musk.', { projection: 'strong' }],
  ['Parfums de Marly', 'pdm-valaya', 'Valaya', 'fresh-clean', ['clean', 'floral', 'fresh'], ['musky', 'aldehydic', 'white floral', 'fruity'], ['bergamot', 'mandarin', 'white peach', 'orange blossom', 'musk'], ['clean-girl', 'soft', 'luxury', 'white-shirt', 'feminine'], 'A clean white-musky floral with bergamot, peach, orange blossom, and cottony softness.', { genderStyle: 'feminine' }],
  ['Parfums de Marly', 'pdm-cassili', 'Cassili', 'fruity-playful', ['floral', 'sweet', 'fresh'], ['plum', 'tropical', 'floral', 'vanilla'], ['red currant', 'plum', 'frangipani', 'mimosa', 'vanilla'], ['plum', 'sunny', 'feminine', 'playful', 'spring'], 'A sunny plum and frangipani floral with mimosa and creamy vanilla.', { genderStyle: 'feminine' }],
  ['Parfums de Marly', 'pdm-safanad', 'Safanad', 'floral-bold', ['floral', 'sweet', 'oriental'], ['orange blossom', 'ylang', 'vanilla', 'amber'], ['pear', 'orange blossom', 'ylang-ylang', 'amber', 'vanilla'], ['golden-floral', 'feminine', 'warm', 'elegant', 'luxury'], 'A golden white-floral amber with pear, orange blossom, ylang, and vanilla.', { genderStyle: 'feminine' }],
  ['Parfums de Marly', 'pdm-oriana', 'Oriana', 'sweet-gourmand', ['sweet', 'gourmand', 'floral'], ['marshmallow', 'orange blossom', 'raspberry', 'cream'], ['mandarin', 'raspberry', 'orange blossom', 'marshmallow', 'chantilly cream'], ['marshmallow', 'fluffy', 'girly', 'sweet', 'soft'], 'A fluffy marshmallow-orange blossom gourmand with raspberry and whipped cream.', { genderStyle: 'feminine' }],
  ['Parfums de Marly', 'pdm-habdan', 'Habdan', 'amber-spicy', ['oriental', 'sweet', 'spicy'], ['apple', 'saffron', 'caramel', 'amber'], ['saffron', 'apple', 'frankincense', 'caramel', 'oud'], ['warm', 'spiced-apple', 'resinous', 'rich', 'night'], 'Spiced apple, saffron, frankincense, caramel, and oud with rich warmth.'],
  ['Parfums de Marly', 'pdm-godolphin', 'Godolphin', 'smoky-dark', ['woody', 'spicy', 'oriental'], ['leather', 'fruity', 'amber', 'saffron'], ['saffron', 'thyme', 'rose', 'leather', 'amber'], ['leather', 'smooth', 'formal', 'masculine', 'rich'], 'A polished leather with saffron, rose, amber, and masculine refinement.', { genderStyle: 'masculine' }],
  ['Parfums de Marly', 'pdm-darley', 'Darley', 'fresh-clean', ['fresh', 'spicy', 'woody'], ['lavender', 'mint', 'tonka', 'aromatic'], ['lemon', 'mint', 'lavender', 'rosemary', 'tonka bean'], ['aromatic', 'fresh', 'classic', 'clean', 'daily'], 'Fresh lemon, mint, lavender, rosemary, and tonka in a clean aromatic style.', { genderStyle: 'masculine' }],
  ['Parfums de Marly', 'pdm-pegasus-exclusif', 'Pegasus Exclusif', 'amber-spicy', ['sweet', 'woody', 'oriental'], ['almond', 'vanilla', 'sandalwood', 'oud'], ['cardamom', 'almond', 'lavender', 'vanilla', 'oud'], ['almond', 'creamy', 'rich', 'evening', 'luxury'], 'A deeper almond-vanilla Pegasus with cardamom, lavender, woods, and oud.', { genderStyle: 'masculine', projection: 'strong' }],

  ['Yves Saint Laurent', 'ysl-babycat', 'Babycat', 'amber-spicy', ['oriental', 'spicy', 'sweet'], ['vanilla', 'suede', 'pepper', 'resinous'], ['pink pepper', 'black pepper', 'saffron', 'vanilla', 'suede'], ['vanilla-suede', 'spicy', 'cult-favorite', 'warm', 'night'], 'A cult spicy vanilla-suede with pepper, saffron, and resinous warmth.', { priceRange: 'niche', priceDisplay: '$250-$320', projection: 'strong' }],
  ['Yves Saint Laurent', 'ysl-tuxedo', 'Tuxedo', 'amber-spicy', ['spicy', 'woody', 'oriental'], ['patchouli', 'ambergris', 'spicy', 'rose'], ['violet leaf', 'coriander', 'rose', 'patchouli', 'ambergris'], ['tailored', 'evening', 'smooth', 'formal', 'unisex'], 'A tailored patchouli-ambergris evening scent with rose and soft spice.', { priceRange: 'niche', priceDisplay: '$250-$320' }],
  ['Yves Saint Laurent', 'ysl-caban', 'Caban', 'amber-spicy', ['oriental', 'spicy', 'woody'], ['tonka', 'pepper', 'sandalwood', 'amber'], ['pink pepper', 'tonka bean', 'sandalwood', 'labdanum'], ['coat', 'cozy', 'warm', 'elegant', 'cashmere'], 'A warm cashmere-coat scent of tonka, pepper, sandalwood, and labdanum.', { priceRange: 'niche', priceDisplay: '$250-$320' }],
  ['Yves Saint Laurent', 'ysl-caftan', 'Caftan', 'amber-spicy', ['oriental', 'spicy', 'sweet'], ['incense', 'benzoin', 'vanilla', 'resinous'], ['pink pepper', 'incense', 'benzoin', 'labdanum', 'vanilla'], ['resinous', 'golden', 'warm', 'formal', 'opulent'], 'Golden incense, benzoin, labdanum, and vanilla with opulent warmth.', { priceRange: 'niche', priceDisplay: '$250-$320', projection: 'strong' }],
  ['Yves Saint Laurent', 'ysl-saharienne', 'Saharienne', 'citrus-beach', ['citrus', 'fresh', 'clean'], ['neroli', 'citrus', 'white musk', 'green'], ['bergamot', 'mandarin', 'neroli', 'orange blossom', 'white musk'], ['desert-sun', 'citrus', 'white-shirt', 'fresh', 'elegant'], 'A sunlit citrus-neroli scent with orange blossom and clean white musk.', { priceRange: 'niche', priceDisplay: '$250-$320' }],
  ['Yves Saint Laurent', 'ysl-capeline', 'Capeline', 'floral-soft', ['floral', 'clean', 'fresh'], ['lily', 'vanilla', 'musky', 'green'], ['bergamot', 'lily', 'orange blossom', 'vanilla', 'musk'], ['soft-floral', 'hat', 'polished', 'feminine', 'daytime'], 'A polished lily-orange blossom floral with vanilla and clean musk.', { priceRange: 'niche', priceDisplay: '$250-$320', genderStyle: 'feminine' }],

  ['Dior', 'dior-gris-dior', 'Gris Dior', 'floral-bold', ['floral', 'woody', 'spicy'], ['rose', 'patchouli', 'mossy', 'amber'], ['bergamot', 'rose', 'jasmine', 'patchouli', 'moss'], ['grey', 'chypre', 'elegant', 'unisex', 'formal'], 'A refined grey chypre of rose, jasmine, patchouli, moss, and bergamot.', { priceRange: 'niche', priceDisplay: '$165-$330' }],
  ['Dior', 'dior-ambre-nuit', 'Ambre Nuit', 'amber-spicy', ['oriental', 'floral', 'spicy'], ['amber', 'rose', 'spicy', 'citrus'], ['bergamot', 'rose', 'ambergris', 'pink pepper', 'patchouli'], ['amber-rose', 'silky', 'evening', 'elegant', 'warm'], 'A silky amber-rose with bergamot, pepper, ambergris, and quiet luxury warmth.', { priceRange: 'niche', priceDisplay: '$165-$330' }],
  ['Dior', 'dior-bois-dargent', "Bois d'Argent", 'woody-elegant', ['woody', 'clean', 'sweet'], ['iris', 'honey', 'woody', 'powdery'], ['iris', 'myrrh', 'honey', 'woods', 'musk'], ['silver', 'powdery', 'quiet-luxury', 'soft', 'refined'], 'Powdery iris, honey, myrrh, woods, and musk with silver-soft elegance.', { priceRange: 'niche', priceDisplay: '$165-$330' }],
  ['Dior', 'dior-oud-ispahan', 'Oud Ispahan', 'floral-bold', ['oriental', 'floral', 'woody'], ['rose', 'oud', 'incense', 'amber'], ['labdanum', 'rose', 'patchouli', 'sandalwood', 'oud'], ['rose-oud', 'opulent', 'middle-eastern', 'formal', 'strong'], 'A grand rose-oud with labdanum, patchouli, sandalwood, and smoky depth.', { priceRange: 'niche', priceDisplay: '$165-$330', projection: 'strong' }],
  ['Dior', 'dior-lucky', 'Lucky', 'floral-soft', ['floral', 'fresh', 'clean'], ['lily-of-the-valley', 'white floral', 'musky', 'fresh'], ['lily of the valley', 'white flowers', 'musk', 'ozonic notes'], ['lucky-charm', 'delicate', 'fresh', 'spring', 'soft'], 'A delicate lily-of-the-valley charm with white florals and clean musk.', { priceRange: 'niche', priceDisplay: '$165-$330', genderStyle: 'feminine' }],
  ['Dior', 'dior-dioriviera', 'Dioriviera', 'citrus-beach', ['citrus', 'floral', 'fresh'], ['fig', 'rose', 'green', 'solar'], ['fig', 'rose', 'green notes', 'musk'], ['riviera', 'fig', 'summer', 'rose', 'fresh'], 'A sunny Riviera pairing of fig, rose, green notes, and soft musk.', { priceRange: 'niche', priceDisplay: '$165-$330' }],
  ['Dior', 'dior-new-look', 'New Look', 'amber-spicy', ['oriental', 'spicy', 'woody'], ['aldehydic', 'amber', 'incense', 'woody'], ['aldehydes', 'frankincense', 'amber', 'woods'], ['couture', 'incense', 'modern', 'sharp', 'formal'], 'A couture amber-incense with aldehydic brightness and structured woods.', { priceRange: 'niche', priceDisplay: '$165-$330' }],
  ['Dior', 'dior-diorissimo', 'Diorissimo', 'floral-soft', ['floral', 'fresh', 'clean'], ['lily-of-the-valley', 'green', 'white floral', 'fresh'], ['lily of the valley', 'ylang-ylang', 'jasmine', 'civet accord', 'green notes'], ['classic', 'spring', 'delicate', 'vintage', 'fresh'], 'A classic lily-of-the-valley floral with green freshness and vintage grace.', { genderStyle: 'feminine' }],

  ['Xerjoff', 'xerjoff-torino21', 'Torino21', 'fresh-clean', ['fresh', 'citrus', 'clean'], ['mint', 'lemon', 'aromatic', 'green'], ['mint', 'lemon', 'thyme', 'lavender', 'musk'], ['minty', 'fresh', 'summer', 'energetic', 'sporty'], 'A hyper-fresh mint, lemon, thyme, lavender, and musk scent built for summer.'],
  ['Xerjoff', 'xerjoff-torino24', 'Torino24', 'citrus-beach', ['citrus', 'fresh', 'woody'], ['citrus', 'mango', 'woody', 'musky'], ['mandarin', 'mango', 'orange blossom', 'moss', 'musk'], ['bright', 'sporty', 'tropical', 'fresh', 'modern'], 'Bright mandarin, mango, orange blossom, moss, and musk with sporty polish.'],
  ['Xerjoff', 'xerjoff-starlight', 'Starlight', 'amber-spicy', ['spicy', 'sweet', 'oriental'], ['cardamom', 'almond', 'cinnamon', 'amber'], ['bergamot', 'cardamom', 'cinnamon', 'almond', 'amber'], ['spiced', 'cozy', 'holiday', 'luxury', 'warm'], 'A plush cardamom-cinnamon amber with almond sweetness and festive warmth.', { projection: 'strong' }],
  ['Xerjoff', 'xerjoff-lira', 'Lira', 'sweet-gourmand', ['sweet', 'gourmand', 'citrus'], ['caramel', 'blood orange', 'vanilla', 'cinnamon'], ['blood orange', 'lavender', 'cinnamon', 'caramel', 'vanilla'], ['lemon-cake', 'gourmand', 'feminine', 'cozy', 'sweet'], 'A beloved citrus-caramel vanilla gourmand with cinnamon and soft lavender.', { genderStyle: 'feminine' }],
  ['Xerjoff', 'xerjoff-dama-bianca', 'Dama Bianca', 'floral-soft', ['floral', 'sweet', 'clean'], ['vanilla', 'violet', 'powdery', 'musky'], ['lime', 'violet', 'iris', 'malt', 'vanilla'], ['white-dress', 'soft', 'powdery', 'feminine', 'delicate'], 'Soft violet, iris, malt, lime, and vanilla with delicate white-dress sweetness.', { genderStyle: 'feminine' }],
  ['Xerjoff', 'xerjoff-cruz-del-sur-ii', 'Cruz del Sur II', 'fruity-playful', ['sweet', 'gourmand', 'fresh'], ['mango', 'milk', 'tropical', 'creamy'], ['mango', 'pineapple', 'milk', 'dried fruits', 'musk'], ['mango', 'creamy', 'tropical', 'fun', 'summer'], 'Creamy mango, pineapple, milk, dried fruit, and musk with tropical joy.'],
  ['Xerjoff', 'xerjoff-mefisto', 'Mefisto', 'fresh-clean', ['citrus', 'fresh', 'floral'], ['citrus', 'lavender', 'iris', 'musky'], ['grapefruit', 'bergamot', 'lavender', 'iris', 'musk'], ['italian', 'clean', 'classic', 'spring', 'fresh'], 'Classic Italian citrus, lavender, iris, and musk with clean refinement.', { genderStyle: 'masculine' }],
  ['Xerjoff', 'xerjoff-uden', 'Uden', 'citrus-beach', ['citrus', 'woody', 'sweet'], ['citrus', 'rum', 'vanilla', 'woody'], ['lemon', 'grapefruit', 'rum', 'sandalwood', 'vanilla'], ['resort', 'citrus', 'smooth', 'luxury', 'warm'], 'Smooth citrus, rum, sandalwood, and vanilla with luxury resort warmth.'],

  ['Chanel', 'chanel-chance-edp', 'Chance Eau de Parfum', 'floral-soft', ['floral', 'spicy', 'clean'], ['pink pepper', 'jasmine', 'patchouli', 'musky'], ['pink pepper', 'jasmine', 'iris', 'patchouli', 'musk'], ['sparkling', 'pink-pepper', 'polished', 'daily', 'feminine'], 'Sparkling pink pepper, jasmine, patchouli, iris, and musk with polished charm.', { genderStyle: 'feminine' }],
  ['Chanel', 'chanel-chance-eau-vive', 'Chance Eau Vive', 'citrus-beach', ['citrus', 'floral', 'fresh'], ['grapefruit', 'blood orange', 'jasmine', 'musky'], ['grapefruit', 'blood orange', 'jasmine', 'cedar', 'musk'], ['orange', 'bright', 'energetic', 'summer', 'feminine'], 'A bright grapefruit-blood orange Chance with jasmine, cedar, and musk.', { genderStyle: 'feminine' }],
  ['Chanel', 'chanel-cristalle', 'Cristalle', 'green-woody', ['citrus', 'fresh', 'floral'], ['green', 'citrus', 'oakmoss', 'floral'], ['lemon', 'hyacinth', 'honeysuckle', 'oakmoss', 'vetiver'], ['classic', 'green', 'chypre', 'fresh', 'elegant'], 'A crisp green citrus-floral chypre with oakmoss and elegant classic structure.', { genderStyle: 'feminine' }],
  ['Chanel', 'chanel-bois-des-iles', 'Bois des Iles', 'woody-elegant', ['woody', 'oriental', 'floral'], ['sandalwood', 'aldehydic', 'amber', 'powdery'], ['aldehydes', 'ylang-ylang', 'sandalwood', 'benzoin', 'tonka bean'], ['sandalwood', 'classic', 'powdery', 'luxury', 'soft'], 'A classic aldehydic sandalwood with ylang, benzoin, and powdery warmth.'],
  ['Chanel', 'chanel-coromandel', 'Coromandel', 'amber-spicy', ['oriental', 'woody', 'sweet'], ['patchouli', 'amber', 'white chocolate', 'resinous'], ['bitter orange', 'patchouli', 'benzoin', 'white chocolate', 'frankincense'], ['patchouli', 'opulent', 'gold', 'warm', 'formal'], 'A plush patchouli-amber with white chocolate, incense, and golden resin.', { projection: 'strong' }],
  ['Chanel', 'chanel-sycomore', 'Sycomore', 'green-woody', ['woody', 'fresh', 'spicy'], ['vetiver', 'smoky', 'woody', 'earthy'], ['vetiver', 'cypress', 'juniper', 'tobacco', 'sandalwood'], ['vetiver', 'dry', 'elegant', 'tailored', 'minimal'], 'A dry elegant vetiver with cypress, juniper, tobacco, and sandalwood.'],
  ['Chanel', 'chanel-le-lion', 'Le Lion de Chanel', 'amber-spicy', ['oriental', 'spicy', 'woody'], ['amber', 'leather', 'vanilla', 'resinous'], ['bergamot', 'labdanum', 'patchouli', 'vanilla', 'sandalwood'], ['amber', 'leather', 'bold', 'formal', 'luxury'], 'A bold amber-leather Chanel with labdanum, patchouli, vanilla, and sandalwood.', { projection: 'strong' }],
  ['Chanel', 'chanel-beige', 'Beige', 'floral-soft', ['floral', 'sweet', 'clean'], ['honey', 'frangipani', 'white floral', 'musky'], ['hawthorn', 'freesia', 'frangipani', 'honey', 'musk'], ['soft', 'beige', 'polished', 'quiet-luxury', 'feminine'], 'A soft honeyed floral of freesia, frangipani, hawthorn, and musk.', { genderStyle: 'feminine' }],
  ['Chanel', 'chanel-paris-paris', 'Paris-Paris', 'floral-soft', ['floral', 'fresh', 'clean'], ['rose', 'citrus', 'pink pepper', 'musky'], ['damask rose', 'citrus', 'pink pepper', 'patchouli', 'musk'], ['rose', 'daytime', 'sparkling', 'casual-chic', 'fresh'], 'A sparkling casual rose with citrus, pink pepper, patchouli, and musk.', { genderStyle: 'feminine' }],

  ['Diptyque', 'diptyque-eau-papier', 'Eau Papier', 'skin-musk', ['clean', 'woody', 'sweet'], ['rice', 'mimosa', 'musk', 'woody'], ['white musks', 'mimosa', 'rice steam accord', 'blond woods'], ['paper', 'skin', 'soft', 'minimal', 'comforting'], 'A soft paper-skin scent of rice steam, mimosa, white musks, and blond woods.', { projection: 'subtle' }],
  ['Diptyque', 'diptyque-lombre-dans-leau', "L'Ombre dans L'Eau", 'green-woody', ['fresh', 'floral', 'clean'], ['blackcurrant', 'rose', 'green', 'watery'], ['blackcurrant leaf', 'bulgarian rose', 'green notes', 'musk'], ['garden', 'blackcurrant', 'rose', 'green', 'rainy'], 'A green garden of blackcurrant leaves, rose, watery stems, and musk.'],
  ['Diptyque', 'diptyque-tempo', 'Tempo', 'green-woody', ['woody', 'spicy', 'oriental'], ['patchouli', 'cacao', 'violet', 'woody'], ['patchouli', 'violet leaf', 'clary sage', 'cacao', 'mate'], ['patchouli', '70s', 'earthy', 'artistic', 'deep'], 'An artistic patchouli with violet leaf, cacao, sage, and earthy warmth.'],
  ['Diptyque', 'diptyque-eau-rihla', 'Eau Rihla', 'smoky-dark', ['woody', 'spicy', 'oriental'], ['leather', 'saffron', 'raspberry', 'woody'], ['raspberry', 'saffron', 'iris', 'leather', 'cedar'], ['leather', 'journey', 'warm', 'luxury', 'evening'], 'A warm leather journey with raspberry, saffron, iris, and cedar.'],
  ['Diptyque', 'diptyque-eau-nabati', 'Eau Nabati', 'green-woody', ['fresh', 'woody', 'clean'], ['green', 'balsamic', 'bergamot', 'woody'], ['bergamot', 'petitgrain', 'balsam', 'immortelle', 'musk'], ['green', 'botanical', 'sunlit', 'natural', 'fresh'], 'A botanical green scent with bergamot, petitgrain, balsam, immortelle, and musk.'],
  ['Diptyque', 'diptyque-eau-moheli', 'Eau Moheli', 'floral-soft', ['floral', 'spicy', 'woody'], ['ylang-ylang', 'spicy', 'green', 'woody'], ['ylang-ylang', 'pink pepper', 'ginger', 'vetiver', 'patchouli'], ['ylang', 'sunny', 'island', 'spicy-floral', 'warm'], 'Sunlit ylang-ylang with pink pepper, ginger, vetiver, and patchouli.'],
  ['Diptyque', 'diptyque-olene', 'Olene', 'floral-bold', ['floral', 'fresh', 'clean'], ['jasmine', 'wisteria', 'white floral', 'green'], ['wisteria', 'jasmine', 'honeysuckle', 'narcissus', 'green notes'], ['white-floral', 'garden', 'lush', 'romantic', 'spring'], 'A lush white floral garden of jasmine, wisteria, honeysuckle, and narcissus.', { genderStyle: 'feminine' }],
  ['Diptyque', 'diptyque-geranium-odorata', 'Geranium Odorata', 'fresh-clean', ['fresh', 'spicy', 'floral'], ['geranium', 'mint', 'aromatic', 'green'], ['geranium', 'bergamot', 'pink pepper', 'vetiver', 'tonka bean'], ['aromatic', 'green', 'minty', 'fresh', 'tailored'], 'Fresh geranium, minty-green aromatics, pepper, vetiver, and tonka.'],
];

export const catalogCompletion: FragranceSeed[] = entries.map(entry);
