export type ScentFamily = 'fresh' | 'woody' | 'floral' | 'sweet' | 'spicy' | 'clean' | 'gourmand' | 'oriental' | 'citrus' | 'aquatic';
export type Occasion = 'daily' | 'work' | 'date' | 'night' | 'special' | 'casual';
export type GenderStyle = 'masculine' | 'feminine' | 'unisex';
export type Projection = 'subtle' | 'moderate' | 'strong';
export type PriceRange = 'budget' | 'mid' | 'designer' | 'niche';
export type Tier = 'designer' | 'niche';
export type Aesthetic = 'old-money' | 'clean' | 'dark-academia' | 'beach' | 'quiet-luxury' | 'streetwear' | 'romantic';
export type Vibe = 'rainy-castle' | 'sunny-beach' | 'late-night-city' | 'hotel-room' | 'forest-rain' | 'luxury-mall';

export interface Fragrance {
  id: string;
  name: string;
  brand: string;
  priceRange: PriceRange;
  priceDisplay: string;
  scentFamilies: ScentFamily[];
  notes: string[];
  vibes: Vibe[];
  aesthetics: Aesthetic[];
  occasions: Occasion[];
  genderStyle: GenderStyle;
  projection: Projection;
  tier: Tier;
  seasons: string[];
  moods: string[];
  shortDescription: string;
}

export const fragrances: Fragrance[] = [
  {
    id: 'bleu-chanel',
    name: 'Bleu de Chanel',
    brand: 'Chanel',
    priceRange: 'designer',
    priceDisplay: '$120–$200',
    scentFamilies: ['woody', 'fresh', 'citrus'],
    notes: ['grapefruit', 'ginger', 'sandalwood', 'cedar', 'vetiver'],
    vibes: ['luxury-mall', 'late-night-city', 'hotel-room'],
    aesthetics: ['old-money', 'quiet-luxury', 'clean'],
    occasions: ['work', 'date', 'special'],
    genderStyle: 'masculine',
    projection: 'moderate',
    tier: 'designer',
    seasons: ['spring', 'autumn', 'winter'],
    moods: ['confident', 'elegant'],
    shortDescription: 'A modern classic — effortlessly refined for any elevated occasion.',
  },
  {
    id: 'black-orchid',
    name: 'Black Orchid',
    brand: 'Tom Ford',
    priceRange: 'designer',
    priceDisplay: '$150–$250',
    scentFamilies: ['floral', 'oriental', 'spicy'],
    notes: ['black orchid', 'dark chocolate', 'patchouli', 'black truffle', 'vanilla'],
    vibes: ['late-night-city', 'rainy-castle', 'luxury-mall'],
    aesthetics: ['dark-academia', 'romantic', 'old-money'],
    occasions: ['date', 'night', 'special'],
    genderStyle: 'unisex',
    projection: 'strong',
    tier: 'designer',
    seasons: ['autumn', 'winter'],
    moods: ['mysterious', 'elegant'],
    shortDescription: 'Dark, luxurious, and unforgettable — for nights that leave an impression.',
  },
  {
    id: 'libre-ysl',
    name: 'Libre',
    brand: 'Yves Saint Laurent',
    priceRange: 'designer',
    priceDisplay: '$110–$180',
    scentFamilies: ['floral', 'woody', 'sweet'],
    notes: ['lavender', 'orange blossom', 'musk', 'vanilla', 'cedar'],
    vibes: ['luxury-mall', 'late-night-city', 'sunny-beach'],
    aesthetics: ['romantic', 'quiet-luxury', 'clean'],
    occasions: ['date', 'night', 'special', 'work'],
    genderStyle: 'feminine',
    projection: 'moderate',
    tier: 'designer',
    seasons: ['spring', 'summer', 'autumn'],
    moods: ['confident', 'elegant', 'soft'],
    shortDescription: 'Bold and feminine with a free spirit — lavender meets warm vanilla.',
  },
  {
    id: 'sauvage-dior',
    name: 'Sauvage',
    brand: 'Dior',
    priceRange: 'designer',
    priceDisplay: '$100–$180',
    scentFamilies: ['fresh', 'woody', 'spicy'],
    notes: ['bergamot', 'pepper', 'ambroxan', 'vetiver', 'lavender'],
    vibes: ['forest-rain', 'late-night-city', 'hotel-room'],
    aesthetics: ['clean', 'quiet-luxury', 'streetwear'],
    occasions: ['daily', 'work', 'date', 'casual'],
    genderStyle: 'masculine',
    projection: 'strong',
    tier: 'designer',
    seasons: ['spring', 'summer', 'autumn'],
    moods: ['fresh', 'confident'],
    shortDescription: 'Magnetic and crowd-pleasing — a fresh-spicy beast that turns heads.',
  },
  {
    id: 'chance-chanel',
    name: 'Chance Eau Tendre',
    brand: 'Chanel',
    priceRange: 'designer',
    priceDisplay: '$110–$170',
    scentFamilies: ['floral', 'fresh', 'citrus'],
    notes: ['grapefruit', 'quince', 'jasmine', 'white musk', 'cedar'],
    vibes: ['sunny-beach', 'hotel-room', 'luxury-mall'],
    aesthetics: ['clean', 'romantic', 'quiet-luxury'],
    occasions: ['daily', 'work', 'casual', 'date'],
    genderStyle: 'feminine',
    projection: 'moderate',
    tier: 'designer',
    seasons: ['spring', 'summer'],
    moods: ['fresh', 'playful', 'soft'],
    shortDescription: 'Light and joyful — a soft floral breeze perfect for everyday elegance.',
  },
  {
    id: 'aventus-creed',
    name: 'Aventus',
    brand: 'Creed',
    priceRange: 'niche',
    priceDisplay: '$350–$500',
    scentFamilies: ['fresh', 'woody', 'citrus'],
    notes: ['pineapple', 'birch', 'blackcurrant', 'ambergris', 'musk'],
    vibes: ['luxury-mall', 'late-night-city', 'hotel-room'],
    aesthetics: ['old-money', 'quiet-luxury'],
    occasions: ['special', 'work', 'date'],
    genderStyle: 'masculine',
    projection: 'moderate',
    tier: 'niche',
    seasons: ['spring', 'summer', 'autumn'],
    moods: ['confident', 'elegant'],
    shortDescription: 'The benchmark of success — fruity, smoky, and undeniably powerful.',
  },
  {
    id: 'oud-wood-tf',
    name: 'Oud Wood',
    brand: 'Tom Ford',
    priceRange: 'designer',
    priceDisplay: '$250–$380',
    scentFamilies: ['woody', 'spicy', 'oriental'],
    notes: ['oud', 'rosewood', 'sandalwood', 'tonka bean', 'amber'],
    vibes: ['rainy-castle', 'late-night-city', 'luxury-mall'],
    aesthetics: ['old-money', 'dark-academia', 'quiet-luxury'],
    occasions: ['date', 'night', 'special'],
    genderStyle: 'unisex',
    projection: 'moderate',
    tier: 'designer',
    seasons: ['autumn', 'winter'],
    moods: ['mysterious', 'elegant', 'confident'],
    shortDescription: 'Rare, smoky oud balanced with warmth — intimate and deeply sophisticated.',
  },
  {
    id: 'flowerbomb-vf',
    name: 'Flowerbomb',
    brand: 'Viktor & Rolf',
    priceRange: 'designer',
    priceDisplay: '$100–$180',
    scentFamilies: ['floral', 'sweet', 'gourmand'],
    notes: ['rose', 'jasmine', 'freesia', 'patchouli', 'vanilla'],
    vibes: ['luxury-mall', 'rainy-castle', 'hotel-room'],
    aesthetics: ['romantic', 'old-money', 'quiet-luxury'],
    occasions: ['date', 'special', 'night'],
    genderStyle: 'feminine',
    projection: 'strong',
    tier: 'designer',
    seasons: ['autumn', 'winter', 'spring'],
    moods: ['soft', 'elegant', 'playful'],
    shortDescription: 'An explosion of florals wrapped in sweetness — feminine and intoxicating.',
  },
  {
    id: 'silver-mountain-creed',
    name: 'Silver Mountain Water',
    brand: 'Creed',
    priceRange: 'niche',
    priceDisplay: '$280–$420',
    scentFamilies: ['fresh', 'aquatic', 'citrus'],
    notes: ['bergamot', 'green tea', 'sandalwood', 'musk', 'neroli'],
    vibes: ['forest-rain', 'hotel-room', 'sunny-beach'],
    aesthetics: ['clean', 'quiet-luxury', 'old-money'],
    occasions: ['daily', 'work', 'casual'],
    genderStyle: 'unisex',
    projection: 'moderate',
    tier: 'niche',
    seasons: ['spring', 'summer'],
    moods: ['fresh', 'elegant'],
    shortDescription: 'Crisp mountain air in a bottle — clean, airy, and effortlessly refined.',
  },
  {
    id: 'neroli-portofino-tf',
    name: 'Neroli Portofino',
    brand: 'Tom Ford',
    priceRange: 'designer',
    priceDisplay: '$200–$320',
    scentFamilies: ['citrus', 'fresh', 'floral'],
    notes: ['neroli', 'bergamot', 'lemon', 'amber', 'musk'],
    vibes: ['sunny-beach', 'hotel-room', 'luxury-mall'],
    aesthetics: ['beach', 'quiet-luxury', 'clean'],
    occasions: ['daily', 'casual', 'work'],
    genderStyle: 'unisex',
    projection: 'moderate',
    tier: 'designer',
    seasons: ['spring', 'summer'],
    moods: ['fresh', 'playful', 'elegant'],
    shortDescription: 'Mediterranean sunshine — bright citrus and neroli for sun-drenched days.',
  },
  {
    id: 'tobacco-vanille-tf',
    name: 'Tobacco Vanille',
    brand: 'Tom Ford',
    priceRange: 'designer',
    priceDisplay: '$250–$380',
    scentFamilies: ['oriental', 'sweet', 'spicy', 'gourmand'],
    notes: ['tobacco', 'vanilla', 'tonka bean', 'cocoa', 'dried fruits'],
    vibes: ['rainy-castle', 'late-night-city', 'luxury-mall'],
    aesthetics: ['dark-academia', 'old-money', 'romantic'],
    occasions: ['date', 'night', 'special'],
    genderStyle: 'unisex',
    projection: 'strong',
    tier: 'designer',
    seasons: ['autumn', 'winter'],
    moods: ['mysterious', 'elegant', 'confident'],
    shortDescription: 'Rich tobacco and creamy vanilla — cosy, bold, and utterly indulgent.',
  },
  {
    id: 'good-girl-cg',
    name: 'Good Girl',
    brand: 'Carolina Herrera',
    priceRange: 'mid',
    priceDisplay: '$80–$130',
    scentFamilies: ['floral', 'oriental', 'sweet'],
    notes: ['jasmine', 'tuberose', 'cacao', 'sandalwood', 'tonka bean'],
    vibes: ['late-night-city', 'luxury-mall', 'rainy-castle'],
    aesthetics: ['dark-academia', 'romantic', 'streetwear'],
    occasions: ['night', 'date', 'special'],
    genderStyle: 'feminine',
    projection: 'strong',
    tier: 'designer',
    seasons: ['autumn', 'winter'],
    moods: ['mysterious', 'confident', 'playful'],
    shortDescription: 'Duality in a bottle — floral and dark, for the night you want to be remembered.',
  },
  {
    id: 'acqua-armani',
    name: 'Acqua di Giò',
    brand: 'Giorgio Armani',
    priceRange: 'mid',
    priceDisplay: '$60–$110',
    scentFamilies: ['aquatic', 'fresh', 'citrus'],
    notes: ['bergamot', 'neroli', 'rosemary', 'sea water', 'white musk'],
    vibes: ['sunny-beach', 'forest-rain', 'hotel-room'],
    aesthetics: ['beach', 'clean', 'streetwear'],
    occasions: ['daily', 'casual', 'work'],
    genderStyle: 'masculine',
    projection: 'moderate',
    tier: 'designer',
    seasons: ['spring', 'summer'],
    moods: ['fresh', 'playful'],
    shortDescription: 'The ocean in a bottle — fresh, clean, and effortlessly wearable every day.',
  },
  {
    id: 'la-vie-est-belle',
    name: 'La Vie Est Belle',
    brand: 'Lancôme',
    priceRange: 'mid',
    priceDisplay: '$70–$130',
    scentFamilies: ['floral', 'gourmand', 'sweet'],
    notes: ['iris', 'jasmine', 'praline', 'vanilla', 'patchouli'],
    vibes: ['luxury-mall', 'sunny-beach', 'hotel-room'],
    aesthetics: ['romantic', 'clean', 'quiet-luxury'],
    occasions: ['daily', 'date', 'work'],
    genderStyle: 'feminine',
    projection: 'moderate',
    tier: 'designer',
    seasons: ['spring', 'autumn'],
    moods: ['soft', 'playful', 'elegant'],
    shortDescription: "A joyful gourmand — iris and sweet praline for life's beautiful moments.",
  },
  {
    id: 'molecule-01',
    name: 'Molecule 01',
    brand: 'Escentric Molecules',
    priceRange: 'mid',
    priceDisplay: '$60–$100',
    scentFamilies: ['woody', 'clean'],
    notes: ['ISO E Super (cedar molecule)', 'skin musk'],
    vibes: ['hotel-room', 'late-night-city', 'forest-rain'],
    aesthetics: ['clean', 'quiet-luxury', 'streetwear'],
    occasions: ['daily', 'casual', 'work'],
    genderStyle: 'unisex',
    projection: 'subtle',
    tier: 'niche',
    seasons: ['spring', 'summer', 'autumn', 'winter'],
    moods: ['fresh', 'mysterious', 'soft'],
    shortDescription: 'Invisible but magnetic — a skin-melding scent that reacts uniquely to you.',
  },
  {
    id: 'lost-cherry-tf',
    name: 'Lost Cherry',
    brand: 'Tom Ford',
    priceRange: 'designer',
    priceDisplay: '$250–$380',
    scentFamilies: ['sweet', 'spicy', 'oriental'],
    notes: ['cherry', 'bitter almond', 'Turkish rose', 'tonka', 'sandalwood'],
    vibes: ['rainy-castle', 'late-night-city', 'luxury-mall'],
    aesthetics: ['dark-academia', 'romantic', 'old-money'],
    occasions: ['date', 'night', 'special'],
    genderStyle: 'unisex',
    projection: 'strong',
    tier: 'designer',
    seasons: ['autumn', 'winter'],
    moods: ['mysterious', 'playful', 'elegant'],
    shortDescription: 'Intoxicatingly sweet cherry with a dark edge — unapologetically sensual.',
  },
  {
    id: 'santal-33-le-labo',
    name: 'Santal 33',
    brand: 'Le Labo',
    priceRange: 'niche',
    priceDisplay: '$200–$350',
    scentFamilies: ['woody', 'spicy', 'fresh'],
    notes: ['sandalwood', 'cedarwood', 'cardamom', 'violet', 'leather'],
    vibes: ['forest-rain', 'hotel-room', 'late-night-city'],
    aesthetics: ['clean', 'quiet-luxury', 'dark-academia'],
    occasions: ['daily', 'work', 'casual', 'date'],
    genderStyle: 'unisex',
    projection: 'moderate',
    tier: 'niche',
    seasons: ['spring', 'autumn', 'winter'],
    moods: ['confident', 'fresh', 'mysterious'],
    shortDescription: 'The cult minimalist — dry sandalwood and violet that smells like art.',
  },
  {
    id: 'miss-dior-dior',
    name: 'Miss Dior',
    brand: 'Dior',
    priceRange: 'designer',
    priceDisplay: '$100–$170',
    scentFamilies: ['floral', 'fresh', 'clean'],
    notes: ['rose', 'peony', 'white musk', 'sandalwood', 'pink pepper'],
    vibes: ['sunny-beach', 'hotel-room', 'luxury-mall'],
    aesthetics: ['romantic', 'clean', 'quiet-luxury'],
    occasions: ['daily', 'date', 'work'],
    genderStyle: 'feminine',
    projection: 'moderate',
    tier: 'designer',
    seasons: ['spring', 'summer'],
    moods: ['soft', 'playful', 'elegant'],
    shortDescription: 'Delicate and romantic — a rosy freshness that feels like a first love.',
  },
  {
    id: 'rose-oud-bdk',
    name: 'Gris Charnel',
    brand: 'BDK Parfums',
    priceRange: 'niche',
    priceDisplay: '$180–$280',
    scentFamilies: ['floral', 'woody', 'spicy'],
    notes: ['rose', 'sandalwood', 'iris', 'musk', 'bergamot'],
    vibes: ['rainy-castle', 'hotel-room', 'luxury-mall'],
    aesthetics: ['quiet-luxury', 'romantic', 'old-money'],
    occasions: ['date', 'work', 'special'],
    genderStyle: 'unisex',
    projection: 'moderate',
    tier: 'niche',
    seasons: ['autumn', 'winter', 'spring'],
    moods: ['elegant', 'soft', 'mysterious'],
    shortDescription: 'Understated and beautiful — rose and sandalwood with effortless depth.',
  },
  {
    id: 'light-blue-dolce',
    name: 'Light Blue',
    brand: 'Dolce & Gabbana',
    priceRange: 'mid',
    priceDisplay: '$60–$110',
    scentFamilies: ['fresh', 'aquatic', 'citrus'],
    notes: ['Sicilian lemon', 'apple', 'jasmine', 'cedarwood', 'white musk'],
    vibes: ['sunny-beach', 'hotel-room', 'forest-rain'],
    aesthetics: ['beach', 'clean', 'romantic'],
    occasions: ['daily', 'casual', 'date'],
    genderStyle: 'feminine',
    projection: 'subtle',
    tier: 'designer',
    seasons: ['spring', 'summer'],
    moods: ['fresh', 'playful', 'soft'],
    shortDescription: 'Sun-drenched Italian coast — crisp, bright, and endlessly summery.',
  },
  {
    id: 'eros-versace',
    name: 'Eros',
    brand: 'Versace',
    priceRange: 'mid',
    priceDisplay: '$60–$100',
    scentFamilies: ['fresh', 'woody', 'sweet'],
    notes: ['mint', 'green apple', 'tonka bean', 'ambroxan', 'vanilla'],
    vibes: ['late-night-city', 'luxury-mall', 'sunny-beach'],
    aesthetics: ['streetwear', 'romantic', 'clean'],
    occasions: ['date', 'night', 'casual'],
    genderStyle: 'masculine',
    projection: 'strong',
    tier: 'designer',
    seasons: ['spring', 'summer', 'autumn'],
    moods: ['confident', 'playful'],
    shortDescription: 'Bold and youthful — fresh mint and sweet woods that command attention.',
  },
  {
    id: 'si-armani',
    name: 'Sì Passione',
    brand: 'Giorgio Armani',
    priceRange: 'mid',
    priceDisplay: '$80–$130',
    scentFamilies: ['floral', 'sweet', 'fresh'],
    notes: ['blackcurrant', 'rose', 'peony', 'patchouli', 'vanilla'],
    vibes: ['luxury-mall', 'late-night-city', 'hotel-room'],
    aesthetics: ['romantic', 'quiet-luxury', 'old-money'],
    occasions: ['date', 'night', 'special', 'work'],
    genderStyle: 'feminine',
    projection: 'moderate',
    tier: 'designer',
    seasons: ['spring', 'autumn', 'winter'],
    moods: ['elegant', 'soft', 'confident'],
    shortDescription: 'Vibrant passion — blackcurrant and rose with a warm sensual base.',
  },
  {
    id: 'the-one-dolce',
    name: 'The One',
    brand: 'Dolce & Gabbana',
    priceRange: 'mid',
    priceDisplay: '$70–$120',
    scentFamilies: ['oriental', 'woody', 'spicy'],
    notes: ['ginger', 'cardamom', 'cedarwood', 'amber', 'tobacco'],
    vibes: ['late-night-city', 'rainy-castle', 'luxury-mall'],
    aesthetics: ['old-money', 'dark-academia', 'streetwear'],
    occasions: ['date', 'night', 'special'],
    genderStyle: 'masculine',
    projection: 'moderate',
    tier: 'designer',
    seasons: ['autumn', 'winter'],
    moods: ['mysterious', 'confident', 'elegant'],
    shortDescription: 'Warmly seductive — spiced amber and tobacco for memorable evenings.',
  },
  {
    id: 'black-phantom-kilian',
    name: 'Black Phantom',
    brand: 'Kilian',
    priceRange: 'niche',
    priceDisplay: '$250–$400',
    scentFamilies: ['gourmand', 'sweet', 'oriental'],
    notes: ['coffee', 'dark rum', 'caramel', 'black sugar', 'sandalwood'],
    vibes: ['rainy-castle', 'late-night-city', 'luxury-mall'],
    aesthetics: ['dark-academia', 'old-money', 'romantic'],
    occasions: ['date', 'night', 'special'],
    genderStyle: 'unisex',
    projection: 'strong',
    tier: 'niche',
    seasons: ['autumn', 'winter'],
    moods: ['mysterious', 'playful', 'elegant'],
    shortDescription: 'Dark and addictive — rum-soaked coffee and caramel for the bold soul.',
  },
  {
    id: 'versace-bright-crystal',
    name: 'Bright Crystal',
    brand: 'Versace',
    priceRange: 'budget',
    priceDisplay: '$40–$80',
    scentFamilies: ['floral', 'fresh', 'sweet'],
    notes: ['pomegranate', 'peony', 'magnolia', 'amber', 'musk'],
    vibes: ['sunny-beach', 'hotel-room', 'luxury-mall'],
    aesthetics: ['clean', 'romantic', 'quiet-luxury'],
    occasions: ['daily', 'casual', 'work'],
    genderStyle: 'feminine',
    projection: 'subtle',
    tier: 'designer',
    seasons: ['spring', 'summer'],
    moods: ['fresh', 'playful', 'soft'],
    shortDescription: 'Soft and approachable — a bright floral that works every single day.',
  },
];
