import type { FragranceSeed } from './fragrances';

type ProfileFields = 'vibes' | 'aesthetics' | 'occasions' | 'seasons' | 'moods';
export type ProfileName =
  | 'fresh-clean'
  | 'fresh-aquatic'
  | 'citrus-beach'
  | 'floral-soft'
  | 'floral-bold'
  | 'fruity-playful'
  | 'sweet-gourmand'
  | 'amber-spicy'
  | 'woody-elegant'
  | 'green-woody'
  | 'smoky-dark'
  | 'skin-musk';

type Profile = Pick<FragranceSeed, ProfileFields>;
export type ProfiledSeed = Omit<FragranceSeed, ProfileFields> & {
  profile: ProfileName;
} & Partial<Pick<FragranceSeed, ProfileFields>>;

const profiles: Record<ProfileName, Profile> = {
  'fresh-clean': {
    vibes: ['hotel-room', 'forest-rain', 'sunny-beach'],
    aesthetics: ['clean', 'quiet-luxury', 'streetwear'],
    occasions: ['daily', 'work', 'casual'],
    seasons: ['spring', 'summer'],
    moods: ['fresh', 'soft'],
  },
  'fresh-aquatic': {
    vibes: ['sunny-beach', 'forest-rain', 'hotel-room'],
    aesthetics: ['beach', 'clean', 'streetwear'],
    occasions: ['daily', 'work', 'casual'],
    seasons: ['spring', 'summer'],
    moods: ['fresh', 'playful'],
  },
  'citrus-beach': {
    vibes: ['sunny-beach', 'hotel-room', 'luxury-mall'],
    aesthetics: ['beach', 'clean', 'quiet-luxury'],
    occasions: ['daily', 'casual', 'work'],
    seasons: ['spring', 'summer'],
    moods: ['fresh', 'playful', 'elegant'],
  },
  'floral-soft': {
    vibes: ['hotel-room', 'sunny-beach', 'luxury-mall'],
    aesthetics: ['romantic', 'clean', 'quiet-luxury'],
    occasions: ['daily', 'work', 'date'],
    seasons: ['spring', 'summer'],
    moods: ['soft', 'fresh', 'elegant'],
  },
  'floral-bold': {
    vibes: ['luxury-mall', 'late-night-city', 'rainy-castle'],
    aesthetics: ['romantic', 'quiet-luxury', 'old-money'],
    occasions: ['date', 'night', 'special'],
    seasons: ['spring', 'autumn', 'winter'],
    moods: ['confident', 'elegant', 'mysterious'],
  },
  'fruity-playful': {
    vibes: ['sunny-beach', 'late-night-city', 'luxury-mall'],
    aesthetics: ['romantic', 'streetwear', 'clean'],
    occasions: ['daily', 'date', 'casual'],
    seasons: ['spring', 'summer', 'autumn'],
    moods: ['playful', 'soft', 'confident'],
  },
  'sweet-gourmand': {
    vibes: ['late-night-city', 'rainy-castle', 'hotel-room'],
    aesthetics: ['romantic', 'dark-academia', 'streetwear'],
    occasions: ['date', 'night', 'special'],
    seasons: ['autumn', 'winter'],
    moods: ['playful', 'mysterious', 'confident'],
  },
  'amber-spicy': {
    vibes: ['rainy-castle', 'late-night-city', 'luxury-mall'],
    aesthetics: ['old-money', 'dark-academia', 'quiet-luxury'],
    occasions: ['date', 'night', 'special'],
    seasons: ['autumn', 'winter'],
    moods: ['mysterious', 'confident', 'elegant'],
  },
  'woody-elegant': {
    vibes: ['luxury-mall', 'hotel-room', 'late-night-city'],
    aesthetics: ['old-money', 'quiet-luxury', 'clean'],
    occasions: ['work', 'date', 'special'],
    seasons: ['spring', 'autumn', 'winter'],
    moods: ['confident', 'elegant'],
  },
  'green-woody': {
    vibes: ['forest-rain', 'hotel-room', 'rainy-castle'],
    aesthetics: ['clean', 'dark-academia', 'quiet-luxury'],
    occasions: ['daily', 'work', 'casual', 'date'],
    seasons: ['spring', 'summer', 'autumn'],
    moods: ['fresh', 'mysterious', 'confident'],
  },
  'smoky-dark': {
    vibes: ['rainy-castle', 'late-night-city', 'luxury-mall'],
    aesthetics: ['dark-academia', 'old-money', 'romantic'],
    occasions: ['date', 'night', 'special'],
    seasons: ['autumn', 'winter'],
    moods: ['mysterious', 'elegant', 'confident'],
  },
  'skin-musk': {
    vibes: ['hotel-room', 'forest-rain', 'sunny-beach'],
    aesthetics: ['clean', 'quiet-luxury', 'romantic'],
    occasions: ['daily', 'work', 'casual', 'date'],
    seasons: ['spring', 'summer', 'autumn'],
    moods: ['soft', 'fresh', 'mysterious'],
  },
};

export function withProfile({ profile, ...seed }: ProfiledSeed): FragranceSeed {
  return { ...profiles[profile], ...seed };
}

export const catalogExpansion: FragranceSeed[] = [
  withProfile({
    profile: 'woody-elegant',
    id: 'dior-homme-intense',
    name: 'Dior Homme Intense',
    brand: 'Dior',
    priceRange: 'designer',
    priceDisplay: '$120-$180',
    scentFamilies: ['woody', 'floral', 'sweet'],
    accords: ['iris', 'powdery', 'woody', 'amber'],
    notes: ['iris', 'ambrette', 'pear', 'cedar', 'vetiver'],
    vibeTags: ['tailored', 'powdery', 'intimate', 'formal', 'evening'],
    genderStyle: 'masculine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Powdery iris and polished woods with a dressed-up, intimate character.',
  }),
  withProfile({
    profile: 'fresh-clean',
    id: 'ysl-y-edp',
    name: 'Y Eau de Parfum',
    brand: 'Yves Saint Laurent',
    priceRange: 'designer',
    priceDisplay: '$105-$175',
    scentFamilies: ['fresh', 'woody', 'spicy'],
    accords: ['aromatic', 'fresh spicy', 'apple', 'woody'],
    notes: ['apple', 'ginger', 'sage', 'juniper berry', 'cedar'],
    vibeTags: ['compliment', 'versatile', 'blue', 'modern', 'confident'],
    genderStyle: 'masculine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Crisp apple, aromatic herbs, and dark woods in a polished modern signature.',
  }),
  withProfile({
    profile: 'fresh-clean',
    id: 'prada-lhomme',
    name: "Prada L'Homme",
    brand: 'Prada',
    priceRange: 'designer',
    priceDisplay: '$100-$160',
    scentFamilies: ['clean', 'floral', 'woody'],
    accords: ['iris', 'soapy', 'powdery', 'clean musk'],
    notes: ['neroli', 'iris', 'violet', 'amber', 'cedar'],
    vibeTags: ['office', 'clean-shirt', 'minimal', 'safe', 'tailored'],
    genderStyle: 'masculine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Immaculate iris, neroli, and amber that wears like a freshly pressed shirt.',
  }),
  withProfile({
    profile: 'woody-elegant',
    id: 'terre-hermes',
    name: "Terre d'Hermes",
    brand: 'Hermes',
    priceRange: 'designer',
    priceDisplay: '$90-$155',
    scentFamilies: ['citrus', 'woody', 'spicy'],
    accords: ['citrus', 'earthy', 'woody', 'mineral'],
    notes: ['orange', 'grapefruit', 'pepper', 'vetiver', 'cedar'],
    vibeTags: ['earthy', 'mature', 'mineral', 'tailored', 'timeless'],
    genderStyle: 'masculine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Dry orange, pepper, and vetiver with an earthy, quietly authoritative finish.',
  }),
  withProfile({
    profile: 'floral-soft',
    id: 'gucci-bloom',
    name: 'Gucci Bloom',
    brand: 'Gucci',
    priceRange: 'designer',
    priceDisplay: '$100-$170',
    scentFamilies: ['floral', 'clean'],
    accords: ['white floral', 'tuberose', 'jasmine', 'green'],
    notes: ['jasmine', 'tuberose', 'rangoon creeper', 'orris', 'honeysuckle'],
    vibeTags: ['garden', 'creamy-floral', 'romantic', 'feminine', 'spring'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'A lush white-floral garden with creamy tuberose and natural green freshness.',
  }),
  withProfile({
    profile: 'fruity-playful',
    id: 'burberry-her',
    name: 'Burberry Her',
    brand: 'Burberry',
    priceRange: 'designer',
    priceDisplay: '$105-$175',
    scentFamilies: ['sweet', 'floral', 'fresh'],
    accords: ['fruity', 'berry', 'musky', 'sweet'],
    notes: ['strawberry', 'raspberry', 'blackcurrant', 'jasmine', 'musk'],
    vibeTags: ['berry', 'city', 'youthful', 'compliment', 'addictive'],
    genderStyle: 'feminine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Bright berries, airy florals, and soft musk with upbeat city energy.',
  }),
  withProfile({
    profile: 'floral-bold',
    id: 'valentino-donna-born-in-roma',
    name: 'Donna Born in Roma',
    brand: 'Valentino',
    priceRange: 'designer',
    priceDisplay: '$105-$180',
    scentFamilies: ['floral', 'sweet', 'woody'],
    accords: ['vanilla', 'white floral', 'woody', 'fruity'],
    notes: ['blackcurrant', 'jasmine sambac', 'jasmine tea', 'bourbon vanilla', 'cashmeran'],
    vibeTags: ['city-chic', 'vanilla', 'night-out', 'confident', 'modern'],
    genderStyle: 'feminine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Jasmine and bourbon vanilla with a dark, woody city-night edge.',
  }),
  withProfile({
    profile: 'floral-soft',
    id: 'armani-my-way',
    name: 'My Way',
    brand: 'Giorgio Armani',
    priceRange: 'designer',
    priceDisplay: '$105-$175',
    scentFamilies: ['floral', 'sweet', 'citrus'],
    accords: ['white floral', 'tuberose', 'citrus', 'vanilla'],
    notes: ['orange blossom', 'bergamot', 'tuberose', 'jasmine', 'vanilla'],
    vibeTags: ['bright', 'uplifting', 'travel', 'polished', 'romantic'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Radiant orange blossom and tuberose softened by clean vanilla and musk.',
  }),
  withProfile({
    profile: 'floral-soft',
    id: 'mon-guerlain',
    name: 'Mon Guerlain',
    brand: 'Guerlain',
    priceRange: 'designer',
    priceDisplay: '$95-$170',
    scentFamilies: ['floral', 'sweet', 'oriental'],
    accords: ['lavender', 'vanilla', 'powdery', 'amber'],
    notes: ['lavender', 'bergamot', 'jasmine sambac', 'vanilla', 'sandalwood'],
    vibeTags: ['comforting', 'powdery', 'elegant', 'soft', 'signature'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    seasons: ['spring', 'autumn', 'winter'],
    shortDescription: 'Lavender, vanilla, and sandalwood composed into a soft, assured signature.',
  }),
  withProfile({
    profile: 'skin-musk',
    id: 'narciso-rodriguez-for-her',
    name: 'For Her Eau de Toilette',
    brand: 'Narciso Rodriguez',
    priceRange: 'designer',
    priceDisplay: '$85-$145',
    scentFamilies: ['floral', 'clean', 'woody'],
    accords: ['musk', 'powdery', 'floral', 'woody'],
    notes: ['orange blossom', 'osmanthus', 'musk', 'amber', 'vetiver'],
    vibeTags: ['skin-scent', 'intimate', 'minimal', 'soft', 'signature'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Velvety musk, orange blossom, and pale woods with intimate elegance.',
  }),
  withProfile({
    profile: 'fresh-clean',
    id: 'ck-one',
    name: 'CK One',
    brand: 'Calvin Klein',
    priceRange: 'budget',
    priceDisplay: '$30-$70',
    scentFamilies: ['fresh', 'citrus', 'clean'],
    accords: ['citrus', 'green', 'aromatic', 'clean'],
    notes: ['lemon', 'bergamot', 'green tea', 'violet', 'musk'],
    vibeTags: ['90s', 'easy', 'unisex', 'casual', 'affordable'],
    genderStyle: 'unisex',
    projection: 'subtle',
    longevity: 'light',
    tier: 'designer',
    shortDescription: 'A breezy citrus-green classic that remains effortless, casual, and genuinely unisex.',
  }),
  withProfile({
    profile: 'fresh-aquatic',
    id: 'davidoff-cool-water',
    name: 'Cool Water',
    brand: 'Davidoff',
    priceRange: 'budget',
    priceDisplay: '$25-$60',
    scentFamilies: ['aquatic', 'fresh', 'woody'],
    accords: ['marine', 'aromatic', 'green', 'fresh spicy'],
    notes: ['sea water', 'lavender', 'mint', 'sandalwood', 'musk'],
    vibeTags: ['ocean', 'classic', 'sporty', 'affordable', 'fresh'],
    genderStyle: 'masculine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Cool marine air, lavender, and green woods in an enduring affordable classic.',
  }),
  withProfile({
    profile: 'fresh-aquatic',
    id: 'issey-miyake-leau-dissey',
    name: "L'Eau d'Issey",
    brand: 'Issey Miyake',
    priceRange: 'mid',
    priceDisplay: '$60-$115',
    scentFamilies: ['floral', 'aquatic', 'fresh'],
    accords: ['aquatic floral', 'ozonic', 'fresh', 'woody'],
    notes: ['lotus', 'melon', 'freesia', 'lily', 'sandalwood'],
    vibeTags: ['water', 'minimal', '90s', 'airy', 'serene'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Transparent lotus, melon, and woods with a serene water-on-skin effect.',
  }),
  withProfile({
    profile: 'floral-bold',
    id: 'mugler-alien',
    name: 'Alien',
    brand: 'Mugler',
    priceRange: 'mid',
    priceDisplay: '$85-$155',
    scentFamilies: ['floral', 'oriental', 'woody'],
    accords: ['white floral', 'amber', 'woody', 'warm'],
    notes: ['jasmine sambac', 'cashmeran', 'white amber'],
    vibeTags: ['radiant', 'statement', 'otherworldly', 'night', 'strong'],
    genderStyle: 'feminine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'A radiant jasmine and amber statement with unmistakable, room-filling presence.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'mugler-angel',
    name: 'Angel',
    brand: 'Mugler',
    priceRange: 'mid',
    priceDisplay: '$90-$165',
    scentFamilies: ['gourmand', 'sweet', 'oriental'],
    accords: ['patchouli', 'chocolate', 'caramel', 'fruity'],
    notes: ['bergamot', 'red berries', 'honey', 'chocolate', 'patchouli'],
    vibeTags: ['iconic', 'maximalist', 'addictive', 'statement', 'sweet'],
    genderStyle: 'feminine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'A maximalist landmark of chocolate, fruit, honey, and earthy patchouli.',
  }),
  withProfile({
    profile: 'amber-spicy',
    id: 'jpg-le-male-le-parfum',
    name: 'Le Male Le Parfum',
    brand: 'Jean Paul Gaultier',
    priceRange: 'mid',
    priceDisplay: '$90-$145',
    scentFamilies: ['spicy', 'sweet', 'oriental'],
    accords: ['cardamom', 'vanilla', 'lavender', 'amber'],
    notes: ['cardamom', 'lavender', 'iris', 'vanilla', 'oriental woods'],
    vibeTags: ['date-night', 'smooth', 'sweet', 'confident', 'warm'],
    genderStyle: 'masculine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Cardamom, lavender, iris, and vanilla with smooth dressed-up warmth.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'jpg-la-belle',
    name: 'La Belle',
    brand: 'Jean Paul Gaultier',
    priceRange: 'mid',
    priceDisplay: '$90-$150',
    scentFamilies: ['sweet', 'gourmand', 'floral'],
    accords: ['pear', 'vanilla', 'fruity', 'amber'],
    notes: ['pear', 'bergamot', 'vanilla', 'vetiver', 'amber'],
    vibeTags: ['juicy', 'date-night', 'addictive', 'feminine', 'warm'],
    genderStyle: 'feminine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Juicy pear and vanilla with a dark, velvety base made for evenings.',
  }),
  withProfile({
    profile: 'amber-spicy',
    id: 'paco-rabanne-one-million',
    name: '1 Million',
    brand: 'Rabanne',
    priceRange: 'mid',
    priceDisplay: '$80-$135',
    scentFamilies: ['spicy', 'sweet', 'woody'],
    accords: ['warm spicy', 'cinnamon', 'leather', 'amber'],
    notes: ['blood mandarin', 'cinnamon', 'rose', 'leather', 'amber'],
    vibeTags: ['party', 'bold', 'compliment', 'flashy', 'night'],
    genderStyle: 'masculine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Sweet cinnamon, leather, and amber with unapologetic party-night projection.',
  }),
  withProfile({
    profile: 'fruity-playful',
    id: 'chloe-signature',
    name: 'Chloe Eau de Parfum',
    brand: 'Chloe',
    priceRange: 'designer',
    priceDisplay: '$105-$175',
    scentFamilies: ['floral', 'fresh', 'clean'],
    accords: ['rose', 'fresh floral', 'powdery', 'fruity'],
    notes: ['peony', 'lychee', 'rose', 'magnolia', 'cedar'],
    vibeTags: ['rose', 'polished', 'daytime', 'romantic', 'clean'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Fresh rose, peony, and lychee with a polished, airy femininity.',
  }),
  withProfile({
    profile: 'woody-elegant',
    id: 'boss-bottled',
    name: 'Boss Bottled',
    brand: 'Hugo Boss',
    priceRange: 'mid',
    priceDisplay: '$65-$115',
    scentFamilies: ['woody', 'spicy', 'sweet'],
    accords: ['apple', 'cinnamon', 'woody', 'warm spicy'],
    notes: ['apple', 'plum', 'cinnamon', 'mahogany', 'vanilla'],
    vibeTags: ['office', 'classic', 'warm', 'versatile', 'approachable'],
    genderStyle: 'masculine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Apple, cinnamon, and woods in a warm, approachable everyday classic.',
  }),
  withProfile({
    profile: 'skin-musk',
    id: 'le-labo-another-13',
    name: 'Another 13',
    brand: 'Le Labo',
    priceRange: 'niche',
    priceDisplay: '$235-$335',
    scentFamilies: ['clean', 'woody', 'fresh'],
    accords: ['ambroxan', 'musk', 'woody', 'animalic'],
    notes: ['ambroxan', 'jasmine', 'moss', 'ambrette seed', 'iso e super'],
    vibeTags: ['skin-scent', 'minimal', 'unique', 'magnetic', 'editorial'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'A musky ambroxan skin scent that feels clean, strange, and quietly magnetic.',
  }),
  withProfile({
    profile: 'green-woody',
    id: 'diptyque-philosykos',
    name: 'Philosykos',
    brand: 'Diptyque',
    priceRange: 'niche',
    priceDisplay: '$180-$240',
    scentFamilies: ['fresh', 'woody', 'clean'],
    accords: ['fig', 'green', 'woody', 'coconut'],
    notes: ['fig leaf', 'fig fruit', 'fig wood', 'coconut', 'cedar'],
    vibeTags: ['fig-tree', 'mediterranean', 'green', 'artistic', 'summer'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'niche',
    shortDescription: 'An entire fig tree rendered in green leaves, milky fruit, and sun-warmed wood.',
  }),
  withProfile({
    profile: 'citrus-beach',
    id: 'byredo-bal-dafrique',
    name: "Bal d'Afrique",
    brand: 'Byredo',
    priceRange: 'niche',
    priceDisplay: '$225-$320',
    scentFamilies: ['citrus', 'floral', 'woody'],
    accords: ['citrus', 'floral', 'woody', 'aromatic'],
    notes: ['bergamot', 'lemon', 'African marigold', 'violet', 'vetiver'],
    vibeTags: ['radiant', 'artistic', 'golden-hour', 'travel', 'joyful'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'niche',
    shortDescription: 'Radiant citrus, violet, and vetiver with artistic warmth and movement.',
  }),
  withProfile({
    profile: 'green-woody',
    id: 'byredo-gypsy-water',
    name: 'Gypsy Water',
    brand: 'Byredo',
    priceRange: 'niche',
    priceDisplay: '$225-$320',
    scentFamilies: ['woody', 'fresh', 'citrus'],
    accords: ['woody', 'aromatic', 'vanilla', 'fresh spicy'],
    notes: ['bergamot', 'juniper', 'incense', 'pine needle', 'vanilla'],
    vibeTags: ['forest', 'incense', 'airy', 'bohemian', 'soft'],
    genderStyle: 'unisex',
    projection: 'subtle',
    longevity: 'moderate',
    tier: 'niche',
    shortDescription: 'Airy juniper, pine, incense, and vanilla with a soft forest-camp atmosphere.',
  }),
  withProfile({
    profile: 'woody-elegant',
    id: 'byredo-mojave-ghost',
    name: 'Mojave Ghost',
    brand: 'Byredo',
    priceRange: 'niche',
    priceDisplay: '$225-$320',
    scentFamilies: ['woody', 'floral', 'clean'],
    accords: ['woody', 'powdery', 'floral', 'fruity'],
    notes: ['ambrette', 'sapodilla', 'violet', 'sandalwood', 'cedar'],
    vibeTags: ['desert', 'minimal', 'powdery', 'quiet-luxury', 'unique'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'niche',
    shortDescription: 'Soft violet, ambrette, and sandalwood with a pale, modern desert mood.',
  }),
  withProfile({
    profile: 'floral-bold',
    id: 'parfums-de-marly-delina',
    name: 'Delina',
    brand: 'Parfums de Marly',
    priceRange: 'niche',
    priceDisplay: '$250-$390',
    scentFamilies: ['floral', 'fresh', 'sweet'],
    accords: ['rose', 'fruity', 'fresh', 'musky'],
    notes: ['lychee', 'rhubarb', 'Turkish rose', 'peony', 'musk'],
    vibeTags: ['rose', 'luxury', 'compliment', 'feminine', 'radiant'],
    genderStyle: 'feminine',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Tart lychee and rhubarb brighten a plush rose and musk signature.',
  }),
  withProfile({
    profile: 'amber-spicy',
    id: 'parfums-de-marly-layton',
    name: 'Layton',
    brand: 'Parfums de Marly',
    priceRange: 'niche',
    priceDisplay: '$250-$390',
    scentFamilies: ['spicy', 'sweet', 'woody'],
    accords: ['apple', 'vanilla', 'aromatic', 'warm spicy'],
    notes: ['apple', 'lavender', 'geranium', 'vanilla', 'sandalwood'],
    vibeTags: ['compliment', 'luxury', 'date-night', 'versatile', 'addictive'],
    genderStyle: 'masculine',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'A polished apple, lavender, and vanilla crowd-pleaser with niche richness.',
  }),
  withProfile({
    profile: 'green-woody',
    id: 'parfums-de-marly-greenley',
    name: 'Greenley',
    brand: 'Parfums de Marly',
    priceRange: 'niche',
    priceDisplay: '$250-$390',
    scentFamilies: ['fresh', 'woody', 'citrus'],
    accords: ['green apple', 'citrus', 'woody', 'aromatic'],
    notes: ['green apple', 'mandarin', 'petitgrain', 'cedarwood', 'oakmoss'],
    vibeTags: ['green', 'crisp', 'luxury', 'outdoors', 'energetic'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Electric green apple, citrus, and mossy woods with upscale outdoor energy.',
  }),
  withProfile({
    profile: 'amber-spicy',
    id: 'xerjoff-naxos',
    name: 'Naxos',
    brand: 'Xerjoff',
    priceRange: 'niche',
    priceDisplay: '$220-$300',
    scentFamilies: ['sweet', 'spicy', 'oriental'],
    accords: ['honey', 'tobacco', 'lavender', 'warm spicy'],
    notes: ['bergamot', 'lavender', 'honey', 'tobacco leaf', 'vanilla'],
    vibeTags: ['honeyed', 'opulent', 'tobacco', 'statement', 'italian'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Honeyed tobacco, lavender, and citrus with opulent Italian warmth.',
  }),
  withProfile({
    profile: 'fruity-playful',
    id: 'xerjoff-erba-pura',
    name: 'Erba Pura',
    brand: 'Xerjoff',
    priceRange: 'niche',
    priceDisplay: '$220-$300',
    scentFamilies: ['sweet', 'fresh', 'citrus'],
    accords: ['fruity', 'citrus', 'musky', 'sweet'],
    notes: ['Sicilian orange', 'Calabrian bergamot', 'fruits', 'white musk', 'vanilla'],
    vibeTags: ['fruity', 'radiant', 'strong', 'luxury', 'compliment'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'A powerful cloud of bright citrus, saturated fruit, musk, and vanilla.',
  }),
  withProfile({
    profile: 'amber-spicy',
    id: 'nishane-ani',
    name: 'Ani',
    brand: 'Nishane',
    priceRange: 'niche',
    priceDisplay: '$210-$320',
    scentFamilies: ['sweet', 'spicy', 'woody'],
    accords: ['vanilla', 'warm spicy', 'woody', 'citrus'],
    notes: ['bergamot', 'ginger', 'blackcurrant', 'vanilla', 'sandalwood'],
    vibeTags: ['vanilla', 'spicy', 'unique', 'addictive', 'strong'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'A textured spicy vanilla with ginger, green facets, and serious longevity.',
  }),
  withProfile({
    profile: 'fresh-clean',
    id: 'nishane-wulong-cha',
    name: 'Wulong Cha',
    brand: 'Nishane',
    priceRange: 'niche',
    priceDisplay: '$190-$290',
    scentFamilies: ['citrus', 'fresh', 'clean'],
    accords: ['tea', 'citrus', 'green', 'aromatic'],
    notes: ['bergamot', 'orange', 'litsea cubeba', 'oolong tea', 'fig'],
    vibeTags: ['tea', 'spa', 'clean', 'bright', 'unique'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Sparkling citrus and oolong tea with a crisp, luxurious spa-like calm.',
  }),
  withProfile({
    profile: 'citrus-beach',
    id: 'jo-malone-wood-sage-sea-salt',
    name: 'Wood Sage & Sea Salt',
    brand: 'Jo Malone London',
    priceRange: 'niche',
    priceDisplay: '$85-$165',
    scentFamilies: ['fresh', 'woody', 'aquatic'],
    accords: ['salty', 'marine', 'aromatic', 'woody'],
    notes: ['ambrette seed', 'sea salt', 'sage', 'grapefruit', 'red algae'],
    vibeTags: ['coastal', 'windswept', 'minimal', 'skin-scent', 'natural'],
    genderStyle: 'unisex',
    projection: 'subtle',
    longevity: 'light',
    tier: 'niche',
    shortDescription: 'Wind, sea salt, sage, and soft woods in a beautifully understated coastal scent.',
  }),
  withProfile({
    profile: 'floral-soft',
    id: 'jo-malone-english-pear-freesia',
    name: 'English Pear & Freesia',
    brand: 'Jo Malone London',
    priceRange: 'niche',
    priceDisplay: '$85-$165',
    scentFamilies: ['floral', 'fresh', 'sweet'],
    accords: ['fruity', 'floral', 'fresh', 'woody'],
    notes: ['pear', 'melon', 'freesia', 'rose', 'patchouli'],
    vibeTags: ['pear', 'garden', 'polished', 'daytime', 'soft'],
    genderStyle: 'feminine',
    projection: 'subtle',
    longevity: 'light',
    tier: 'niche',
    shortDescription: 'Juicy pear and airy freesia with a polished English-garden ease.',
  }),
  withProfile({
    profile: 'skin-musk',
    id: 'le-labo-the-matcha-26',
    name: 'The Matcha 26',
    brand: 'Le Labo',
    priceRange: 'niche',
    priceDisplay: '$235-$335',
    scentFamilies: ['woody', 'clean', 'fresh'],
    accords: ['green tea', 'fig', 'woody', 'soft'],
    notes: ['matcha tea', 'fig', 'bitter orange', 'cedar', 'vetiver'],
    vibeTags: ['tea', 'intimate', 'meditative', 'minimal', 'skin-scent'],
    genderStyle: 'unisex',
    projection: 'subtle',
    longevity: 'moderate',
    tier: 'niche',
    shortDescription: 'Creamy matcha, fig, and soft woods designed as a private moment on skin.',
  }),
  withProfile({
    profile: 'floral-soft',
    id: 'mfk-gentle-fluidity-gold',
    name: 'Gentle Fluidity Gold',
    brand: 'Maison Francis Kurkdjian',
    priceRange: 'niche',
    priceDisplay: '$245-$335',
    scentFamilies: ['sweet', 'spicy', 'clean'],
    accords: ['vanilla', 'musky', 'powdery', 'amber'],
    notes: ['juniper berries', 'nutmeg', 'coriander', 'vanilla', 'musk'],
    vibeTags: ['golden', 'expensive', 'soft', 'vanilla', 'quiet-luxury'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
    seasons: ['spring', 'autumn', 'winter'],
    shortDescription: 'A polished musky vanilla with aromatic spice and a soft golden glow.',
  }),
  withProfile({
    profile: 'fruity-playful',
    id: 'ariana-grande-cloud',
    name: 'Cloud',
    brand: 'Ariana Grande',
    priceRange: 'budget',
    priceDisplay: '$45-$70',
    scentFamilies: ['sweet', 'gourmand', 'clean'],
    accords: ['coconut', 'vanilla', 'lactonic', 'musky'],
    notes: ['lavender', 'pear', 'coconut', 'praline', 'musk'],
    vibeTags: ['affordable', 'fluffy', 'compliment', 'sweet', 'cozy'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Fluffy coconut, praline, lavender, and musk with an airy sweet finish.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'billie-eilish-eilish',
    name: 'Eilish',
    brand: 'Billie Eilish',
    priceRange: 'budget',
    priceDisplay: '$48-$72',
    scentFamilies: ['sweet', 'gourmand', 'oriental'],
    accords: ['vanilla', 'cacao', 'warm spicy', 'amber'],
    notes: ['red berries', 'mandarin', 'vanilla', 'cacao', 'tonka bean'],
    vibeTags: ['affordable', 'cozy', 'vanilla', 'warm-embrace', 'night'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Warm vanilla, cacao, berries, and tonka with a comforting amber glow.',
  }),
  withProfile({
    profile: 'fruity-playful',
    id: 'ariana-grande-sweet-like-candy',
    name: 'Sweet Like Candy',
    brand: 'Ariana Grande',
    priceRange: 'budget',
    priceDisplay: '$40-$65',
    scentFamilies: ['sweet', 'gourmand', 'floral'],
    accords: ['fruity', 'vanilla', 'powdery', 'sweet'],
    notes: ['blackberry', 'pear', 'jasmine', 'marshmallow', 'vanilla'],
    vibeTags: ['affordable', 'playful', 'marshmallow', 'youthful', 'fruity'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Blackberry, pear, marshmallow, and vanilla in a playful soft-focus gourmand.',
  }),
  withProfile({
    profile: 'fruity-playful',
    id: 'britney-spears-fantasy',
    name: 'Fantasy',
    brand: 'Britney Spears',
    priceRange: 'budget',
    priceDisplay: '$25-$45',
    scentFamilies: ['gourmand', 'sweet', 'floral'],
    accords: ['fruity', 'sweet', 'vanilla', 'tropical'],
    notes: ['kiwi', 'lychee', 'white chocolate', 'cupcake', 'musk'],
    vibeTags: ['affordable', 'nostalgic', 'cupcake', 'playful', 'sweet'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Kiwi, lychee, white chocolate, and cupcake in a joyful nostalgic gourmand.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'lattafa-khamrah',
    name: 'Khamrah',
    brand: 'Lattafa',
    priceRange: 'budget',
    priceDisplay: '$35-$60',
    scentFamilies: ['gourmand', 'sweet', 'spicy'],
    accords: ['cinnamon', 'vanilla', 'amber', 'warm spicy'],
    notes: ['cinnamon', 'nutmeg', 'dates', 'praline', 'vanilla'],
    vibeTags: ['affordable', 'addictive', 'dates', 'winter', 'strong'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Dense cinnamon, dates, praline, and vanilla with exceptional budget performance.',
  }),
  withProfile({
    profile: 'fruity-playful',
    id: 'lattafa-yara',
    name: 'Yara',
    brand: 'Lattafa',
    priceRange: 'budget',
    priceDisplay: '$25-$45',
    scentFamilies: ['sweet', 'floral', 'gourmand'],
    accords: ['tropical', 'vanilla', 'powdery', 'fruity'],
    notes: ['orchid', 'heliotrope', 'tangerine', 'tropical fruits', 'vanilla'],
    vibeTags: ['affordable', 'creamy', 'tropical', 'soft', 'playful'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Creamy tropical fruit, orchid, and vanilla with a soft powdery finish.',
  }),
  withProfile({
    profile: 'amber-spicy',
    id: 'lattafa-asad',
    name: 'Asad',
    brand: 'Lattafa',
    priceRange: 'budget',
    priceDisplay: '$25-$45',
    scentFamilies: ['spicy', 'oriental', 'woody'],
    accords: ['warm spicy', 'amber', 'vanilla', 'woody'],
    notes: ['black pepper', 'pineapple', 'tobacco', 'coffee', 'vanilla'],
    vibeTags: ['affordable', 'bold', 'dark', 'night', 'strong'],
    genderStyle: 'masculine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    isDupe: true,
    inspiredBy: 'Dior Sauvage Elixir',
    dupeOf: 'Sauvage Elixir',
    similarityNotes: 'A sweeter, more vanilla-forward aromatic-spicy alternative with powerful projection.',
    shortDescription: 'A clearly labeled inspired-by option with pepper, tobacco, coffee, and vanilla.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'afnan-9pm',
    name: '9PM',
    brand: 'Afnan',
    priceRange: 'budget',
    priceDisplay: '$30-$55',
    scentFamilies: ['sweet', 'spicy', 'fresh'],
    accords: ['vanilla', 'fruity', 'amber', 'aromatic'],
    notes: ['apple', 'cinnamon', 'lavender', 'orange blossom', 'vanilla'],
    vibeTags: ['affordable', 'party', 'compliment', 'sweet', 'strong'],
    genderStyle: 'masculine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    isDupe: true,
    inspiredBy: 'Ultra Male',
    dupeOf: 'Ultra Male',
    similarityNotes: 'A more affordable sweet apple, lavender, and vanilla alternative for nights out.',
    shortDescription: 'A high-performing inspired-by party scent built around apple and vanilla.',
  }),
  withProfile({
    profile: 'woody-elegant',
    id: 'armaf-club-de-nuit-intense-man',
    name: 'Club de Nuit Intense Man',
    brand: 'Armaf',
    priceRange: 'budget',
    priceDisplay: '$30-$55',
    scentFamilies: ['fresh', 'woody', 'citrus'],
    accords: ['citrus', 'smoky', 'fruity', 'woody'],
    notes: ['lemon', 'pineapple', 'birch', 'jasmine', 'musk'],
    vibeTags: ['affordable', 'smoky', 'compliment', 'confident', 'strong'],
    genderStyle: 'masculine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    isDupe: true,
    inspiredBy: 'Aventus',
    dupeOf: 'Aventus',
    similarityNotes: 'A sharper citrus and smokier birch interpretation at a much lower price.',
    shortDescription: 'A famous inspired-by alternative with forceful citrus, pineapple, and smoky woods.',
  }),
  withProfile({
    profile: 'fruity-playful',
    id: 'al-haramain-amber-oud-gold',
    name: 'Amber Oud Gold Edition',
    brand: 'Al Haramain',
    priceRange: 'budget',
    priceDisplay: '$45-$75',
    scentFamilies: ['sweet', 'fresh', 'clean'],
    accords: ['fruity', 'musky', 'sweet', 'fresh'],
    notes: ['bergamot', 'melon', 'pineapple', 'amber', 'vanilla'],
    vibeTags: ['affordable', 'fruity', 'strong', 'compliment', 'radiant'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    isDupe: true,
    inspiredBy: 'Erba Pura',
    dupeOf: 'Erba Pura',
    similarityNotes: 'A sweeter affordable alternative with a similarly saturated fruit-and-musk profile.',
    shortDescription: 'A high-impact inspired-by fruit, musk, amber, and vanilla alternative.',
  }),
  withProfile({
    profile: 'floral-bold',
    id: 'zara-red-temptation',
    name: 'Red Temptation',
    brand: 'Zara',
    priceRange: 'budget',
    priceDisplay: '$30-$50',
    scentFamilies: ['oriental', 'sweet', 'woody'],
    accords: ['amber', 'saffron', 'woody', 'musky'],
    notes: ['saffron', 'bitter orange', 'jasmine', 'praline', 'amber'],
    vibeTags: ['affordable', 'radiant', 'amber', 'night', 'compliment'],
    genderStyle: 'feminine',
    projection: 'strong',
    longevity: 'moderate',
    tier: 'designer',
    isDupe: true,
    inspiredBy: 'Baccarat Rouge 540',
    dupeOf: 'Baccarat Rouge 540',
    similarityNotes: 'A sweeter, more direct saffron-amber alternative at a high-street price.',
    shortDescription: 'A clearly labeled affordable alternative with saffron, amber, and praline warmth.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'zara-gardenia',
    name: 'Gardenia',
    brand: 'Zara',
    priceRange: 'budget',
    priceDisplay: '$25-$45',
    scentFamilies: ['floral', 'sweet', 'gourmand'],
    accords: ['white floral', 'coffee', 'vanilla', 'fruity'],
    notes: ['orange blossom', 'coffee', 'peach', 'raspberry', 'vanilla'],
    vibeTags: ['affordable', 'coffee', 'night', 'sweet', 'feminine'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    isDupe: true,
    inspiredBy: 'Black Opium',
    dupeOf: 'Black Opium',
    similarityNotes: 'A lighter, fruitier coffee-and-vanilla alternative for a fraction of the price.',
    shortDescription: 'An affordable inspired-by coffee, orange blossom, fruit, and vanilla scent.',
  }),
  withProfile({
    profile: 'fresh-clean',
    id: 'montblanc-explorer',
    name: 'Explorer',
    brand: 'Montblanc',
    priceRange: 'mid',
    priceDisplay: '$55-$105',
    scentFamilies: ['woody', 'fresh', 'citrus'],
    accords: ['woody', 'citrus', 'leather', 'aromatic'],
    notes: ['bergamot', 'pink pepper', 'clary sage', 'leather', 'vetiver'],
    vibeTags: ['versatile', 'travel', 'office', 'confident', 'approachable'],
    genderStyle: 'masculine',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Bergamot, aromatic herbs, leather, and vetiver in an easy modern woody scent.',
  }),
  withProfile({
    profile: 'fresh-clean',
    id: 'glossier-you',
    name: 'Glossier You',
    brand: 'Glossier',
    priceRange: 'mid',
    priceDisplay: '$78-$112',
    scentFamilies: ['clean', 'floral', 'woody'],
    accords: ['musky', 'powdery', 'iris', 'peppery'],
    notes: ['pink pepper', 'iris', 'ambrette', 'ambrox'],
    vibeTags: ['skin-scent', 'minimal', 'everyday', 'intimate', 'clean'],
    genderStyle: 'unisex',
    projection: 'subtle',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Peppery iris, ambrette, and ambrox designed to merge with the wearer.',
  }),
  withProfile({
    profile: 'fresh-clean',
    id: 'clean-reserve-skin',
    name: 'Reserve Skin',
    brand: 'Clean Reserve',
    priceRange: 'mid',
    priceDisplay: '$75-$110',
    scentFamilies: ['clean', 'sweet', 'woody'],
    accords: ['musky', 'salty', 'vanilla', 'soft'],
    notes: ['praline', 'salt', 'tonka bean', 'musk', 'leather'],
    vibeTags: ['skin-scent', 'comforting', 'intimate', 'soft', 'safe'],
    genderStyle: 'unisex',
    projection: 'subtle',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Salty praline, musk, and tonka with a warm, soft-focus skin effect.',
  }),
  withProfile({
    profile: 'floral-bold',
    id: 'chanel-coco-mademoiselle',
    name: 'Coco Mademoiselle',
    brand: 'Chanel',
    priceRange: 'designer',
    priceDisplay: '$115-$210',
    scentFamilies: ['citrus', 'floral', 'woody'],
    accords: ['citrus', 'patchouli', 'rose', 'woody'],
    notes: ['orange', 'bergamot', 'rose', 'jasmine', 'patchouli'],
    vibeTags: ['polished', 'classic', 'confident', 'signature', 'elegant'],
    genderStyle: 'feminine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Sparkling citrus, rose, and patchouli in a polished modern classic.',
  }),
  withProfile({
    profile: 'floral-bold',
    id: 'chanel-no-5',
    name: 'N°5 Eau de Parfum',
    brand: 'Chanel',
    priceRange: 'designer',
    priceDisplay: '$115-$210',
    scentFamilies: ['floral', 'clean', 'woody'],
    accords: ['aldehydic', 'powdery', 'floral', 'woody'],
    notes: ['aldehydes', 'ylang-ylang', 'jasmine', 'rose', 'sandalwood'],
    vibeTags: ['iconic', 'powdery', 'formal', 'timeless', 'old-money'],
    genderStyle: 'feminine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Aldehydes, luminous florals, and sandalwood in an unmistakable icon.',
  }),
  withProfile({
    profile: 'floral-bold',
    id: 'dior-jadore',
    name: "J'adore Eau de Parfum",
    brand: 'Dior',
    priceRange: 'designer',
    priceDisplay: '$110-$205',
    scentFamilies: ['floral', 'fresh', 'sweet'],
    accords: ['white floral', 'fruity', 'fresh', 'floral'],
    notes: ['pear', 'melon', 'magnolia', 'jasmine', 'tuberose'],
    vibeTags: ['golden', 'formal', 'radiant', 'feminine', 'luxury'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'A radiant bouquet of jasmine, magnolia, pear, and luminous white flowers.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'ysl-black-opium',
    name: 'Black Opium',
    brand: 'Yves Saint Laurent',
    priceRange: 'designer',
    priceDisplay: '$105-$180',
    scentFamilies: ['gourmand', 'sweet', 'floral'],
    accords: ['coffee', 'vanilla', 'white floral', 'warm spicy'],
    notes: ['pear', 'pink pepper', 'coffee', 'jasmine', 'vanilla'],
    vibeTags: ['coffee', 'night-out', 'addictive', 'compliment', 'bold'],
    genderStyle: 'feminine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Coffee, vanilla, pear, and jasmine with glossy after-dark energy.',
  }),
  withProfile({
    profile: 'floral-soft',
    id: 'prada-paradoxe',
    name: 'Paradoxe',
    brand: 'Prada',
    priceRange: 'designer',
    priceDisplay: '$105-$180',
    scentFamilies: ['floral', 'sweet', 'clean'],
    accords: ['white floral', 'amber', 'citrus', 'musky'],
    notes: ['pear', 'tangerine', 'orange blossom', 'jasmine', 'amber'],
    vibeTags: ['modern', 'clean', 'compliment', 'radiant', 'polished'],
    genderStyle: 'feminine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Bright orange blossom, pear, amber, and musk with sleek modern polish.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'dolce-gabbana-devotion',
    name: 'Devotion',
    brand: 'Dolce & Gabbana',
    priceRange: 'designer',
    priceDisplay: '$95-$165',
    scentFamilies: ['gourmand', 'sweet', 'citrus'],
    accords: ['vanilla', 'citrus', 'sweet', 'white floral'],
    notes: ['candied lemon', 'orange blossom', 'panacotta', 'vanilla', 'rum'],
    vibeTags: ['lemon-cake', 'comforting', 'romantic', 'golden', 'addictive'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Candied lemon, orange blossom, and vanilla with an elegant dessert warmth.',
  }),
  withProfile({
    profile: 'floral-soft',
    id: 'lancome-idole',
    name: 'Idôle',
    brand: 'Lancôme',
    priceRange: 'designer',
    priceDisplay: '$90-$155',
    scentFamilies: ['floral', 'fresh', 'clean'],
    accords: ['rose', 'fruity', 'musky', 'fresh'],
    notes: ['pear', 'bergamot', 'rose', 'jasmine', 'white musk'],
    vibeTags: ['clean', 'rose', 'uplifting', 'everyday', 'modern'],
    genderStyle: 'feminine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Fresh rose, pear, jasmine, and clean musk for a bright everyday signature.',
  }),
  withProfile({
    profile: 'amber-spicy',
    id: 'viktor-rolf-spicebomb-extreme',
    name: 'Spicebomb Extreme',
    brand: 'Viktor & Rolf',
    priceRange: 'designer',
    priceDisplay: '$110-$155',
    scentFamilies: ['spicy', 'sweet', 'oriental'],
    accords: ['warm spicy', 'tobacco', 'vanilla', 'aromatic'],
    notes: ['black pepper', 'caraway', 'lavender', 'tobacco', 'vanilla'],
    vibeTags: ['winter', 'bold', 'date-night', 'warm', 'strong'],
    genderStyle: 'masculine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Dense pepper, tobacco, lavender, and vanilla built for cold nights.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'armani-stronger-with-you-intensely',
    name: 'Stronger With You Intensely',
    brand: 'Giorgio Armani',
    priceRange: 'designer',
    priceDisplay: '$105-$145',
    scentFamilies: ['sweet', 'spicy', 'gourmand'],
    accords: ['vanilla', 'cinnamon', 'amber', 'toffee'],
    notes: ['pink pepper', 'juniper', 'cinnamon', 'toffee', 'vanilla'],
    vibeTags: ['date-night', 'sweet', 'cozy', 'compliment', 'winter'],
    genderStyle: 'masculine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Cinnamon, toffee, vanilla, and amber with enveloping date-night sweetness.',
  }),
  withProfile({
    profile: 'amber-spicy',
    id: 'valentino-uomo-born-in-roma-intense',
    name: 'Uomo Born in Roma Intense',
    brand: 'Valentino',
    priceRange: 'designer',
    priceDisplay: '$105-$155',
    scentFamilies: ['sweet', 'spicy', 'woody'],
    accords: ['vanilla', 'lavender', 'amber', 'woody'],
    notes: ['vanilla', 'lavender', 'vetiver', 'amber', 'ginger'],
    vibeTags: ['city-night', 'smooth', 'compliment', 'confident', 'warm'],
    genderStyle: 'masculine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Vanilla, lavender, and vetiver with a smooth, assertive city-night profile.',
  }),
  withProfile({
    profile: 'amber-spicy',
    id: 'givenchy-gentleman-reserve-privee',
    name: 'Gentleman Réserve Privée',
    brand: 'Givenchy',
    priceRange: 'designer',
    priceDisplay: '$105-$155',
    scentFamilies: ['woody', 'spicy', 'sweet'],
    accords: ['whiskey', 'iris', 'woody', 'amber'],
    notes: ['bergamot', 'whiskey', 'chestnut', 'iris', 'amber'],
    vibeTags: ['whiskey', 'tailored', 'intimate', 'evening', 'elegant'],
    genderStyle: 'masculine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Whiskey, chestnut, iris, and amber with a tailored evening softness.',
  }),
  withProfile({
    profile: 'fresh-aquatic',
    id: 'acqua-di-gio-profondo',
    name: 'Acqua di Giò Profondo',
    brand: 'Giorgio Armani',
    priceRange: 'designer',
    priceDisplay: '$105-$165',
    scentFamilies: ['aquatic', 'fresh', 'citrus'],
    accords: ['marine', 'aromatic', 'citrus', 'mineral'],
    notes: ['sea notes', 'bergamot', 'green mandarin', 'rosemary', 'musk'],
    vibeTags: ['deep-ocean', 'clean', 'versatile', 'summer', 'confident'],
    genderStyle: 'masculine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Deep marine notes, citrus, herbs, and mineral musk with polished freshness.',
  }),
  withProfile({
    profile: 'fresh-clean',
    id: 'versace-dylan-blue',
    name: 'Dylan Blue',
    brand: 'Versace',
    priceRange: 'mid',
    priceDisplay: '$65-$110',
    scentFamilies: ['fresh', 'woody', 'spicy'],
    accords: ['aromatic', 'fresh spicy', 'aquatic', 'woody'],
    notes: ['bergamot', 'grapefruit', 'fig leaf', 'ambroxan', 'incense'],
    vibeTags: ['blue', 'versatile', 'compliment', 'everyday', 'confident'],
    genderStyle: 'masculine',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'A versatile blue aromatic with citrus, ambroxan, woods, and incense.',
  }),
  withProfile({
    profile: 'floral-bold',
    id: 'amouage-guidance',
    name: 'Guidance',
    brand: 'Amouage',
    priceRange: 'niche',
    priceDisplay: '$300-$395',
    scentFamilies: ['floral', 'sweet', 'woody'],
    accords: ['fruity', 'floral', 'amber', 'woody'],
    notes: ['pear', 'hazelnut', 'saffron', 'rose', 'sandalwood'],
    vibeTags: ['opulent', 'unique', 'statement', 'expensive', 'strong'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Pear, hazelnut, rose, saffron, and sandalwood in a lavish modern statement.',
  }),
  withProfile({
    profile: 'woody-elegant',
    id: 'amouage-reflection-man',
    name: 'Reflection Man',
    brand: 'Amouage',
    priceRange: 'niche',
    priceDisplay: '$280-$380',
    scentFamilies: ['floral', 'woody', 'fresh'],
    accords: ['white floral', 'woody', 'aromatic', 'powdery'],
    notes: ['rosemary', 'neroli', 'jasmine', 'orris', 'sandalwood'],
    vibeTags: ['formal', 'clean', 'luxury', 'tailored', 'serene'],
    genderStyle: 'masculine',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Neroli, jasmine, orris, and sandalwood with immaculate formal elegance.',
  }),
  withProfile({
    profile: 'smoky-dark',
    id: 'initio-side-effect',
    name: 'Side Effect',
    brand: 'Initio Parfums Privés',
    priceRange: 'niche',
    priceDisplay: '$270-$390',
    scentFamilies: ['sweet', 'spicy', 'oriental'],
    accords: ['rum', 'tobacco', 'vanilla', 'warm spicy'],
    notes: ['rum', 'tobacco', 'cinnamon', 'saffron', 'vanilla'],
    vibeTags: ['addictive', 'intimate', 'night', 'bold', 'statement'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Rum, tobacco, cinnamon, and vanilla with dark, magnetic intensity.',
  }),
  withProfile({
    profile: 'skin-musk',
    id: 'initio-musk-therapy',
    name: 'Musk Therapy',
    brand: 'Initio Parfums Privés',
    priceRange: 'niche',
    priceDisplay: '$270-$390',
    scentFamilies: ['clean', 'fresh', 'floral'],
    accords: ['musky', 'citrus', 'fruity', 'powdery'],
    notes: ['bergamot', 'mandarin', 'blackcurrant', 'white musk', 'sandalwood'],
    vibeTags: ['clean', 'expensive', 'spa', 'soft', 'uplifting'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Citrus, blackcurrant, white musk, and sandalwood with plush clean serenity.',
  }),
  withProfile({
    profile: 'citrus-beach',
    id: 'mancera-cedrat-boise',
    name: 'Cedrat Boise',
    brand: 'Mancera',
    priceRange: 'niche',
    priceDisplay: '$110-$190',
    scentFamilies: ['citrus', 'woody', 'fresh'],
    accords: ['citrus', 'fruity', 'woody', 'leather'],
    notes: ['Sicilian citrus', 'blackcurrant', 'cedar', 'leather', 'vanilla'],
    vibeTags: ['versatile', 'fruity-woods', 'compliment', 'confident', 'strong'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Bright citrus and blackcurrant over cedar, leather, and soft vanilla.',
  }),
  withProfile({
    profile: 'floral-bold',
    id: 'mancera-instant-crush',
    name: 'Instant Crush',
    brand: 'Mancera',
    priceRange: 'niche',
    priceDisplay: '$110-$190',
    scentFamilies: ['oriental', 'sweet', 'woody'],
    accords: ['amber', 'saffron', 'vanilla', 'woody'],
    notes: ['saffron', 'ginger', 'rose', 'amberwood', 'vanilla'],
    vibeTags: ['radiant', 'strong', 'compliment', 'warm', 'statement'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Saffron, ginger, rose, amberwood, and vanilla with radiant projection.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'montale-intense-cafe',
    name: 'Intense Café',
    brand: 'Montale',
    priceRange: 'niche',
    priceDisplay: '$105-$180',
    scentFamilies: ['gourmand', 'sweet', 'floral'],
    accords: ['coffee', 'rose', 'vanilla', 'amber'],
    notes: ['floral notes', 'rose', 'coffee', 'vanilla', 'white musk'],
    vibeTags: ['coffee', 'rose', 'addictive', 'cozy', 'strong'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Sweet coffee, rose, vanilla, and musk with dense cafe warmth.',
  }),
  withProfile({
    profile: 'skin-musk',
    id: 'juliette-has-a-gun-not-a-perfume',
    name: 'Not a Perfume',
    brand: 'Juliette Has a Gun',
    priceRange: 'niche',
    priceDisplay: '$105-$150',
    scentFamilies: ['clean', 'woody', 'fresh'],
    accords: ['ambery', 'musky', 'woody', 'skin scent'],
    notes: ['cetalox'],
    vibeTags: ['minimal', 'skin-scent', 'clean', 'safe', 'layering'],
    genderStyle: 'unisex',
    projection: 'subtle',
    longevity: 'moderate',
    tier: 'niche',
    shortDescription: 'A single clean ambery molecule that wears differently on every skin.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'kayali-vanilla-28',
    name: 'Vanilla | 28',
    brand: 'Kayali',
    priceRange: 'mid',
    priceDisplay: '$100-$138',
    scentFamilies: ['gourmand', 'sweet', 'oriental'],
    accords: ['vanilla', 'brown sugar', 'amber', 'warm spicy'],
    notes: ['vanilla orchid', 'jasmine', 'brown sugar', 'tonka bean', 'amber'],
    vibeTags: ['layering', 'vanilla', 'addictive', 'warm', 'date-night'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    shortDescription: 'Brown sugar, vanilla orchid, tonka, and amber with rich layering warmth.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'kayali-yum-pistachio-gelato',
    name: 'Yum Pistachio Gelato | 33',
    brand: 'Kayali',
    priceRange: 'mid',
    priceDisplay: '$100-$138',
    scentFamilies: ['gourmand', 'sweet', 'floral'],
    accords: ['pistachio', 'sweet', 'powdery', 'nutty'],
    notes: ['pistachio', 'hazelnut', 'rum', 'marshmallow', 'whipped cream'],
    vibeTags: ['pistachio', 'playful', 'creamy', 'dessert', 'soft'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Pistachio, hazelnut, marshmallow, and whipped cream with playful softness.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'commodity-milk-expressive',
    name: 'Milk Expressive',
    brand: 'Commodity',
    priceRange: 'mid',
    priceDisplay: '$145-$155',
    scentFamilies: ['gourmand', 'sweet', 'woody'],
    accords: ['lactonic', 'woody', 'amber', 'sweet'],
    notes: ['cold milk', 'marshmallow', 'mahogany', 'tonka bean', 'benzoin'],
    vibeTags: ['lactonic', 'comforting', 'fireside', 'soft', 'cozy'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'niche',
    shortDescription: 'Cold milk, marshmallow, mahogany, and tonka with fireside comfort.',
  }),
  withProfile({
    profile: 'skin-musk',
    id: 'phlur-missing-person',
    name: 'Missing Person',
    brand: 'Phlur',
    priceRange: 'mid',
    priceDisplay: '$99-$110',
    scentFamilies: ['clean', 'floral', 'woody'],
    accords: ['musky', 'skin scent', 'powdery', 'woody'],
    notes: ['skin musk', 'bergamot nectar', 'jasmine', 'orange blossom', 'sandalwood'],
    vibeTags: ['skin-scent', 'nostalgic', 'intimate', 'soft', 'clean'],
    genderStyle: 'unisex',
    projection: 'subtle',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Skin musk, pale florals, and sandalwood with intimate nostalgic softness.',
  }),
  withProfile({
    profile: 'citrus-beach',
    id: 'replica-beach-walk',
    name: 'REPLICA Beach Walk',
    brand: 'Maison Margiela',
    priceRange: 'designer',
    priceDisplay: '$85-$170',
    scentFamilies: ['fresh', 'floral', 'aquatic'],
    accords: ['coconut', 'solar', 'citrus', 'white floral'],
    notes: ['bergamot', 'pink pepper', 'ylang-ylang', 'coconut milk', 'musk'],
    vibeTags: ['beach', 'solar', 'coconut', 'holiday', 'warm-skin'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Bergamot, coconut milk, ylang-ylang, and musk with sun-warmed beach energy.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'replica-coffee-break',
    name: 'REPLICA Coffee Break',
    brand: 'Maison Margiela',
    priceRange: 'designer',
    priceDisplay: '$85-$170',
    scentFamilies: ['gourmand', 'sweet', 'floral'],
    accords: ['coffee', 'lavender', 'lactonic', 'vanilla'],
    notes: ['coffee', 'lavender', 'milk mousse', 'tonka bean', 'vanilla'],
    vibeTags: ['coffee-shop', 'comforting', 'slow-weekend', 'soft', 'cozy'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'moderate',
    tier: 'designer',
    shortDescription: 'Coffee, lavender, milk mousse, tonka, and vanilla in a quiet cafe memory.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'lattafa-eclaire',
    name: 'Eclaire',
    brand: 'Lattafa',
    priceRange: 'budget',
    priceDisplay: '$35-$60',
    scentFamilies: ['gourmand', 'sweet', 'oriental'],
    accords: ['caramel', 'lactonic', 'vanilla', 'sweet'],
    notes: ['caramel', 'milk', 'sugar', 'honey', 'vanilla'],
    vibeTags: ['affordable', 'lactonic', 'caramel', 'comforting', 'strong'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    isDupe: true,
    inspiredBy: 'Bianco Latte',
    dupeOf: 'Bianco Latte',
    similarityNotes: 'A budget caramel, milk, honey, and vanilla alternative with strong sweetness.',
    shortDescription: 'A clearly labeled inspired-by lactonic caramel and vanilla gourmand.',
  }),
  withProfile({
    profile: 'green-woody',
    id: 'lattafa-liam-grey',
    name: 'Liam Grey',
    brand: 'Lattafa',
    priceRange: 'budget',
    priceDisplay: '$30-$50',
    scentFamilies: ['woody', 'spicy', 'sweet'],
    accords: ['tea', 'fig', 'woody', 'spicy'],
    notes: ['black tea', 'cardamom', 'fig', 'iris', 'sandalwood'],
    vibeTags: ['affordable', 'tea', 'fig', 'dark-academia', 'cozy'],
    genderStyle: 'unisex',
    projection: 'moderate',
    longevity: 'long',
    tier: 'designer',
    isDupe: true,
    inspiredBy: 'Gris Charnel',
    dupeOf: 'Gris Charnel',
    similarityNotes: 'A sweeter, more affordable tea, fig, cardamom, and sandalwood alternative.',
    shortDescription: 'A clearly labeled inspired-by fig tea and sandalwood fragrance.',
  }),
  withProfile({
    profile: 'fruity-playful',
    id: 'maison-alhambra-bright-peach',
    name: 'Bright Peach',
    brand: 'Maison Alhambra',
    priceRange: 'budget',
    priceDisplay: '$25-$45',
    scentFamilies: ['sweet', 'floral', 'woody'],
    accords: ['peach', 'fruity', 'vanilla', 'woody'],
    notes: ['peach', 'blood orange', 'rum', 'cognac', 'vanilla'],
    vibeTags: ['affordable', 'juicy', 'peach', 'bold', 'summer'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    isDupe: true,
    inspiredBy: 'Bitter Peach',
    dupeOf: 'Bitter Peach',
    similarityNotes: 'A sweeter affordable peach, citrus, rum, and vanilla interpretation.',
    shortDescription: 'A clearly labeled inspired-by juicy peach and boozy vanilla alternative.',
  }),
  withProfile({
    profile: 'sweet-gourmand',
    id: 'maison-alhambra-lovely-cherie',
    name: 'Lovely Chèrie',
    brand: 'Maison Alhambra',
    priceRange: 'budget',
    priceDisplay: '$25-$45',
    scentFamilies: ['sweet', 'gourmand', 'floral'],
    accords: ['cherry', 'almond', 'vanilla', 'warm spicy'],
    notes: ['sour cherry', 'bitter almond', 'rose', 'tonka bean', 'vanilla'],
    vibeTags: ['affordable', 'cherry', 'addictive', 'date-night', 'warm'],
    genderStyle: 'unisex',
    projection: 'strong',
    longevity: 'long',
    tier: 'designer',
    isDupe: true,
    inspiredBy: 'Lost Cherry',
    dupeOf: 'Lost Cherry',
    similarityNotes: 'A budget cherry, almond, rose, and vanilla interpretation with bold sweetness.',
    shortDescription: 'A clearly labeled inspired-by cherry and almond gourmand alternative.',
  }),
];
